Repository aliyun/terraform-provider-alicloud, pull requests merged in 2018-09, with the labels that each got.

#314 Retrieve the account_id automatically if needed
  CHANGELOG.md
  alicloud/common.go
  alicloud/config.go
  alicloud/resource_alicloud_fc_function.go
  alicloud/resource_alicloud_fc_service.go
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_router_interface_connection.go
  alicloud/service_alicloud_common.go
  alicloud/service_alicloud_fc.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/generate_session_access_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/get_caller_identity.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_assumed_role_user.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_credentials.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_session_access_key.go
  vendor/vendor.json
  website/docs/index.html.markdown
Labels: size/XL

#315 Base64 encode ESS scaling config user_data
  CHANGELOG.md
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
Labels: size/S

#316 Fix DB database not found error
  CHANGELOG.md
  alicloud/resource_alicloud_db_database.go
  alicloud/resource_alicloud_db_database_test.go
  alicloud/service_alicloud_rds.go
Labels: size/M

#318 Fix DNS tests falied error
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/data_source_alicloud_dns_records_test.go
  alicloud/import_alicloud_dns_record_test.go
  alicloud/import_alicloud_dns_test.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_test.go
Labels: size/L

#312 Resource CEN
  alicloud/common.go
  alicloud/config.go
  alicloud/errors.go
  alicloud/import_alicloud_cen_instance_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cen.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/associate_cen_bandwidth_package.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/attach_cen_child_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/create_cen.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/create_cen_bandwidth_package.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/delete_cen.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/delete_cen_bandwidth_package.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_attached_child_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_bandwidth_packages.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_geographic_span_remaining_bandwidth.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_inter_region_bandwidth_limits.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_region_domain_route_entries.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cen_vbr_health_check.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_cens.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_geographic_region_membership.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/describe_route_conflict.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/detach_cen_child_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/disable_cen_vbr_health_check.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/enable_cen_vbr_health_check.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/modify_cen_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/modify_cen_bandwidth_package_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/modify_cen_bandwidth_package_spec.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/set_cen_inter_region_bandwidth_limit.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_bandwidth_package.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_bandwidth_package_ids.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_bandwidth_packages.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_ids.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_inter_region_bandwidth_limit.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_inter_region_bandwidth_limits.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_route_entries.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cen_route_entry.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_cens.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_child_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_child_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_region_id.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_region_ids.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_route_conflict.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_route_conflicts.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_vbr_health_check.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/struct_vbr_health_checks.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cbn/unassociate_cen_bandwidth_package.go
  vendor/vendor.json
  website/alicloud.erb
  website/docs/r/cen_instance.html.markdown
Labels: size/XXL

#317 Add AliCloud SSL VPN client cert resource
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ssl_vpn_client_cert.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/alicloud.erb
  website/docs/r/ssl_vpn_client_cert.html.markdown
Labels: size/L

#332 Update Changelog
  CHANGELOG.md
Labels: size/XS

#327 add resource CEN Child Instance Attachment
  alicloud/errors.go
  alicloud/import_alicloud_cen_instance_attachment_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/resource_alicloud_cen_instance_attachment_test.go
  alicloud/service_alicloud_cen.go
  website/alicloud.erb
  website/docs/r/cen_instance_attachment.html.markdown
Labels: size/XL

#222 support multiaz kubernetes cluster
  alicloud/common.go
  alicloud/extension_ecs.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/vendor.json
  website/docs/r/cs_kubernetes.html.markdown
Labels: size/XL

#338 Fix knstore productId
  CHANGELOG.md
  alicloud/config.go
Labels: size/XS

#339 Allow setting the scaling group balancing policy
  CHANGELOG.md
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  website/docs/r/ess_scaling_group.html.markdown
Labels: size/S

#341 Fix alicloud db connection
  CHANGELOG.md
  alicloud/common.go
  alicloud/resource_alicloud_db_connection.go
  alicloud/resource_alicloud_db_connection_test.go
Labels: size/M

#333 Add resource CEN bandwidth package
  alicloud/errors.go
  alicloud/import_alicloud_cen_bandwidth_package_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/service_alicloud_cen.go
  website/alicloud.erb
  website/docs/r/cen_bandwidth_package.html.markdown
Labels: size/XL

#343 add new data source alicloud_disks
  CHANGELOG.md
  alicloud/data_source_alicloud_disks.go
  alicloud/data_source_alicloud_disks_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/disks.html.markdown
Labels: size/XL

#355 add worker_data_disk_category and worker_data_disk_size to kubernetes creation
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/vendor.json
  website/docs/r/cs_kubernetes.html.markdown
Labels: size/S

#356 Add AliCloud Route Table resource
  alicloud/provider.go
  alicloud/resource_alicloud_vroute_table.go
  alicloud/resource_alicloud_vroute_table_test.go
  alicloud/service_alicloud_route_table.go
  website/alicloud.erb
  website/docs/r/route_table.html.markdown
Labels: size/XL

#354 resource CEN bandwidth package attachment
  alicloud/errors.go
  alicloud/import_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/service_alicloud_cen.go
  website/alicloud.erb
  website/docs/r/cen_bandwidth_package_attachment.html.markdown
Labels: size/XL

#360 Update AliCloud Route Table resource
  alicloud/resource_alicloud_vroute_table.go
  alicloud/resource_alicloud_vroute_table_test.go
  website/alicloud.erb
  website/docs/r/route_table.html.markdown
Labels: size/L

#342 Add new data source cen_instances
  alicloud/data_source_alicloud_cen_instances.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/provider.go
  website/docs/d/cen_instances.html.markdown
Labels: size/XL

#363 Support AliCloud datasource vpn_gateways
  alicloud/common.go
  alicloud/data_source_alicloud_vpn_gateways.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/vpn_gateways.html.markdown
Labels: size/XL

#364 Support AliCloud datasource vpn_customer_gateways
  alicloud/data_source_alicloud_vpn_customer_gateways.go
  alicloud/data_source_alicloud_vpn_customer_gateways_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/vpn_customer_gateways.html.markdown
Labels: size/XL

#361 add cen bandwidth limit resource
  alicloud/import_alicloud_cen_bandwidth_limit_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/service_alicloud_cen.go
  website/alicloud.erb
  website/docs/r/cen_bandwidth_limit.html.markdown
  website/docs/r/cen_bandwidth_package.html.markdown
  website/docs/r/cen_instance_attachment.html.markdown
Labels: size/XL

#362 Add AliCloud Route Table association resource
  alicloud/import_alicloud_vroute_table_attachment_test.go
  alicloud/import_alicloud_vroute_table_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_route_table_attachment.go
  alicloud/resource_alicloud_route_table_attachment_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vroute_table.go
  alicloud/resource_alicloud_vroute_table_test.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_route_table.go
  website/alicloud.erb
  website/docs/r/route_table_attachment.html.markdown
Labels: size/XL

#367 Feature: add datasource for cen bandwidth packages.
  alicloud/data_source_alicloud_cen_bandwidth_packages.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cen_bandwidth_packages.html.markdown
Labels: size/XL

#370 Improve datasource images's docs
  CHANGELOG.md
  website/docs/d/images.html.markdown
Labels: size/XS

#372 Fix cen_instances markdown
  website/docs/d/cen_instances.html.markdown
Labels: size/XS

#374 add mns topic
  CHANGELOG.md
  alicloud/errors.go
  alicloud/import_alicloud_mns_topic_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_mns_topic.go
  alicloud/resource_alicloud_mns_topic_test.go
  alicloud/service_alicloud_mns.go
  alicloud/service_alicloud_route_table.go
  examples/mns-topic/README.md
  examples/mns-topic/main.tf
  examples/mns-topic/outputs.tf
  examples/mns-topic/variables.tf
  website/alicloud.erb
  website/docs/r/mns_queue.html.markdown
  website/docs/r/mns_topic.html.markdown
Labels: size/XL
