Repository aliyun/terraform-provider-alicloud, pull requests merged in 2018-11, with the labels that each got.

#460 Correct markdown format
  website/docs/d/cen_route_entries.html.markdown
Labels: size/XS

#454 Add AliCloud Common Bandwidth Package resource
  alicloud/common.go
  alicloud/import_alicloud_common_bandwidth_package_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  alicloud/service_alicloud_common_bandwidth_package.go
  alicloud/validators.go
  website/alicloud.erb
  website/docs/r/common_bandwidth_package.html.markdown
Labels: size/XL

#462 add resource of api gateway app support
  alicloud/errors.go
  alicloud/import_alicloud_api_gateway_app_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_api_gateway_app.go
  alicloud/resource_alicloud_api_gateway_app_test.go
  alicloud/service_alicloud_api_gateway.go
  examples/api-gateway/main.tf
  examples/api-gateway/variables.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/describe_app.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/set_apis_authorities.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/set_apps_authorities.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/struct_authorized_api.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/struct_authorized_app.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cloudapi/struct_service_config.go
  vendor/vendor.json
  website/docs/r/api_gateway_app.html.markdown
Labels: size/XL

#457 add new resource of api gateway api
  alicloud/errors.go
  alicloud/extension_api_gateway.go
  alicloud/import_alicloud_api_gateway_api_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_api_gateway_group_test.go
  alicloud/service_alicloud_api_gateway.go
  examples/api-gateway/main.tf
  examples/api-gateway/variables.tf
  examples/cen/main.tf
  examples/cen/variables.tf
  examples/log/main.tf
  examples/log/outputs.tf
  examples/log/variables.tf
  examples/slb-ca-certificate/main.tf
  examples/slb-ca-certificate/variables.tf
  examples/slb-server-certificate/main.tf
  examples/slb-server-certificate/outputs.tf
  examples/slb/main.tf
  vendor/vendor.json
  website/alicloud.erb
  website/docs/r/api_gateway_api.html.markdown
Labels: size/XXL

#464 Correct docs spelling error
  CHANGELOG.md
  website/alicloud.erb
  website/docs/d/api_gateway_apis.html.markdown
  website/docs/d/api_gateway_groups.html.markdown
Labels: size/S

#465 KVstore instance password supports at sign
  CHANGELOG.md
  alicloud/validators.go
Labels: size/XS

#466 Use product code to get common request domain
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/service_alicloud_slb.go
Labels: size/S

#463 alicloud_slb_listener support idle_timeout/request_timeout for http/h…
  alicloud/data_source_alicloud_slb_listeners.go
  alicloud/data_source_alicloud_slb_listeners_test.go
  alicloud/diff_suppress_funcs.go
  alicloud/extension_slb.go
  alicloud/import_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  examples/slb/README.md
  examples/slb/main.tf
  examples/slb/private_key.pem
  examples/slb/server_certificate.pem
  website/docs/d/slb_listeners.html.markdown
  website/docs/r/slb_listener.html.markdown
Labels: size/XL

#470 Fix pagenumber built error
  CHANGELOG.md
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_images.go
  alicloud/data_source_alicloud_instances.go
  alicloud/data_source_alicloud_key_pairs.go
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_slbs.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/service_alicloud_ess.go
Labels: size/M

#468 Add AliCloud Common Bandwidth Package Attachment resource
  alicloud/import_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  alicloud/service_alicloud_common_bandwidth_package.go
  website/alicloud.erb
  website/docs/r/common_bandwidth_package.html.markdown
  website/docs/r/common_bandwidth_package_attachment.html.markdown
Labels: size/XL

#474 support ENI attachment
  alicloud/import_alicloud_network_interface_attachment_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_network_interface_attachment.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
  alicloud/validators.go
  examples/network-interface/main.tf
  examples/network-interface/outputs.tf
  examples/network-interface/variables.tf
  website/alicloud.erb
  website/docs/r/network_interface.html.markdown
  website/docs/r/network_interface_attachment.html.markdown
Labels: size/XL

#475 support ENI datasource
  alicloud/data_source_alicloud_network_interfaces.go
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/provider.go
  examples/network-interface/main.tf
  examples/network-interface/outputs.tf
  website/alicloud.erb
  website/docs/d/network_interfaces.html.markdown
Labels: size/XL

#477 fix the bug of sg inner_access, #766
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_test.go
Labels: size/XS

#479 remove unreachable line
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#480 Fix cs_application cluster not found
  CHANGELOG.md
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/import_alicloud_network_interface_attachment_test.go
  alicloud/import_alicloud_network_interface_test.go
  alicloud/resource_alicloud_network_interface.go
  alicloud/resource_alicloud_network_interface_test.go
  alicloud/service_alicloud_cs.go
Labels: size/XS

#472 Add api gateway resource VPC support
  alicloud/errors.go
  alicloud/import_alicloud_api_gateway_vpc_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_api_gateway_vpc.go
  alicloud/resource_alicloud_api_gateway_vpc_test.go
  alicloud/service_alicloud_api_gateway.go
  examples/api-gateway-api/apigateway-api.tf
  examples/api-gateway-api/variables.tf
  examples/api-gateway-vpc/main.tf
  examples/api-gateway-vpc/variables.tf
  website/alicloud.erb
  website/docs/r/api_gateway_app.html.markdown
  website/docs/r/api_gateway_vpc_access.html.markdown
Labels: size/XL

#478 add new api gateway resource APP-Attachment support
  alicloud/errors.go
  alicloud/extension_api_gateway.go
  alicloud/provider.go
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_app_attachment.go
  alicloud/resource_alicloud_api_gateway_app_attachment_test.go
  alicloud/service_alicloud_api_gateway.go
  examples/api-gateway-api/main.tf
  examples/api-gateway-api/variables.tf
  examples/api-gateway-vpc/main.tf
  examples/ecs/main.tf
  examples/network-interface/main.tf
  examples/network-interface/outputs.tf
  examples/network-interface/variables.tf
  examples/slb/main.tf
  website/alicloud.erb
  website/docs/r/api_gateway_api.html.markdown
  website/docs/r/api_gateway_app_attachment.html.markdown
Labels: size/XL

#486 Add a new region eu-west-1
  CHANGELOG.md
  alicloud/alicloud_sweeper_test.go
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/regions.go
  alicloud/provider.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_swarm.go
Labels: size/M

#484 Support creating data disk with instance
  alicloud/errors.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  examples/ecs/main.tf
  website/docs/r/instance.html.markdown
Labels: size/XL

#488 Improve docs alicloud_db_database and alicloud_cs_kubernetes
  CHANGELOG.md
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/db_database.html.markdown
Labels: size/XS

#489 cancel the limit of system disk size
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#492 fix error about the docs format
  website/docs/d/network_interfaces.html.markdown
  website/docs/r/network_interface.html.markdown
  website/docs/r/network_interface_attachment.html.markdown
Labels: size/XS

#490 support disk resize
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_test.go
  website/docs/r/disk.html.markdown
  website/docs/r/instance.html.markdown
Labels: size/S

#495 Fix db_connection not found error when deleting
  CHANGELOG.md
  alicloud/resource_alicloud_db_connection.go
Labels: size/XS

#496 Skip ram_groups a test case
  CHANGELOG.md
  alicloud/data_source_alicloud_ram_groups_test.go
Labels: size/XS

#497 Fix examples/mns-topic parameter error
  CHANGELOG.md
  examples/ecs/main.tf
  examples/mns-topic/main.tf
  examples/mns-topic/variables.tf
Labels: size/XS

#498 update api resource that support to deploy api
  alicloud/errors.go
  alicloud/extension_api_gateway.go
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_app_attachment.go
  alicloud/service_alicloud_api_gateway.go
  examples/api-gateway-api/main.tf
  website/docs/r/api_gateway_api.html.markdown
Labels: size/XL

#500 api gateway skip app relevant tests
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  alicloud/import_alicloud_api_gateway_app_test.go
  alicloud/resource_alicloud_api_gateway_app_attachment_test.go
  alicloud/resource_alicloud_api_gateway_app_test.go
Labels: size/XS

#499 fix datahub bug when visit region of ap-southeast-1
  alicloud/connectivity/client.go
Labels: size/XS

#501 Update Changelog
  CHANGELOG.md
  alicloud/connectivity/client.go
  website/docs/r/instance.html.markdown
  website/docs/r/network_interface_attachment.html.markdown
Labels: size/XS

#502 fix an docs error.
  website/docs/r/network_interface_attachment.html.markdown
Labels: size/XS

#503 Fix pvtz_zone_record update bug
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
Labels: size/XL

#504 Improve provider config with Trim method
  CHANGELOG.md
  alicloud/provider.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/endpoints_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/local_global_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/local_regional_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/mapping_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/simple_host_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/debug.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/utils.go
  vendor/vendor.json
Labels: size/L

#505 Fix the sweeper test for CEN and CEN bandwidth package
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_instance_test.go
Labels: size/S

#509 Improve drds_instance docs
  CHANGELOG.md
  website/alicloud.erb
  website/docs/r/drds_instance.html.markdown
Labels: size/XS

#511 Fix pvtz resource priority bug
  CHANGELOG.md
  alicloud/extension_pvtz.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
  examples/pvtz/main.tf
  examples/pvtz/variables.tf
  website/docs/r/pvtz_zone_record.html.markdown
Labels: size/M

#513 fix a bug of instance testcase
  alicloud/resource_alicloud_instance_test.go
Labels: size/M

#512 support eni amount in data source instance types
  alicloud/data_source_alicloud_instance_types.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
  website/docs/d/instance_types.html.markdown
Labels: size/XS

#516 Skip automatically the testcases which does not support some known regions
  CHANGELOG.md
  README.md
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_pvtz_zone_records_test.go
  alicloud/data_source_alicloud_pvtz_zones_test.go
  alicloud/import_alicloud_datahub_project_test.go
  alicloud/import_alicloud_datahub_subscription_test.go
  alicloud/import_alicloud_datahub_topic_test.go
  alicloud/import_alicloud_drds_instance_test.go
  alicloud/import_alicloud_fc_function_test.go
  alicloud/import_alicloud_fc_service_test.go
  alicloud/import_alicloud_fc_trigger_test.go
  alicloud/import_alicloud_pvtz_zone_attachment_test.go
  alicloud/import_alicloud_pvtz_zone_record_test.go
  alicloud/import_alicloud_pvtz_zone_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_datahub_project_test.go
  alicloud/resource_alicloud_datahub_subscription_test.go
  alicloud/resource_alicloud_datahub_topic_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_fc_function_test.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
  alicloud/resource_alicloud_pvtz_zone_test.go
  alicloud/resource_alicloud_slb_test.go
Labels: size/XL

#517 Add some region limitation guide for sone resources
  CHANGELOG.md
  website/docs/r/datahub_project.html.markdown
  website/docs/r/fc_service.html.markdown
  website/docs/r/slb.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: size/XS

#518 Skip automatically the testcases which does not support multi az regions
  CHANGELOG.md
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/testing.go
Labels: size/S

#519 fix a bug of ram_use display name
  CHANGELOG.md
  alicloud/resource_alicloud_ram_user.go
  alicloud/validators.go
Labels: size/XS

#522 resouce alicloud_slb support tags.
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_slb.go
  alicloud/validators.go
  examples/slb/main.tf
  examples/slb/outputs.tf
  website/docs/r/slb.html.markdown
Labels: size/XL

#523 datasource alicloud_slbs support tags.
  alicloud/data_source_alicloud_slbs.go
  alicloud/data_source_alicloud_slbs_test.go
  alicloud/validators.go
  examples/slb/main.tf
  website/docs/d/slbs.html.markdown
Labels: size/L

#524 Skip automatically the testcases which does not support classic regions
  CHANGELOG.md
  alicloud/import_alicloud_security_group_test.go
  alicloud/resource_alicloud_security_group_rule_test.go
  alicloud/resource_alicloud_security_group_test.go
Labels: size/S

#525 fix a snat_entry bug without set id to empty
  CHANGELOG.md
  alicloud/resource_alicloud_snat.go
  alicloud/resource_alicloud_snat_test.go
Labels: size/M

#526 Skip automatically the testcases which does not support route table and classic drds
  CHANGELOG.md
  alicloud/connectivity/regions.go
  alicloud/import_alicloud_drds_instance_test.go
  alicloud/import_alicloud_route_entry_test.go
  alicloud/import_alicloud_route_table_attachment_test.go
  alicloud/import_alicloud_route_table_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_route_entry.go
  alicloud/resource_alicloud_route_entry_test.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_route_table_attachment_test.go
  alicloud/resource_alicloud_route_table_test.go
  website/docs/r/route_table.html.markdown
Labels: size/S

#528 Remove DB instance engine_version limitation
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: size/XS

#529 Fix router interface prepaid purchase
  alicloud/service_alicloud_vpc.go
Labels: size/XS

#530 Remove PayBy95 test case
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  website/docs/r/common_bandwidth_package.html.markdown
Labels: size/XS

#531 add vpc_id attribute for vpc
  alicloud/resource_alicloud_drds_instance.go
Labels: size/XS

#534 Update resource drds supported regions
  CHANGELOG.md
  alicloud/connectivity/regions.go
  website/docs/r/drds_instance.html.markdown
Labels: size/XS

#536 Fix fc_service sweeper test bug
  CHANGELOG.md
  alicloud/resource_alicloud_fc_service_test.go
Labels: size/S

#537 Fix route_entry concurrence bug and improve it testcases
  CHANGELOG.md
  alicloud/errors.go
  alicloud/extension_vpc.go
  alicloud/resource_alicloud_route_entry.go
  alicloud/resource_alicloud_route_entry_test.go
  alicloud/validators.go
  alicloud/validators_test.go
  website/alicloud.erb
  website/docs/r/route_entry.html.markdown
Labels: size/L

#535 fix tls_cipher_policy update bug for resource alicloud_slb_listener.
  alicloud/extension_slb.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  website/docs/r/slb_listener.html.markdown
Labels: size/L

#538 Skip automatically the testcases which does not support API gateway
  CHANGELOG.md
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_api_gateway_apis_test.go
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  alicloud/import_alicloud_api_gateway_api_test.go
  alicloud/import_alicloud_api_gateway_app_test.go
  alicloud/import_alicloud_api_gateway_group_test.go
  alicloud/import_alicloud_api_gateway_vpc_test.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_api_gateway_app_attachment_test.go
  alicloud/resource_alicloud_api_gateway_app_test.go
  alicloud/resource_alicloud_api_gateway_group_test.go
  alicloud/resource_alicloud_api_gateway_vpc_test.go
Labels: size/S

#539 fix listener deleted bug for resource alicloud_slb_listener.
  alicloud/resource_alicloud_slb_listener.go
Labels: size/XS

#510 Add a docs guides/getting-account to help user learn alibaba cloud acount
  website/alicloud.erb
  website/docs/guides/getting-account.html.md
  website/docs/r/drds_instance.html.markdown
Labels: size/S
