Repository aliyun/terraform-provider-alicloud, pull requests merged in 2018-08, with the labels that each got.

#265 Fixing a broken link
  website/docs/r/router_interface.html.markdown
Labels: documentation

#293 Improve data source docs
  CHANGELOG.md
  website/docs/d/db_instances.html.markdown
  website/docs/d/dns_domain_groups.html.markdown
  website/docs/d/dns_domain_records.html.markdown
  website/docs/d/dns_domains.html.markdown
  website/docs/d/dns_groups.html.markdown
  website/docs/d/dns_records.html.markdown
  website/docs/d/eips.html.markdown
  website/docs/d/images.html.markdown
  website/docs/d/instance_types.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/key_pairs.html.markdown
  website/docs/d/kms_keys.html.markdown
  website/docs/d/pvtz_zone_records.html.markdown
  website/docs/d/pvtz_zones.html.markdown
  website/docs/d/ram_account_aliases.html.markdown
  website/docs/d/ram_alias.html.markdown
  website/docs/d/ram_groups.html.markdown
  website/docs/d/ram_policies.html.markdown
  website/docs/d/ram_roles.html.markdown
  website/docs/d/ram_users.html.markdown
  website/docs/d/regions.html.markdown
  website/docs/d/router_interfaces.html.markdown
  website/docs/d/security_group_rules.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vswitches.html.markdown
  website/docs/d/zones.html.markdown
Labels: size/XXL

#295 Check pvtzconn error
  CHANGELOG.md
  alicloud/config.go
Labels: size/XS

#298 Add AliCloud VPN gateway resource
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/service_alicloud_vpn_gateway.go
  alicloud/validators.go
  website/alicloud.erb
  website/docs/r/vpn_gateway.html.markdown
Labels: size/XL

#299 Add AliCloud VPN customer gateway resource
  alicloud/provider.go
  alicloud/resource_alicloud_vpn_customer_gateway.go
  alicloud/resource_alicloud_vpn_customer_gateway_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/alicloud.erb
  website/docs/r/vpn_customer_gateway.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: size/L

#300 Enlarge sdk default timeout to fix some timeout scenario
  CHANGELOG.md
  alicloud/config.go
Labels: size/S

#304 Add AliCloud VPN connection resource
  alicloud/extension_vpn.go
  alicloud/provider.go
  alicloud/resource_alicloud_vpn_connection.go
  alicloud/resource_alicloud_vpn_connection_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/alicloud.erb
  website/docs/r/vpn_connection.html.markdown
Labels: size/XL

#310 Add force to make key pair affect immediately
  CHANGELOG.md
  alicloud/resource_alicloud_key_pair_attachment.go
  alicloud/service_alicloud_ecs.go
  website/docs/r/key_pair_attachment.html.markdown
Labels: size/M
