Repository aliyun/terraform-provider-alicloud, pull requests merged in 2018-12, with the labels that each got.

#541 Fix dns_record does not support concurrence bug
  alicloud/errors.go
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_dns_record_test.go
Labels: size/M

#543 Fix pvtz_record describing bug
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/service_alicloud_pvtz.go
Labels: size/XS

#544 Improve ecs instance and disk testcase with common case
  CHANGELOG.md
  alicloud/data_source_alicloud_disks_test.go
  alicloud/data_source_alicloud_instances_test.go
  alicloud/import_alicloud_instance_test.go
  alicloud/resource_alicloud_disk_attachment_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_common_test.go
  examples/slb/main.tf
Labels: size/XXL

#546 Fix potential bugs of datahub and ram when the resource has been deleted
  CHANGELOG.md
  alicloud/resource_alicloud_datahub_project.go
  alicloud/resource_alicloud_datahub_subscription.go
  alicloud/resource_alicloud_datahub_topic.go
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_group_membership.go
  alicloud/resource_alicloud_ram_group_policy_attachment.go
  alicloud/resource_alicloud_ram_login_profile.go
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_role.go
Labels: size/XS

#548 Improve datahub project testcase
  CHANGELOG.md
  alicloud/import_alicloud_datahub_project_test.go
  alicloud/import_alicloud_datahub_subscription_test.go
  alicloud/import_alicloud_datahub_topic_test.go
  alicloud/resource_alicloud_datahub_project_test.go
  alicloud/resource_alicloud_datahub_subscription_test.go
  alicloud/resource_alicloud_datahub_topic_test.go
Labels: size/XL

#550 Fix oss bucket deleting failed error
  CHANGELOG.md
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
Labels: size/S

#551 fixes #549
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/M

#555 Datasource alicloud_zones supports filter FunctionCompute
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_zones.go
  website/docs/d/zones.html.markdown
Labels: documentation, size/XS

#556 Fix alicloud_fc_trigger's config diff bug
  CHANGELOG.md
  alicloud/import_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/service_alicloud_fc.go
Labels: size/S

#554 Fix a bug that caused the alicloud_dns_record.routing attribute to be…
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_dns_record_test.go
Labels: size/M

#558 Fix alicloud rds related IncorrectStatus bug
  CHANGELOG.md
  alicloud/errors.go
  alicloud/import_alicloud_db_account_privilege_test.go
  alicloud/import_alicloud_db_account_test.go
  alicloud/import_alicloud_db_backup_policy_test.go
  alicloud/import_alicloud_db_connection_test.go
  alicloud/import_alicloud_db_database_test.go
  alicloud/import_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_connection_test.go
  alicloud/resource_alicloud_db_database_test.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_rds.go
Labels: size/XL

#552 Modify router interface prepaid test case
  alicloud/resource_alicloud_router_interface_test.go
  website/docs/r/router_interface.html.markdown
Labels: documentation, size/XS

#560 Improve ram_role_attachment testcase
  CHANGELOG.md
  alicloud/resource_alicloud_ram_role_attachment_test.go
Labels: size/M

#561 Improve dns_domains testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/resource_alicloud_ram_role_attachment_test.go
Labels: size/XS

#565 Fix ess_scaling_group import bugs and improve ess schedule testcase
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_schedule_test.go
Labels: size/XS

#567 Modify kvstore_instance password to Optional and improve its testcases
  CHANGELOG.md
  alicloud/extension_rds.go
  alicloud/import_alicloud_kvstore_instance_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XXL

#569 Add timeout and retry for tablestore client and Improve its testcases
  CHANGELOG.md
  alicloud.tf
  alicloud/connectivity/client.go
  alicloud/connectivity/regions.go
  alicloud/import_alicloud_ots_instance_test.go
  alicloud/import_alicloud_ots_table_test.go
  alicloud/resource_alicloud_ots_instance.go
  alicloud/resource_alicloud_ots_instance_attachment_test.go
  alicloud/resource_alicloud_ots_instance_test.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/resource_alicloud_ots_table_test.go
  alicloud/service_alicloud_ots.go
  examples/ots-table/ots.json
Labels: size/XXL

#570 Fix kvstore instance class update error
  CHANGELOG.md
  alicloud.tf
  alicloud/resource_alicloud_kvstore_instance.go
  examples/ots-table/ots.json
Labels: size/L

#571 Fix table store creating timeout error
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/service_alicloud_ots.go
Labels: size/S

#572 Fix table store describing no such host error
  CHANGELOG.md
  alicloud/service_alicloud_ots.go
Labels: size/S

#574 Fix describing endpoint failed error
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/service_alicloud_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/describe_endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/describe_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/describe_services.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/list_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/list_endpoints_by_ip.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_endpoint_list_in_list_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_endpoint_list_in_list_endpoints_by_ip.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_item_endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_protocols_in_describe_endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_protocols_in_describe_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_protocols_in_list_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_protocols_in_list_endpoints_by_ip.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_region_ids.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/location/struct_services.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#575 skip private ip test in some regions
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_network_interface_test.go
  website/docs/r/network_interface.html.markdown
Labels: documentation, size/XS

#577 VPN gateway support 200/500/1000M bandwidth
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/validators.go
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/XS

#578 Fix docs eip_association
  CHANGELOG.md
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XS

#576 fix a bug about instance charge type change
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/M

#579 Improve the describing endpoint
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
Labels: size/XS

#521 fixed bug in backup policy update
  alicloud/resource_alicloud_kvstore_backup_policy.go
  website/docs/r/kvstore_backup_policy.html.markdown
Labels: size/XS

#580 Improve kvstore backup policy testcase
  CHANGELOG.md
  alicloud/import_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
Labels: size/XL

#581 Fix pvtz_record RecordInvalidConflict bug
  CHANGELOG.md
  alicloud/common.go
  alicloud/errors.go
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/S

#583 Fix table store no such host error with deleting and updating
  CHANGELOG.md
  alicloud/resource_alicloud_ots_table.go
Labels: size/S

#584 Improve ram client endpoint
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_policy_test.go
Labels: size/M

#585 Fix provider compile error on 32bit
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#586 Improve kvstore client token
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
Labels: size/XS

#588 Fix cen instance and bandwidth multi regions test case bug
  CHANGELOG.md
  alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_cen_route_entries_test.go
  alicloud/import_alicloud_cen_bandwidth_limit_test.go
  alicloud/import_alicloud_cen_instance_attachment_test.go
  alicloud/import_alicloud_cen_route_entry_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_instance_attachment_test.go
  alicloud/resource_alicloud_cen_route_entry_test.go
Labels: size/XL

#592 Improve ram, ess schedule and cdn testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_ram_groups_test.go
  alicloud/data_source_alicloud_ram_policies_test.go
  alicloud/data_source_alicloud_ram_roles_test.go
  alicloud/data_source_alicloud_ram_users_test.go
  alicloud/import_alicloud_ram_group_test.go
  alicloud/import_alicloud_ram_login_profile_test.go
  alicloud/import_alicloud_ram_policy_test.go
  alicloud/import_alicloud_ram_role_test.go
  alicloud/import_alicloud_ram_user_test.go
  alicloud/resource_alicloud_cdn_domain_test.go
  alicloud/resource_alicloud_ess_schedule_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_ram_access_key_test.go
  alicloud/resource_alicloud_ram_account_alias_test.go
  alicloud/resource_alicloud_ram_group_membership_test.go
  alicloud/resource_alicloud_ram_group_policy_attachment_test.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role_attachment_test.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
  alicloud/resource_alicloud_ram_user_test.go
Labels: size/XXL

#593 Improve apigateway testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_api_gateway_apis_test.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  alicloud/import_alicloud_api_gateway_api_test.go
  alicloud/import_alicloud_api_gateway_group_test.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_api_gateway_group_test.go
Labels: size/XL

#594 Fix log service timeout error
  CHANGELOG.md
  alicloud/errors.go
  alicloud/import_alicloud_log_machine_group_test.go
  alicloud/import_alicloud_log_project_test.go
  alicloud/import_alicloud_log_store_index_test.go
  alicloud/import_alicloud_log_store_test.go
  alicloud/resource_alicloud_log_machine_group.go
  alicloud/resource_alicloud_log_machine_group_test.go
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_log_store.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/resource_alicloud_log_store_index_test.go
  alicloud/resource_alicloud_log_store_test.go
  alicloud/service_alicloud_log.go
Labels: size/XL

#599 Improve kvstore and ess schedule testcase
  CHANGELOG.md
  alicloud/import_alicloud_ess_schedule_test.go
  alicloud/resource_alicloud_kvstore_instance_test.go
Labels: size/S

#600 Improve ess configuration testcase
  CHANGELOG.md
  alicloud/import_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XL

#603 Support update ess lifecycle hook name and improve ess testcase by random name
  CHANGELOG.md
  alicloud/import_alicloud_ess_alarm_test.go
  alicloud/import_alicloud_ess_lifecycle_hook_test.go
  alicloud/import_alicloud_ess_scalinggroup_test.go
  alicloud/import_alicloud_ess_schedule_test.go
  alicloud/resource_alicloud_ess_alarm_test.go
  alicloud/resource_alicloud_ess_lifecyclehook.go
  alicloud/resource_alicloud_ess_lifecyclehook_test.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  alicloud/resource_alicloud_ess_scalingrule_test.go
  alicloud/resource_alicloud_ess_schedule_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_scaling_lifecycle_hook.html.markdown
Labels: documentation, size/XXL

#604 Fix deleting ess group timeout bug
  CHANGELOG.md
  alicloud/service_alicloud_ess.go
Labels: size/XS

#606 Fix oss bucket object testcase destroy bug
  CHANGELOG.md
  alicloud/resource_alicloud_oss_bucket_object_test.go
Labels: size/S
