Repository aliyun/terraform-provider-alicloud, pull requests merged in 2018-10, with the labels that each got.

#381 Fix alicloud_ram_user_policy_attachment EntityNotExist.User error
  alicloud/resource_alicloud_ram_user_policy_attachment.go
Labels: size/XS

#382 add datasources mns queues
  alicloud/data_source_alicloud_mns_queue.go
  alicloud/data_source_alicloud_mns_queue_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/mns_queues.html.markdown
Labels: size/L

#383 RAM support useragent
  alicloud/config.go
  vendor/github.com/denverdino/aliyungo/ram/api.go
  vendor/vendor.json
Labels: size/XS

#384 add topic datasource
  alicloud/data_source_alicloud_mns_topic.go
  alicloud/data_source_alicloud_mns_topic_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/mns_queues.html.markdown
  website/docs/d/mns_topics.html.markdown
Labels: size/L

#385 Improve resource ram_policy's document validatefunc
  alicloud/resource_alicloud_ram_policy.go
Labels: size/XS

#386 add subscription datasource
  alicloud/data_source_alicloud_mns_queue.go
  alicloud/data_source_alicloud_mns_topic.go
  alicloud/data_source_alicloud_mns_topic_subscription.go
  alicloud/data_source_alicloud_mns_topic_subscription_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_mns_topic.go
  alicloud/service_alicloud_mns.go
  website/alicloud.erb
  website/docs/d/mns_topic_subscriptions.html.markdown
Labels: size/XL

#379 Update Changelog
  CHANGELOG.md
  alicloud/data_source_alicloud_mns_topic_subscription.go
  website/docs/d/mns_topic_subscriptions.html.markdown
  website/docs/d/mns_topics.html.markdown
  website/docs/r/mns_topic_subscription.html.markdown
Labels: size/S

#391 Update changelog
  CHANGELOG.md
Labels: size/XS

#393 Improve example/ecs-key-pair
  examples/ecs-key-pair/main.tf
  examples/ecs-key-pair/variables.tf
Labels: size/XS

#392 Change key pair file mode to 400
  alicloud/resource_alicloud_key_pair.go
Labels: size/XS

#394 Add new example/pvtz
  examples/pvtz/README.md
  examples/pvtz/main.tf
  examples/pvtz/outputs.tf
  examples/pvtz/variables.tf
Labels: size/M

#395 Remove useless datasource cache file
  examples/dns/domains.txt
  examples/dns/main.tf
  examples/dns/records.txt
  examples/ram/alias.txt
Labels: size/M

#398 modify the sweeptest nameprefix
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/resource_alicloud_mns_topic_test.go
Labels: size/XS

#399 Skip havip test case
  alicloud/import_alicloud_havip_attachment_test.go
  alicloud/import_alicloud_havip_test.go
  alicloud/resource_alicloud_havip_attachment_test.go
  alicloud/resource_alicloud_havip_test.go
Labels: size/XL

#400 modify the mns err info
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/resource_alicloud_mns_topic_test.go
Labels: size/XS

#404 Add new resource datahub_topic
  CHANGELOG.md
  alicloud/import_alicloud_datahub_topic_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_datahub_topic.go
  alicloud/resource_alicloud_datahub_topic_test.go
  website/alicloud.erb
  website/docs/r/datahub_topic.html.markdown
Labels: size/XL

#405 Add new resource datahub_subscription
  CHANGELOG.md
  alicloud/import_alicloud_datahub_subscription_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_datahub_subscription.go
  alicloud/resource_alicloud_datahub_subscription_test.go
  website/alicloud.erb
  website/docs/r/datahub_subscription.html.markdown
Labels: size/XL

#406 Add new example/datahub
  CHANGELOG.md
  examples/datahub/README.md
  examples/datahub/main.tf
  examples/datahub/outputs.tf
  examples/datahub/variables.tf
Labels: size/M

#410 fix kubernetes's new_nat_gateway issue
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/vendor.json
Labels: size/S

#407 add fc example
  examples/fc/README.md
  examples/fc/hello.py
  examples/fc/main.tf
  examples/fc/outputs.tf
  examples/fc/variables.tf
Labels: size/L

#412 add new data source of api gateway groups
  alicloud/data_source_alicloud_api_gateway_groups.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  alicloud/provider.go
  examples/api-gateway/main.tf
  website/alicloud.erb
  website/docs/d/api_gateway_groups.html.markdown
Labels: size/L

#414 added need_slb attribute to cs swarm
  CHANGELOG.md
  alicloud/import_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_cs_swarm_test.go
  website/docs/r/cs_swarm.html.markdown
Labels: size/M

#417 Improve examples/ots-table
  CHANGELOG.md
  examples/ots-table/main.tf
Labels: size/S

#420 Hide AliCloud HaVip Attachment resource docs because of it is not public totally
  alicloud/errors.go
  alicloud/resource_alicloud_havip_attachment.go
  website/alicloud.erb
  website/docs/r/havip_attachment.html.markdown
  website/docs/r/route_table_attachment.html.markdown
Labels: size/XS

#422 change child instance type Vbr to VBR and replace some const variables
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/service_alicloud_cen.go
Labels: size/XS

#426 resource alicloud_slb_listener support acl.
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  examples/slb/README.md
  examples/slb/main.tf
  examples/slb/outputs.tf
  website/docs/r/slb_listener.html.markdown
Labels: size/L

#425 Update AliCloud Router Interface resource
  alicloud/import_alicloud_router_interface_test.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_router_interface_connection_test.go
  alicloud/resource_alicloud_router_interface_test.go
  alicloud/service_alicloud_vpc.go
  alicloud/validators.go
  website/docs/r/router_interface.html.markdown
Labels: size/M

#427 Fix alicloud_ess_scaling_configuration setting data_disk failed
  CHANGELOG.md
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: size/M

#428 Fix reources' id description bugs
  CHANGELOG.md
  website/docs/r/cs_application.html.markdown
  website/docs/r/datahub_subscription.html.markdown
  website/docs/r/datahub_topic.html.markdown
  website/docs/r/db_account.html.markdown
  website/docs/r/db_account_privilege.html.markdown
  website/docs/r/db_connection.html.markdown
  website/docs/r/db_database.html.markdown
  website/docs/r/fc_function.html.markdown
  website/docs/r/fc_trigger.html.markdown
  website/docs/r/log_machine_group.html.markdown
  website/docs/r/log_store.html.markdown
  website/docs/r/log_store_index.html.markdown
  website/docs/r/ots_table.html.markdown
  website/docs/r/slb.html.markdown
  website/docs/r/slb_listener.html.markdown
Labels: size/S

#434 Modify mns test case name
  CHANGELOG.md
  alicloud/data_source_alicloud_mns_queue_test.go
  alicloud/data_source_alicloud_mns_topic_subscription_test.go
  alicloud/data_source_alicloud_mns_topic_test.go
  alicloud/import_alicloud_mns_queue_test.go
  alicloud/import_alicloud_mns_topic_subscription_test.go
  alicloud/import_alicloud_mns_topic_test.go
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/resource_alicloud_mns_topic_subscription_test.go
  alicloud/resource_alicloud_mns_topic_test.go
Labels: size/XS

#435 Improve datahub_project sweeper test
  CHANGELOG.md
  alicloud/resource_alicloud_datahub_project_test.go
Labels: size/XS

#438 add resource alicloud_slb_ca_certificate support.
  alicloud/errors.go
  alicloud/import_alicloud_slb_ca_certificate_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_ca_certificate_test.go
  alicloud/service_alicloud_slb.go
  examples/slb-ca-certificate/README.md
  examples/slb-ca-certificate/ca_certificate.pem
  examples/slb-ca-certificate/main.tf
  examples/slb-ca-certificate/outputs.tf
  examples/slb-ca-certificate/variables.tf
  website/alicloud.erb
  website/docs/r/slb_ca_certificate.html.markdown
Labels: size/XL

#436 add resource alicloud_slb_server_certificate support.
  alicloud/diff_suppress_funcs.go
  alicloud/errors.go
  alicloud/import_alicloud_slb_server_certificate_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  alicloud/service_alicloud_slb.go
  examples/slb-server-certificate/README.md
  examples/slb-server-certificate/main.tf
  examples/slb-server-certificate/outputs.tf
  examples/slb-server-certificate/private_key.pem
  examples/slb-server-certificate/server_certificate.pem
  examples/slb-server-certificate/variables.tf
  website/alicloud.erb
  website/docs/r/slb_server_certificate.html.markdown
Labels: size/XL

#440 resource alicloud_slb_listener tcp protocol support established_timeout parameter
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  examples/slb/README.md
  examples/slb/main.tf
  examples/slb/outputs.tf
  website/docs/r/slb_listener.html.markdown
Labels: size/S

#441 Fix mns resource docs bug
  CHANGELOG.md
  website/docs/r/mns_queue.html.markdown
  website/docs/r/mns_topic.html.markdown
  website/docs/r/mns_topic_subscription.html.markdown
Labels: size/XS

#443 add data source alicloud_slb_acls.
  alicloud/data_source_alicloud_slb_acls.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/provider.go
  alicloud/service_alicloud_slb.go
  examples/slb-acl/main.tf
  examples/slb-acl/variables.tf
  examples/slb/main.tf
  website/alicloud.erb
  website/docs/d/slb_acls.html.markdown
Labels: size/XL

#447 Update changelog
  CHANGELOG.md
Labels: size/XS

#448 Update changelog
  CHANGELOG.md
Labels: size/XS

#450 Remove CDN default configuration (optimize_enable, page_compress_enab…
  alicloud/common.go
  alicloud/resource_alicloud_cdn_domain.go
Labels: size/M

#459 Bugfix: set number of cen instances five for normal alicloud account testcases
  alicloud/data_source_alicloud_cen_instances_test.go
Labels: size/XS
