Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-02, with the labels that each got.

#753 delete success if not found cen route when delete
  alicloud/errors.go
  alicloud/resource_alicloud_cen_route_entry.go
Labels: size/XS

#757 update changelog
  CHANGELOG.md
Labels: size/XS

#762 fix sls logtail config collection error
  alicloud/resource_alicloud_logtail_config.go
Labels: size/XS

#767 add three az k8s cluster docs
  website/docs/r/cs_kubernetes.html.markdown
Labels: documentation, size/M

#771 support update deletion_protection option
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#770 fix(error) Fixed bug of error code when timeout for upgrade instance
  alicloud/errors.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/XS

#772 Update changelog for 1.31.0
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_groups.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/service_alicloud_rds.go
Labels: size/XS

#773 Fix cms_alarm updating notify_type bug
  CHANGELOG.md
  alicloud/resource_alicloud_cms_alarm.go
Labels: size/S

#779 fix(whitelist) Modified whitelist returned and filter the default values
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/S

#778 add useragent
  CHANGELOG.md
  alicloud/connectivity/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/acs_request.go
  vendor/vendor.json
Labels: dependencies, size/M

#763 Modify kms client to dock with the alicloud official GO SDK
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_kms_keys.go
  alicloud/data_source_alicloud_kms_keys_test.go
  alicloud/resource_alicloud_kms_key.go
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/service_alicloud_kms.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/cancel_key_deletion.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/create_alias.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/create_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/decrypt.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/delete_alias.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/delete_key_material.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/describe_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/disable_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/enable_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/encrypt.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/generate_data_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/get_parameters_for_import.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/import_key_material.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/list_aliases.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/list_aliases_by_key_id.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/list_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/schedule_key_deletion.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_alias.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_aliases_in_list_aliases.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_aliases_in_list_aliases_by_key_id.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_key_metadata.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_region.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/struct_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/kms/update_alias.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#785 cen child instance attach after vsw created
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_cen_route_entries_test.go
  alicloud/resource_alicloud_cen_route_entry_test.go
  examples/cen/main.tf
  website/docs/r/cen_route_entry.html.markdown
Labels: documentation, size/XS

#786 make the timeout longer when cen attach/detach vpc
  alicloud/resource_alicloud_cen_instance_attachment.go
Labels: size/XS

#784 kvstore support parameter configuration
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_kvstore.go
  examples/kvstore/main.tf
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XL

#788 update alibaba-cloud-sdk-go to use lastest useragent and modify errMessage when signature does not match
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/errors/signature_does_not_match_wrapper.go
  vendor/vendor.json
Labels: dependencies, size/XS

#790 Add account site type setting to skip unsupported test cases automatically
  CHANGELOG.md
  README.md
  alicloud/common.go
  alicloud/data_source_alicloud_kms_keys.go
  alicloud/data_source_alicloud_router_interfaces_test.go
  alicloud/data_source_alicloud_vpn_connections_test.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/import_alicloud_db_read_write_splitting_connection_test.go
  alicloud/import_alicloud_router_interface_connection_test.go
  alicloud/import_alicloud_router_interface_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_db_readwrite_splitting_connection_test.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_route_entry_test.go
  alicloud/resource_alicloud_router_interface_connection_test.go
  alicloud/resource_alicloud_router_interface_test.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/resource_alicloud_vpn_connection_test.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/service_alicloud_kms.go
  examples/elasticsearch/variables.tf
  examples/kvstore/main.tf
Labels: size/M

#792 Improve instance and security group testcase for different account site
  CHANGELOG.md
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/import_alicloud_security_group_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/service_alicloud_kvstore.go
Labels: size/XS

#799 Fix vpc return custom route table bug
  CHANGELOG.md
  alicloud/resource_alicloud_vpc.go
Labels: size/M

#800 Fix dns record ttl setting error and update bug
  CHANGELOG.md
  alicloud/import_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_dns_record_test.go
Labels: size/M

#803 fix first create db with tags
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#804 fix rds parameter update issue
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
  website/docs/r/db_readonly_instance.html.markdown
Labels: documentation, size/L

#805 update alicloud_slb_attachment usage example
  website/docs/r/slb_attachment.html.markdown
Labels: documentation, size/XS

#806 add slb_internet_enabled to managed kubernetes
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS
