Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-07, with the labels that each got.

#1362 Fix oss bucket datasource testcase based on the 0.12 syntax
  CHANGELOG.md
  alicloud/data_source_alicloud_oss_bucket_objects_test.go
Labels: size/XS

#1365 update erb file
  website/alicloud.erb
Labels: documentation, size/M

#1354 Adapt to new parameters of dedicated kubernetes cluster
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  website/docs/r/cs_kubernetes.html.markdown
Labels: documentation, size/XL

#1368 Fix alicloud_cas_certificate setId bug
  CHANGELOG.md
  alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/data_source_alicloud_ddoscoo_instances_test.go
  alicloud/resource_alicloud_cas_certificate.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  alicloud/resource_alicloud_ddoscoo_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  examples/ddoscoo/main.tf
  website/docs/r/ddoscoo_instance.html.markdown
Labels: documentation, size/XL

#1370 Improve(cs_kubernetes): add import ignore parameter `log_config`
  alicloud/resource_alicloud_cs_kubernetes_test.go
Labels: size/XS

#1364 improve(drds_instance): Added precheck to its testcases.
  alicloud/data_source_alicloud_drds_instances_test.go
  alicloud/resource_alicloud_drds_instance_test.go
Labels: size/XS

#1369 improve(slb):support slb instance delete protection
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/M

#1371 feature: add data source kvstore instance engines
  alicloud/data_source_alicloud_db_instance_engines.go
  alicloud/data_source_alicloud_kvstore_instance_classes.go
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
  alicloud/data_source_alicloud_kvstore_instance_engines.go
  alicloud/data_source_alicloud_kvstore_instance_engines_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kvstore_instance_engines.html.markdown
Labels: documentation, size/XL

#1327 improve(launch_template): support update method
  alicloud/import_alicloud_launch_template_test.go
  alicloud/resource_alicloud_launch_template.go
  alicloud/resource_alicloud_launch_template_test.go
  alicloud/service_alicloud_ecs.go
  website/docs/r/launch_template.html.markdown
Labels: documentation, size/XXL

#1366 Improve(oss_bucket_object): Improve its use common method.
  alicloud/data_source_alicloud_oss_bucket_objects.go
  alicloud/data_source_alicloud_oss_bucket_objects_test.go
  alicloud/resource_alicloud_oss_bucket_object.go
  alicloud/resource_alicloud_oss_bucket_object_test.go
  alicloud/service_alicloud_oss.go
Labels: size/XL

#1373 fix(cen): fixed its not display error message, added CenThrottlingUse…
  alicloud/data_source_alicloud_cen_bandwidth_limits.go
  alicloud/data_source_alicloud_cen_bandwidth_packages.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/data_source_alicloud_cen_instances.go
  alicloud/errors.go
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_route_entry_test.go
  alicloud/service_alicloud_cen.go
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/M

#1372 improve(common_test):update common_test for terraform 0.12
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1377 cs_kubernetes import ignore log_config
  README.md
  alicloud/data_source_alicloud_cen_bandwidth_limits.go
  alicloud/data_source_alicloud_drds_instances_test.go
  alicloud/data_source_alicloud_kvstore_instance_engines.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_launch_template.go
  alicloud/resource_alicloud_launch_template_test.go
  alicloud/service_alicloud_oss.go
Labels: size/S

#1375 fix(kvstore): kvstore_instance PostPaid to PrePaid error
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/S

#1378 improve(disk): the snapshot_id conflicts with encrypted
  alicloud/resource_alicloud_disk.go
  website/docs/r/disk.html.markdown
Labels: documentation, size/XS

#1383 improve(db_instance_classes): add new parameter db_instance_class
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/data_source_alicloud_db_instance_classes_test.go
  website/docs/d/db_instance_classes.html.markdown
Labels: documentation, size/XS

#1353 Improve(oss_bucket): Improve its resource use common method.
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_object.go
  alicloud/resource_alicloud_oss_bucket_test.go
  alicloud/service_alicloud_oss.go
Labels: documentation, size/XXL

#1367 improve(slb_rule): support health check config
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb_rule.go
  alicloud/resource_alicloud_slb_rule_test.go
  examples/slb-rule/main.tf
  website/docs/r/slb_rule.html.markdown
Labels: documentation, size/XXL

#1381 fix(cen):Add deadline to cen datasources and modify timeout for Descr…
  alicloud/data_source_alicloud_cen_bandwidth_limits.go
  alicloud/data_source_alicloud_cen_bandwidth_packages.go
  alicloud/data_source_alicloud_cen_instances.go
  alicloud/service_alicloud_cen.go
Labels: size/XS

#1386 Remove govendor commands in CI
  .travis.yml
  GNUmakefile
Labels: size/XS

#1387 improve(cs_kubernetes): add importIgnore parameters in the importer testcase
  alicloud/resource_alicloud_cs_kubernetes_test.go
Labels: size/XS

#1388 fix(db_backup_policy): pg10 of category 'basic' modify log_backup error
  alicloud/resource_alicloud_db_backup_policy_test.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/XS

#1384 improve(slb_vserver_group): support attaching eni
  alicloud/extension_slb.go
  alicloud/resource_alicloud_slb_server_group.go
  alicloud/resource_alicloud_slb_server_group_test.go
  examples/slb-server-group/main.tf
  website/docs/r/slb_server_group.html.markdown
Labels: documentation, size/M

#1391 improve(db_instance): improve db_instance MAZ testcase
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#1390 fix(slb_rule): fix testcase bug
  alicloud/resource_alicloud_slb_rule.go
Labels: size/XS

#1374 Improve(oss_bucket): Add names for its attributes of datasource.
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_oss_buckets_test.go
  website/docs/d/oss_buckets.html.markdown
Labels: documentation, size/XL

#1392 fix(vswitch):fix vswitch describe method wrapErrorf bug
  alicloud/service_alicloud_vpc.go
Labels: size/XS

#1380 improve(images): Add os_name_en to the attributes of images datasource.
  alicloud/data_source_alicloud_images.go
  alicloud/data_source_alicloud_images_test.go
  website/docs/d/images.html.markdown
Labels: documentation, size/XL

#1396 fix(instancd):fix testcase name too length bug
  alicloud/resource_alicloud_instance_test.go
Labels: size/XS

#1398 fix(route_entry):fix route_entry create bug
  alicloud/resource_alicloud_route_entry.go
Labels: size/XS

#1397 update CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#1400 fix(oss_bucket): fix oss bucket deleting timeout error
  CHANGELOG.md
  alicloud/resource_alicloud_oss_bucket.go
Labels: size/XS

#1401 fix(instnace): fix missing dry_run when creating instance
  CHANGELOG.md
  alicloud/data_source_alicloud_snapshots_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_snapshot_test.go
Labels: size/XS

#1404 improve(provider): add a new parameter in the provider config
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/regions.go
  alicloud/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#1389 improve(rds): resource db_instance support update for instance_charge_type
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/S

#1403 fix(db_readonly_instance): add retryable error content in instance spec modification and deletion
  alicloud/data_source_alicloud_mongodb_instances_test.go
  alicloud/resource_alicloud_db_readonly_instance.go
Labels: size/XS

#1408 fix(db_readonly_instance): extend the waiting time for spec modification
  alicloud/resource_alicloud_db_readonly_instance.go
Labels: size/XS

#1410 fix(api_gateway): modified the testcase to avoid errors.
  alicloud/resource_alicloud_api_gateway_vpc_test.go
Labels: size/XS

#1413 improve(gpdb_instance):add vpc name
  alicloud/data_source_alicloud_gpdb_instances_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_launch_template_test.go
Labels: size/XS

#1420 improve(vpc):add ids filter
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/data_source_alicloud_vswitches_test.go
  website/docs/d/security_groups.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vswitches.html.markdown
Labels: documentation, size/M

#1411 feat(ons_instances): new datasource alicloud_ons_instances
  alicloud/data_source_alicloud_ons_instances.go
  alicloud/data_source_alicloud_ons_instances_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_ons_instance.go
  alicloud/resource_alicloud_ons_instance_test.go
  website/alicloud.erb
  website/docs/d/ons_instances.html.markdown
Labels: documentation, size/XL

#1417 improve(cas): Added ids filter and added names to datasource attributes.
  alicloud/data_source_alicloud_cas_certificates.go
  alicloud/data_source_alicloud_cas_certificates_test.go
  website/docs/d/cas_certificates.html.markdown
Labels: documentation, size/L

#1418 fix(db_instance):fix db_instance testcase vsw availability_zone
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1407 improve(kms): modified the args of kms_keys datasource.
  alicloud/data_source_alicloud_kms_keys.go
  alicloud/data_source_alicloud_kms_keys_test.go
  website/docs/d/kms_keys.html.markdown
Labels: documentation, size/XL

#1406 improve(kms_key): modify the param `description` to forcenew
  alicloud/resource_alicloud_kms_key.go
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/service_alicloud_kms.go
  website/docs/r/kms_key.html.markdown
Labels: documentation, size/L

#1393 improve(cdn): cdn_domain support certificate config.
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/resource_alicloud_cdn_domain_config_test.go
  alicloud/resource_alicloud_cdn_domain_new.go
  alicloud/resource_alicloud_cdn_domain_new_test.go
  alicloud/resource_alicloud_cdn_domain_test.go
  alicloud/service_alicloud_cdn.go
  website/docs/r/cdn_domain_new.html.markdown
Labels: documentation, size/XXL

#1419 improve(db_instances): Added ids filter and added names to datasource attributes.
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_db_instances_test.go
  website/docs/d/db_instances.html.markdown
Labels: documentation, size/S

#1421 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1422 improve(mns):modified mns_queues.html
  website/docs/d/mns_queues.html.markdown
Labels: documentation, size/XS

#1424 fix(db_backup_policy): resource db_backup_policy testcase use datasource db_instance_classes
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/S

#1423 improve(docs): Reformat abnormal inline HCL code in docs
  website/docs/d/nas_mount_targets.html.markdown
  website/docs/d/ons_instances.html.markdown
  website/docs/r/network_interface_attachment.html.markdown
  website/docs/r/oss_bucket.html.markdown
  website/docs/r/pvtz_zone_record.html.markdown
  website/docs/r/ram_group_membership.html.markdown
  website/docs/r/slb_acl.html.markdown
Labels: documentation, size/XL

#1428 improve(rds):update ppas not support regions
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/resource_alicloud_db_backup_policy_test.go
Labels: size/XS

#1432 improve(rds):improve db_readonly_instance TestAccAlicloudDBReadonlyIn…
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#1431 improve(key_pairs): Added ids filter to datasource.
  alicloud/data_source_alicloud_key_pairs.go
  alicloud/data_source_alicloud_key_pairs_test.go
  website/docs/d/key_pairs.html.markdown
Labels: documentation, size/M

#1430 improve(elasticsearch): Added ids filter and added descriptions to da…
  alicloud/data_source_alicloud_elasticsearch_instances.go
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  website/docs/d/elasticsearch.html.markdown
Labels: documentation, size/M

#1429 improve(drds): Added descriptions to attributes of datasource.
  alicloud/data_source_alicloud_drds_instances.go
  alicloud/data_source_alicloud_drds_instances_test.go
  website/docs/d/drds_instances.html.markdown
Labels: documentation, size/XS

#1427 improve(api_gateway_groups): Added ids filter to datasource.
  alicloud/data_source_alicloud_api_gateway_groups.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  website/docs/d/api_gateway_groups.html.markdown
Labels: documentation, size/S

#1409 improve(rds): db_instance resource supports timeouts setting.
  alicloud/resource_alicloud_db_instance.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/S

#1435 fix(db_readonly_instance): fix invalid status error when updating and deleting
  alicloud/data_source_alicloud_cas_certificates.go
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_kms_keys_test.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/errors.go
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/resource_alicloud_db_connection.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_gpdb_connection.go
  alicloud/resource_alicloud_kms_key.go
  alicloud/service_alicloud_rds.go
Labels: size/S

#1434 fix(ots_table): fix setting deviation_cell_version_in_sec error
  alicloud/resource_alicloud_ots_table.go
  website/docs/r/ots_table.html.markdown
Labels: documentation, size/XS

#1437 fix(db_instance): modified the target state of state config.
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#1438 improve(rds): db_readonly_instance resource supports timeouts setting.
  alicloud/resource_alicloud_db_readonly_instance.go
  website/docs/r/db_readonly_instance.html.markdown
Labels: documentation, size/XS

#1447 support online resize
  alicloud/errors.go
  alicloud/extension_ecs.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_attachment_test.go
Labels: size/M

#1454 fix(slb): fix slb testcase can not find instance types' bug
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_listener_test.go
Labels: size/XS

#1449 add CI for the alicloud provider
  .gitignore
  ci/configure
  ci/pipeline.yml
  ci/tasks/run.sh
  ci/tasks/run.yml
Labels: size/XXL

#1456 improve(cas): Added precheck to testcases.
  alicloud/data_source_alicloud_cas_certificates_test.go
Labels: size/XS

#1455 improve(rds): db_instance and db_readonly_instance resource modify ti…
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_readonly_instance.go
  website/docs/r/db_instance.html.markdown
  website/docs/r/db_readonly_instance.html.markdown
Labels: documentation, size/XS

#1405 improve(cdn): cdn_domain_config added testcases.
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/resource_alicloud_cdn_domain_config_test.go
Labels: size/XXL

#1425 improve(api_gateway_apis): Added ids filter to datasource.
  alicloud/data_source_alicloud_api_gateway_apis.go
  alicloud/data_source_alicloud_api_gateway_apis_test.go
  website/docs/d/api_gateway_apis.html.markdown
Labels: documentation, size/M

#1462 improve(stateConfig):update stateConfig error
  alicloud/errors.go
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_drds_instance.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_snapshot.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/M

#1463 improve(dns_groups): Added ids filter and added names to datasource attributes.
  alicloud/data_source_alicloud_dns_groups.go
  alicloud/data_source_alicloud_dns_groups_test.go
  website/docs/d/dns_groups.html.markdown
Labels: documentation, size/M

#1464 improve(dns_records): Added ids filter to datasource.
  alicloud/data_source_alicloud_dns_records.go
  alicloud/data_source_alicloud_dns_records_test.go
  website/docs/d/dns_records.html.markdown
Labels: documentation, size/S

#1426 improve(api_gateway_apps): Added ids filter to datasource.
  alicloud/data_source_alicloud_api_gateway_apps.go
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  website/docs/d/api_gateway_apps.html.markdown
Labels: documentation, size/S

#1457 improve(kvstore): Added ids filter to datasource.
  alicloud/data_source_alicloud_kvstore_instances.go
  alicloud/data_source_alicloud_kvstore_instances_test.go
  website/docs/d/kvstore_instances.html.markdown
Labels: documentation, size/S

#1467 improve(cdn): Added retry to avoid ServiceBusy error.
  alicloud/resource_alicloud_cdn_domain_new.go
Labels: size/XS

#1465 fix(kvstore_instance): resource kvstore_instance add Retry while Modi…
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/XS

#1416 fix(slb_server_group): fix the maximum number of backend servers added to a slb_server_group
  alicloud/extension_slb.go
  alicloud/resource_alicloud_slb_server_group.go
  alicloud/resource_alicloud_slb_server_group_test.go
  examples/slb-server-group/main.tf
Labels: documentation, size/XL

#1480 增加PrivateIPAddress字段，修改markdown中内容
  alicloud/resource_alicloud_eip_association.go
  alicloud/resource_alicloud_eip_association_test.go
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XS

#1479 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1478 improve(mongodb_instances): Added ids filter to datasource.
  alicloud/data_source_alicloud_kvstore_instance_engines_test.go
  alicloud/data_source_alicloud_mongodb_instances.go
  alicloud/data_source_alicloud_mongodb_instances_test.go
  website/docs/d/mongodb_instances.html.markdown
Labels: documentation, size/S

#1468 improve(dns_domain): Added ids filter to datasource.
  alicloud/data_source_alicloud_dns_domains.go
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/resource_alicloud_dns.go
  website/docs/d/dns_domains.html.markdown
  website/docs/r/dns.html.markdown
Labels: documentation, size/S

#1481 change to 1.52.2
  CHANGELOG.md
  alicloud/data_source_alicloud_api_gateway_apis.go
  website/docs/d/api_gateway_apis.html.markdown
  website/docs/d/api_gateway_apps.html.markdown
  website/docs/d/dns_groups.html.markdown
  website/docs/d/dns_records.html.markdown
  website/docs/d/kvstore_instances.html.markdown
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XS

#1441 improve(mns_topic_subscriptions): Added names to datasource attributes.
  alicloud/data_source_alicloud_mns_topic_subscriptions.go
  alicloud/data_source_alicloud_mns_topic_subscriptions_test.go
  alicloud/errors.go
  website/docs/d/mns_topic_subscriptions.html.markdown
Labels: documentation, size/M

#1486 fix(api_gateway): fix can't get resource id when stage_names set.
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_api_test.go
Labels: size/S

#1450 improve(nas_file_systems): Added descriptions to datasource attributes.
  alicloud/data_source_alicloud_nas_file_systems.go
  alicloud/data_source_alicloud_nas_file_systems_test.go
  website/docs/d/nas_file_systems.html.markdown
Labels: documentation, size/XS

#1451 fix(cen): modified the timeouts of cen instance to avoid errors.
  alicloud/resource_alicloud_cen_instance.go
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/XS

#1444 improve(nas_access_groups): Added names to its attributes.
  alicloud/data_source_alicloud_nas_access_groups.go
  alicloud/data_source_alicloud_nas_access_groups_test.go
  website/docs/d/nas_access_groups.html.markdown
Labels: documentation, size/S

#1488 Improve(mns_topic): Improve its resource use common method.
  alicloud/resource_alicloud_mns_topic.go
  alicloud/resource_alicloud_mns_topic_test.go
  alicloud/service_alicloud_mns.go
Labels: size/L

#1448 improve(nas_access_rules): Added ids filter to datasource.
  alicloud/data_source_alicloud_nas_access_rules.go
  alicloud/data_source_alicloud_nas_access_rules_test.go
  alicloud/resource_alicloud_nas_access_rule.go
  website/docs/d/nas_access_rules.html.markdown
  website/docs/r/nas_access_rule.html.markdown
Labels: documentation, size/M

#1485 Improve(mns_queue): Improve its resource use common method.
  alicloud/resource_alicloud_mns_queue.go
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/service_alicloud_mns.go
Labels: size/XL

#1475 improve(fc_triggers): Added ids filter to datasource.
  alicloud/data_source_alicloud_fc_triggers.go
  alicloud/data_source_alicloud_fc_triggers_test.go
  alicloud/resource_alicloud_fc_trigger.go
  website/docs/d/fc_triggers.html.markdown
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/S

#1474 improve(fc_services): Added ids filter to datasource.
  alicloud/data_source_alicloud_fc_services.go
  alicloud/data_source_alicloud_fc_services_test.go
  alicloud/resource_alicloud_fc_service.go
  website/docs/d/fc_services.html.markdown
  website/docs/r/fc_service.html.markdown
Labels: documentation, size/S

#1473 improve(fc_functions): Added ids filter to datasource.
  alicloud/data_source_alicloud_fc_functions.go
  alicloud/data_source_alicloud_fc_functions_test.go
  alicloud/resource_alicloud_fc_function.go
  website/docs/d/fc_functions.html.markdown
  website/docs/r/fc_function.html.markdown
Labels: documentation, size/S

#1472 improve(instance_types):update instance_types filter condition
  alicloud/resource_alicloud_key_pair_attachment_test.go
  alicloud/resource_alicloud_slb_rule_test.go
Labels: size/S

#1471 improve(pvtz_zone__domain): Added ids filter to datasource.
  alicloud/data_source_alicloud_pvtz_zone_records.go
  alicloud/data_source_alicloud_pvtz_zone_records_test.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  website/docs/d/pvtz_zone_records.html.markdown
  website/docs/r/pvtz_zone_record.html.markdown
Labels: documentation, size/L

#1470 improve(cr_repos): Added names to datasource attributes.
  alicloud/data_source_alicloud_cr_repos.go
  alicloud/data_source_alicloud_cr_repos_test.go
  website/docs/d/cr_repos.html.markdown
Labels: documentation, size/L

#1469 improve(cr_namespaces): Added names to datasource attributes.
  alicloud/data_source_alicloud_cr_namespaces.go
  alicloud/data_source_alicloud_cr_namespaces_test.go
  website/docs/d/cr_namespaces.html.markdown
Labels: documentation, size/L

#1466 improve(cdn): Added region to domain name and modified sweep rules.
  alicloud/resource_alicloud_cdn_domain_config_test.go
  alicloud/resource_alicloud_cdn_domain_new_test.go
Labels: size/M

#1461 improve(ram_roles): Added ids filter to datasource.
  alicloud/data_source_alicloud_ram_roles.go
  alicloud/data_source_alicloud_ram_roles_test.go
  alicloud/resource_alicloud_ram_role.go
  website/docs/d/ram_roles.html.markdown
  website/docs/r/ram_role.html.markdown
Labels: documentation, size/S

#1459 improve(ram_users): Added ids filter to datasource.
  alicloud/data_source_alicloud_ram_users.go
  alicloud/data_source_alicloud_ram_users_test.go
  website/docs/d/ram_users.html.markdown
Labels: documentation, size/XS

#1458 improve(pvtz_zones): Added ids filter and added names to datasource attributes.
  alicloud/data_source_alicloud_pvtz_zones.go
  alicloud/data_source_alicloud_pvtz_zones_test.go
  website/docs/d/pvtz_zones.html.markdown
Labels: documentation, size/L

#1477 improve(customer_gateway):create add retry
  alicloud/common.go
  alicloud/resource_alicloud_vpn_customer_gateway.go
Labels: size/S

#1493 improve(instance_type):update testcase config
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/data_source_alicloud_slb_attachments_test.go
  alicloud/data_source_alicloud_slb_rules_test.go
  alicloud/data_source_alicloud_slb_server_groups_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
  alicloud/resource_alicloud_slb_server_group_test.go
  alicloud/resource_alicloud_snapshot_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/M

#1491 improve(disk):suppurt delete_auto_snapshot delete_with_instance enabl…
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_test.go
  website/docs/r/disk.html.markdown
Labels: documentation, size/XS

#1476 improve(gpdb): resources supports timeouts setting.
  alicloud/data_source_alicloud_gpdb_instances_test.go
  alicloud/errors.go
  alicloud/resource_alicloud_gpdb_connection.go
  alicloud/resource_alicloud_gpdb_instance.go
  alicloud/service_alicloud_gpdb.go
  website/docs/r/gpdb_connection.html.markdown
  website/docs/r/gpdb_instance.html.markdown
Labels: documentation, size/M

#1495 improve(network_interface): enhance sweeper test
  alicloud/data_source_alicloud_api_gateway_apis.go
  alicloud/data_source_alicloud_cas_certificates_test.go
  alicloud/resource_alicloud_cdn_domain_config_test.go
  alicloud/resource_alicloud_network_interface_test.go
Labels: size/XS

#1501 improve(disk):update disk_attachment
  alicloud/data_source_alicloud_instances_test.go
  alicloud/data_source_alicloud_slb_attachments_test.go
  alicloud/data_source_alicloud_slb_rules_test.go
  alicloud/data_source_alicloud_slb_server_groups_test.go
  alicloud/data_source_alicloud_snapshots_test.go
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/resource_alicloud_disk_attachment_test.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_rule_test.go
  alicloud/resource_alicloud_slb_server_group_test.go
  alicloud/resource_alicloud_snapshot_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XL

#1453 improve(nas_mount_targets): Added ids filter to datasource.
  alicloud/data_source_alicloud_nas_mount_targets.go
  alicloud/data_source_alicloud_nas_mount_targets_test.go
  website/docs/d/nas_mount_targets.html.markdown
Labels: documentation, size/S

#1483 add(ons): ons-topic resource & data source
  alicloud/data_source_alicloud_ons_topics.go
  alicloud/data_source_alicloud_ons_topics_test.go
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ons_topic.go
  alicloud/resource_alicloud_ons_topic_test.go
  alicloud/service_alicloud_ons.go
  alicloud/validators.go
  examples/ons-topic/README.md
  examples/ons-topic/main.tf
  examples/ons-topic/outputs.tf
  examples/ons-topic/variables.tf
  website/alicloud.erb
  website/docs/d/ons_topics.html.markdown
  website/docs/r/ons_instance.html.markdown
  website/docs/r/ons_topic.html.markdown
Labels: documentation, size/XL

#1499 update CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#1507 improve(slb):update testcase
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/resource_alicloud_slb_server_group_test.go
Labels: size/XS

#1505 Fix(logstore_index): Invalid update parameter change
  alicloud/resource_alicloud_log_store_index.go
Labels: size/XS

#1510 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1494 Improve(log_store): Improve resources use common method.
  alicloud/resource_alicloud_log_store.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/resource_alicloud_log_store_index_test.go
  alicloud/resource_alicloud_log_store_test.go
  alicloud/service_alicloud_log.go
Labels: size/XL

#1513 improve(fc_function):fc_fucntion support sweeper
  alicloud/resource_alicloud_fc_function_test.go
Labels: size/M

#1512 improve(fc_trigger):fc_trigger support sweeper
  alicloud/resource_alicloud_fc_function_test.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_trigger_test.go
Labels: size/M

#1487 Improve(api_gateway): api_gateway_api added testcases.
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_api_gateway_vpc_access.go
  alicloud/resource_alicloud_api_gateway_vpc_access_test.go
Labels: size/L

#1492 Improve(mns_topic_subscription): Improve its resource use common method.
  alicloud/resource_alicloud_mns_topic_subscription.go
  alicloud/resource_alicloud_mns_topic_subscription_test.go
  alicloud/resource_alicloud_mns_topic_test.go
  alicloud/service_alicloud_mns.go
Labels: size/XL

#1497 Improve(log_machine_group): Improve resources use common method.
  alicloud/resource_alicloud_log_machine_group.go
  alicloud/resource_alicloud_log_machine_group_test.go
  alicloud/service_alicloud_log.go
Labels: size/XL

#1508 Improve(logtail_attachment): Improve resource use common method.
  alicloud/resource_alicloud_logtail_attachment.go
  alicloud/resource_alicloud_logtail_attachment_test.go
  alicloud/service_alicloud_log.go
Labels: size/XL

#1446 improve(mongodb_instance): supports timeouts setting.
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/S
