Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-08, with the labels that each got.

#1517 remove useless import
  alicloud/data_source_alicloud_fc_functions.go
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/resource_alicloud_fc_function_test.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/resource_alicloud_logtail_attachment.go
  alicloud/resource_alicloud_mns_topic_subscription.go
  alicloud/service_alicloud_gpdb.go
  alicloud/service_alicloud_log.go
  alicloud/service_alicloud_mns.go
  alicloud/service_alicloud_mongodb.go
  ci/pipeline.yml
Labels: size/S

#1496 Improve(log_project): Improve resource use common method.
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/service_alicloud_log.go
Labels: size/L

#1516 remove empty fields in managed k8s, add force_update, add multiple az support
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  go.mod
  go.sum
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/github.com/denverdino/aliyungo/ecs/disks.go
  vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
  vendor/github.com/denverdino/aliyungo/ecs/vpcs.go
  vendor/github.com/denverdino/aliyungo/util/encoding.go
  vendor/modules.txt
  website/docs/d/cs_managed_kubernetes_clusters.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: dependencies, documentation, size/XL

#1503 Feature/alicloud ess scalinggroup vserver groups attachment
  CHANGELOG.md
  alicloud/provider.go
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_scalinggroup_vserver_groups.markdown
Labels: documentation, size/XL

#1506 add(ons): ons-group resource & data source
  alicloud/data_source_alicloud_ons_groups.go
  alicloud/data_source_alicloud_ons_groups_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_ons_group.go
  alicloud/resource_alicloud_ons_group_test.go
  alicloud/service_alicloud_ons.go
  alicloud/validators.go
  examples/ons-group/README.md
  examples/ons-group/main.tf
  examples/ons-group/outputs.tf
  examples/ons-group/variables.tf
  website/alicloud.erb
  website/docs/d/ons_groups.html.markdown
  website/docs/r/ons_group.html.markdown
Labels: documentation, size/XL

#1518 improve(dns_record): add diffsuppressfunc to avoid DomainRecordDuplicate error.
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_dns_record.go
  website/docs/r/dns_record.html.markdown
Labels: documentation, size/XS

#1520 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1521 fix(mongodb_instance): fix notfound error when describing it
  CHANGELOG.md
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
  alicloud/service_alicloud_mongodb.go
Labels: size/XS

#1522 remove useless trigger in vpn ci
  CHANGELOG.md
  ci/pipeline.yml
Labels: size/XS

#1515 Improve(cr_repo): Improve resource use common method.
  alicloud/import_alicloud_cr_repo_test.go
  alicloud/resource_alicloud_cr_repo.go
  alicloud/resource_alicloud_cr_repo_test.go
  alicloud/service_alicloud_cr.go
Labels: size/XL

#1445 improve(kvstore): kvstore_instance resource supports timeouts setting.
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/service_alicloud_kvstore.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/M

#1526 fix(sweep): modified the region of prefixes.
  alicloud/resource_alicloud_api_gateway_vpc_access_test.go
  alicloud/resource_alicloud_cdn_domain_new_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_ram_account_alias_test.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_test.go
Labels: size/S

#1532 Fix(alicloud_logstore_index) Repair parameter description document
  website/docs/r/log_store_index.html.markdown
Labels: documentation, size/XS

#1525 Improve(pvtz_zone): Improve its and attachment resources use common method.
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  alicloud/resource_alicloud_pvtz_zone_test.go
  alicloud/service_alicloud_pvtz.go
  website/docs/r/pvtz_zone.html.markdown
Labels: documentation, size/XL

#1528 Improve(pvtz_zone_record): Improve resource use common method.
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
  alicloud/service_alicloud_pvtz.go
Labels: size/XL

#1509 Improve(cr_namespace): Improve resource use common method.
  alicloud/data_source_alicloud_cr_namespaces.go
  alicloud/import_alicloud_cr_namespace_test.go
  alicloud/resource_alicloud_cr_namespace.go
  alicloud/resource_alicloud_cr_namespace_test.go
  alicloud/resource_alicloud_cr_repo.go
  alicloud/resource_alicloud_cr_repo_test.go
  alicloud/service_alicloud_cr.go
Labels: size/XL

#1519 feat(instance): new datasource alicloud_instance_type_families.
  alicloud/data_source_alicloud_instance_type_families.go
  alicloud/data_source_alicloud_instance_type_families_test.go
  alicloud/provider.go
  alicloud/service_alicloud_ecs.go
  website/docs/d/instance_type_families.html.markdown
Labels: documentation, size/XL

#1527 Support multi_az_policy of 'COST_OPTIMIZED'
  CHANGELOG.md
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  website/docs/r/ess_scaling_group.html.markdown
Labels: dependencies, documentation, size/XL

#1531 add(slb_master_slave_server_group): update slb sdk and add slb master slave server group resource & data source
  alicloud/data_source_alicloud_slb_master_slave_server_groups.go
  alicloud/data_source_alicloud_slb_master_slave_server_groups_test.go
  alicloud/errors.go
  alicloud/extension_slb.go
  alicloud/provider.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_master_slave_server_group.go
  alicloud/resource_alicloud_slb_master_slave_server_group_test.go
  alicloud/service_alicloud_slb.go
  examples/slb-master-slave-server-group/main.tf
  website/docs/d/slb_master_slave_server_groups.html.markdown
  website/docs/r/slb_master_slave_server_group.html.markdown
Labels: dependencies, documentation, size/XXL

#1537 improve(provider):profile,role_arn,session_name,session_expiration su…
  alicloud/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#1539 fix kvstore unexpected state 'Changing'
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/XS

#1538 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1545 Improve(router_interface): modified testcase multi count.
  alicloud/resource_alicloud_router_interface_test.go
Labels: size/XS

#1543 Improve(images): removed image alinux check in datasource.
  alicloud/data_source_alicloud_images_test.go
Labels: size/XS

#1550 Improve(ram): ram policy attachment resources supports import.
  alicloud/resource_alicloud_ram_group_policy_attachment.go
  alicloud/resource_alicloud_ram_group_policy_attachment_test.go
  alicloud/resource_alicloud_ram_role_policy_attachment.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/resource_alicloud_ram_user_policy_attachment.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
  website/docs/r/ram_group_policy_attachment.html.markdown
  website/docs/r/ram_role_policy_attachment.html.markdown
  website/docs/r/ram_user_policy_attachment.html.markdown
Labels: documentation, size/M

#1553 modify(cs): skip the testcases of cs_application and cs_swarm
  alicloud/resource_alicloud_cs_application_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
Labels: size/XS

#1551 Improve(ots_instance): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_ots_instances.go
  alicloud/data_source_alicloud_ots_instances_test.go
  alicloud/resource_alicloud_ots_instance.go
  alicloud/resource_alicloud_ots_instance_test.go
  alicloud/service_alicloud_ots.go
Labels: size/XXL

#1552 Improve(ots_instance_attachment): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_ots_instance_attachments.go
  alicloud/data_source_alicloud_ots_instance_attachments_test.go
  alicloud/resource_alicloud_ots_instance_attachment.go
  alicloud/resource_alicloud_ots_instance_attachment_test.go
  alicloud/service_alicloud_ots.go
Labels: size/XL

#1500 Improve(logtail_config): Improve resource use common method.
  alicloud/resource_alicloud_logtail_config.go
  alicloud/resource_alicloud_logtail_config_test.go
  alicloud/service_alicloud_log.go
  website/docs/r/logtail_config.html.markdown
Labels: documentation, size/XL

#1546 Improve(ots_table): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_ots_tables.go
  alicloud/data_source_alicloud_ots_tables_test.go
  alicloud/resource_alicloud_ots_instance_attachment.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/resource_alicloud_ots_table_test.go
  alicloud/service_alicloud_ots.go
  website/docs/r/ots_table.html.markdown
Labels: documentation, size/XXL

#1559 Fix log document
  website/docs/r/log_machine_group.html.markdown
Labels: documentation, size/XS

#1561 improve(CI): add default bucket and region for CI
  ci/pipeline.yml
  ci/tasks/run.yml
Labels: size/XS

#1562 fix(CI): fix pipeline grammar error
  ci/pipeline.yml
Labels: size/XL

#1563 improve(key_pair):update key_pair document
  website/docs/r/key_pair_attachment.html.markdown
Labels: documentation, size/XS

#1564 fix(CI): remove the useless code
  ci/tasks/run.sh
Labels: size/XS

#1549 Support new resource: alicloud_ess_notification
  CHANGELOG.md
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ess_notification.go
  alicloud/resource_alicloud_ess_notification_test.go
  alicloud/service_alicloud_ess.go
  website/alicloud.erb
  website/docs/r/ess_notification.html.markdown
Labels: documentation, size/XL

#1569 fix(sweep): modified the error return to run sweep completely.
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
Labels: size/XS

#1572 bugfix：throw notFoundError when scalingGroup is not found.
  alicloud/service_alicloud_ess.go
Labels: size/XS

#1567 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1555 Improve(datahub_project): Improve resource use common method.
  alicloud/import_alicloud_datahub_project_test.go
  alicloud/resource_alicloud_datahub_project.go
  alicloud/resource_alicloud_datahub_project_test.go
  alicloud/service_alicloud_datahub.go
Labels: size/XL

#1566 fix(disks):fix dataSource test case bug
  alicloud/data_source_alicloud_disks_test.go
Labels: size/XS

#1573 Rename resource name that is not start with a letter
  alicloud/data_source_alicloud_instance_types.go
  examples/build-lnmp/main.tf
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1574 Fix typo
  website/docs/r/key_pair_attachment.html.markdown
Labels: documentation, size/XS

#1576 fix(ci):fix CI statistics bug
  ci/tasks/run.sh
Labels: size/XS

#1556 Improve(datahub_subscription): Improve resource use common method.
  alicloud/import_alicloud_datahub_subscription_test.go
  alicloud/resource_alicloud_datahub_project.go
  alicloud/resource_alicloud_datahub_subscription.go
  alicloud/resource_alicloud_datahub_subscription_test.go
  alicloud/service_alicloud_datahub.go
Labels: size/XL

#1580 improve(Document):improve document demo about set
  website/docs/r/cdn_domain.html.markdown
  website/docs/r/network_acl_attachment.html.markdown
  website/docs/r/ots_table.html.markdown
Labels: documentation, size/S

#1577 improve(ci):supplement log
  alicloud/common.go
  alicloud/data_source_alicloud_instance_type_families.go
  alicloud/data_source_alicloud_ons_groups.go
  alicloud/data_source_alicloud_ons_instances.go
  alicloud/data_source_alicloud_ons_topics.go
  alicloud/data_source_alicloud_oss_bucket_objects.go
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_slb_backend_servers.go
  alicloud/data_source_alicloud_slb_master_slave_server_groups.go
  alicloud/resource_alicloud_cr_namespace.go
  alicloud/resource_alicloud_cr_repo.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
  alicloud/resource_alicloud_log_machine_group.go
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_log_store.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/resource_alicloud_logtail_attachment.go
  alicloud/resource_alicloud_logtail_config.go
  alicloud/resource_alicloud_network_acl_entries_test.go
  alicloud/resource_alicloud_network_acl_test.go
  alicloud/resource_alicloud_ons_group.go
  alicloud/resource_alicloud_ons_topic.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_object.go
  alicloud/resource_alicloud_ots_instance.go
  alicloud/resource_alicloud_ots_instance_attachment.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_slb_backend_server.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_master_slave_server_group.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vpn_customer_gateway_test.go
  alicloud/service_alicloud_cr.go
  alicloud/service_alicloud_ecs.go
  alicloud/service_alicloud_log.go
  alicloud/service_alicloud_ons.go
  alicloud/service_alicloud_oss.go
  alicloud/service_alicloud_ots.go
  alicloud/service_alicloud_slb.go
Labels: size/XL

#1585 improve(tags): modified test case to check the upper case letters in tags.
  alicloud/common.go
  alicloud/resource_alicloud_disk_test.go
  alicloud/resource_alicloud_network_interface_test.go
  alicloud/resource_alicloud_oss_bucket_test.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/resource_alicloud_snapshot_test.go
Labels: size/S

#1588 improve(slb): sweep the protected slb
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/S

#1590 fix(instance):update instance testcase
  alicloud/resource_alicloud_instance_test.go
Labels: size/M

#1586 Improve(ram): ram resources supports import.
  alicloud/resource_alicloud_ram_access_key_test.go
  alicloud/resource_alicloud_ram_account_alias.go
  alicloud/resource_alicloud_ram_account_alias_test.go
  alicloud/resource_alicloud_ram_account_password_policy_test.go
  alicloud/resource_alicloud_ram_group_membership.go
  alicloud/resource_alicloud_ram_group_membership_test.go
  website/docs/r/ram_account_alias.html.markdown
  website/docs/r/ram_group_membership.html.markdown
  website/docs/r/ram_user_policy_attachment.html.markdown
Labels: documentation, size/M

#1593 fix(vsw): fix bug from github issue.
  alicloud/data_source_alicloud_vswitches.go
Labels: size/XS

#1596 update CHANGELOG.md
  CHANGELOG.md
  website/docs/r/route_entry.html.markdown
Labels: documentation, size/XS

#1597 improve(ons_instance): set instance name using random
  CHANGELOG.md
  alicloud/resource_alicloud_ons_group_test.go
  alicloud/resource_alicloud_ons_instance_test.go
  alicloud/resource_alicloud_ons_topic_test.go
Labels: size/XS

#1581 Improve(cs_managed_kubernetes): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  alicloud/service_alicloud_cs.go
Labels: size/XXL

#1598 improve(ons_topic):retry when Throttling.User
  alicloud/errors.go
  alicloud/resource_alicloud_ons_topic.go
Labels: size/S

#1584 Improve(cs_kubernetes): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_cs_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_ons_topic.go
  alicloud/service_alicloud_cs.go
Labels: size/XXL

#1591 Improve(ddoscoo): Improve its resource and datasource use common method.
  alicloud/data_source_alicloud_ddoscoo_instances.go
  alicloud/data_source_alicloud_ddoscoo_instances_test.go
  alicloud/resource_alicloud_ddoscoo_instance.go
  alicloud/resource_alicloud_ddoscoo_instance_test.go
  alicloud/service_alicloud_ddoscoo.go
  website/docs/r/ddoscoo_instance.html.markdown
  website/docs/r/ram_group_membership.html.markdown
Labels: documentation, size/XL

#1600 improve(CI): change sweeper time
  ci/pipeline.yml
Labels: size/S

#1599 improve(rds): fix db_instance apply error after import
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#1604 fix(ons): fix the create group error in testcase
  alicloud/data_source_alicloud_ons_groups_test.go
  alicloud/resource_alicloud_ons_group_test.go
Labels: size/XS

#1608 fix(ons):fix ons error Throttling.User
  alicloud/resource_alicloud_ons_group.go
  alicloud/resource_alicloud_ons_group_test.go
  alicloud/resource_alicloud_ons_instance.go
  alicloud/resource_alicloud_ons_instance_test.go
  alicloud/resource_alicloud_ons_topic_test.go
Labels: size/M

#1607 improve(db_readonly_instance):improve db_readonly_instance testcase
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#1605 improve(drds): modified drds supported regions
  alicloud/connectivity/regions.go
Labels: size/XS

#1587 Improve(slb):slb support set AddressIpVersion
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_common_test.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/XL

#1617 imporve(elasticsearch): modified availability zone of elasticsearch instance.
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1616 improve(ram & actiontrail): added precheck for resources testcases.
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/data_source_alicloud_ram_account_alias_test.go
  alicloud/resource_alicloud_actiontrail_test.go
  alicloud/resource_alicloud_ram_account_alias_test.go
  alicloud/resource_alicloud_ram_account_password_policy_test.go
  ci/tasks/run.sh
Labels: size/S

#1610 fix(disk):fix disk detach bug
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#1606 imporve(cdn) modified wait time of cdn domain creation.
  alicloud/resource_alicloud_cdn_domain_new.go
Labels: size/XS

#1609 improve(cdn): cdn domain supported tags.
  alicloud/common.go
  alicloud/resource_alicloud_cdn_domain_new.go
  alicloud/resource_alicloud_cdn_domain_new_test.go
  alicloud/resource_alicloud_ons_group.go
  alicloud/service_alicloud_cdn.go
  alicloud/tags.go
  website/docs/r/cdn_domain_new.html.markdown
Labels: documentation, size/L

#1620 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS
