Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-11, with the labels that each got.

#1805 add a new datasource alicloud_emr_disk_types
  alicloud/data_source_alicloud_emr_disk_types.go
  alicloud/data_source_alicloud_emr_disk_types_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/alicloud.erb
  website/docs/d/emr_disk_types.html.markdown
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/XL

#1810 Add password to resource_alicloud_ess_scalingconfiguration
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/S

#1790 add sag_qos and sag_qos_policy and sag_qos_car
  alicloud/provider.go
  alicloud/resource_alicloud_sag_qos.go
  alicloud/resource_alicloud_sag_qos_car.go
  alicloud/resource_alicloud_sag_qos_car_test.go
  alicloud/resource_alicloud_sag_qos_policy.go
  alicloud/resource_alicloud_sag_qos_policy_test.go
  alicloud/resource_alicloud_sag_qos_test.go
  alicloud/service_alicloud_sag.go
  examples/sag_qos/main.tf
  examples/sag_qos/versions.tf
  examples/sag_qos_car/main.tf
  examples/sag_qos_car/versions.tf
  examples/sag_qos_policy/main.tf
  examples/sag_qos_policy/versions.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/create_qos_car.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/delete_qos_car.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/describe_qos_cars.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/modify_qos_car.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/struct_qos_car.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/struct_qos_cars.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/smartag/struct_snat_entry.go
  website/alicloud.erb
  website/docs/r/sag_qos.html.markdown
  website/docs/r/sag_qos_car.html.markdown
  website/docs/r/sag_qos_policy.html.markdown
Labels: dependencies, documentation, size/XXL

#1822 Add resource_group_id to 5 data_datasources
  alicloud/data_source_alicloud_slb_acls.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/data_source_alicloud_slb_ca_certificates.go
  alicloud/data_source_alicloud_slb_ca_certificates_test.go
  alicloud/data_source_alicloud_slbs.go
  alicloud/data_source_alicloud_slbs_test.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/data_source_alicloud_vswitches_test.go
  website/docs/d/slb_acls.html.markdown
  website/docs/d/slb_ca_certificates.html.markdown
  website/docs/d/slbs.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vswitches.html.markdown
Labels: documentation, size/L

#1815 imporve(instance): modified the argument reference in doc.
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#1820 update CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#1824 alicloud_ess_scheduled_task supports Cron type
  CHANGELOG.md
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scheduled_task.go
  website/alicloud.erb
  website/docs/index.html.markdown
  website/docs/r/ess_scheduled_task.html.markdown
Labels: documentation, size/S

#1799 add sag_snat
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_sag_snat_entry.go
  alicloud/resource_alicloud_sag_snat_entry_test.go
  alicloud/service_alicloud_sag.go
  examples/sag_snat_entry/main.tf
  examples/sag_snat_entry/versions.tf
  website/alicloud.erb
  website/docs/r/sag_snat_entry.html.markdown
Labels: dependencies, documentation, size/XL

#1827 improve(alikafka): Added name for vpcs and vswitches.
  alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
  alicloud/data_source_alicloud_alikafka_instances_test.go
  alicloud/data_source_alicloud_alikafka_topics_test.go
  alicloud/resource_alicloud_alikafka_consumer_group_test.go
  alicloud/resource_alicloud_alikafka_instance_test.go
  alicloud/resource_alicloud_alikafka_topic_test.go
Labels: size/S

#1821 support to create emr gateway cluster instance
  alicloud/extension_emr.go
  alicloud/resource_alicloud_emr_cluster.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/XL

#1835 fix(ess): use GetOkExists to avoid some potential bugs
  alicloud/resource_alicloud_ess_scalingrule.go
Labels: size/XS

#1840 fix waitfor method nil bug
  alicloud/resource_alicloud_cas_certificate_test.go
  alicloud/resource_alicloud_log_machine_group_test.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_log_store_test.go
  alicloud/service_alicloud_alikafka.go
  alicloud/service_alicloud_api_gateway.go
  alicloud/service_alicloud_cas.go
  alicloud/service_alicloud_cdn.go
  alicloud/service_alicloud_cen.go
  alicloud/service_alicloud_cr.go
  alicloud/service_alicloud_cs.go
  alicloud/service_alicloud_datahub.go
  alicloud/service_alicloud_dns.go
  alicloud/service_alicloud_drds.go
  alicloud/service_alicloud_ecs.go
  alicloud/service_alicloud_elasticsearch.go
  alicloud/service_alicloud_emr.go
  alicloud/service_alicloud_fc.go
  alicloud/service_alicloud_gpdb.go
  alicloud/service_alicloud_kms.go
  alicloud/service_alicloud_kvstore.go
  alicloud/service_alicloud_log.go
  alicloud/service_alicloud_mns.go
  alicloud/service_alicloud_mongodb.go
  alicloud/service_alicloud_ons.go
  alicloud/service_alicloud_ots.go
  alicloud/service_alicloud_ram.go
  alicloud/service_alicloud_rds.go
  alicloud/service_alicloud_slb.go
  alicloud/service_alicloud_vpc.go
Labels: size/XL

#1830 change sideBar
  website/alicloud.erb
Labels: documentation, size/XXL

#1838 improve(resource_alicloud_db_database): support Mohawk_100_BIN
  alicloud/extension_rds.go
  website/docs/r/db_database.html.markdown
Labels: documentation, size/XS

#1836 perf(alicloud_db_backup_policy,db_instances):perf rds document desc
  website/docs/d/db_instances.html.markdown
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/XS

#1841 fix(nat_gateway):fix nat_gateway period bug
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_nat_gateway_test.go
Labels: size/S

#1844 improve(rds): fix for hidden dts ip list
  alicloud/service_alicloud_rds.go
Labels: size/XS

#1845 improve(instance): postpaid instance supported 'dry_run'.
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_log_machine_group_test.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_log_store_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#1839 filter the local disk to fix the bug of InvalidDataDiskType
  alicloud/data_source_alicloud_emr_instance_types.go
  alicloud/data_source_alicloud_emr_instance_types_test.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/docs/d/emr_instance_types.html.markdown
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/L

#1850 imporve(ess): add module guide for the ess resources
  ci/pipeline.yml
  website/docs/r/ess_alarm.html.markdown
  website/docs/r/ess_scaling_configuration.html.markdown
  website/docs/r/ess_scaling_group.html.markdown
  website/docs/r/ess_scaling_lifecycle_hook.html.markdown
  website/docs/r/ess_scaling_rule.html.markdown
  website/docs/r/ess_scheduled_task.html.markdown
Labels: documentation, size/S

#1851 fix terraform docs
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_serverless_kubernetes.go
  alicloud/resource_alicloud_cs_serverless_kubernetes_test.go
  examples/serverless-kubernetes/main.tf
  examples/serverless-kubernetes/outputs.tf
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/cs_serverless_kubernetes.html.markdown
Labels: documentation, size/M

#1849 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1852 improve(provider): add default value for configuration_source
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/provider.go
  website/docs/r/ess_scaling_rule.html.markdown
Labels: documentation, size/L

#1819 feat(alicloud/yundun_dbaudit): add support for Yundun_dbaudit
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_yundun_dbaudit_instances.go
  alicloud/data_source_alicloud_yundun_dbaudit_instances_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_yundun_dbaudit_instance.go
  alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
  alicloud/service_alicloud_yundun_dbaudit.go
  examples/dbaudit/main.tf
  examples/dbaudit/output.tf
  examples/dbaudit/variables.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/clear_instance_storage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/config_instance_white_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/delete_alarm_receive_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_audit_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_event_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_instance_attribue.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_instance_storage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/describe_session_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/disable_instance_public_access.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/enable_instance_public_access.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/list_tag_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/list_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/modify_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/modify_instance_storage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/move_resource_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/refund_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/start_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_audit_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_event_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instance_attribue.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instance_storage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instance_storages.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_item.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_item_in_describe_event_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_region.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_session_logs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_tag_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_tag_keys.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_tag_resource.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_white_list_in_describe_instance_attribue.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/struct_white_list_in_describe_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_dbaudit/untag_resources.go
  website/alicloud.erb
  website/docs/d/yundun_dbaudit_instances.html.markdown
  website/docs/r/yundun_dbaudit_instance.html.markdown
Labels: dependencies, size/XXL

#1853 improve docs and add ci for yundun dbaudit
  alicloud/connectivity/client.go
  ci/pipeline.yml
  website/alicloud.erb
  website/docs/d/yundun_dbaudit_instances.html.markdown
  website/docs/r/ddosbgp_instance.html.markdown
  website/docs/r/yundun_dbaudit_instance.html.markdown
Labels: documentation, size/XL

#1857 improve(ess_scalingconfiguration): support password_inherit
  CHANGELOG.md
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/XS

#1863 improve(kvstore): remove memcache filter from datasource test
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
  alicloud/data_source_alicloud_kvstore_instance_engines_test.go
  website/docs/r/cdn_domain_new.html.markdown
Labels: documentation, size/S

#1864 improve(kvstore_instance_engines): improve its code
  alicloud/data_source_alicloud_kvstore_instance_engines.go
Labels: size/XS

#1862 fix(key_pair):fix key_pair testcase bug
  alicloud/data_source_alicloud_key_pairs_test.go
Labels: size/XS

#1865 fix(mongodb_instances): fix name_regex bug
  alicloud/data_source_alicloud_mongodb_instances.go
Labels: size/XS

#1874 fix(mongodb_instances): fix filetering bug
  alicloud/data_source_alicloud_mongodb_instances.go
Labels: size/XS

#1855 improve(provider): added endpoint for resources.
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
Labels: size/S

#1875 improve(kvstore_instance_classess): improve test case error caused by no stock
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
Labels: size/XS

#1876 improve(zones): use describeAvailableResource API to get rds available zones
  alicloud/data_source_alicloud_zones.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/M

#1877 improve(scalingconfiguration): supports changing password_inherit
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/XS

#1871 improve(mns): mns support sts access
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_mns_queues.go
  alicloud/data_source_alicloud_mns_topic_subscriptions.go
  alicloud/data_source_alicloud_mns_topics.go
  alicloud/resource_alicloud_mns_queue.go
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/resource_alicloud_mns_topic.go
  alicloud/resource_alicloud_mns_topic_subscription.go
  alicloud/resource_alicloud_mns_topic_subscription_test.go
  alicloud/resource_alicloud_mns_topic_test.go
  alicloud/service_alicloud_mns.go
  go.mod
  go.sum
  vendor/github.com/aliyun/aliyun-mns-go-sdk/.gitignore
  vendor/github.com/aliyun/aliyun-mns-go-sdk/LICENSE
  vendor/github.com/aliyun/aliyun-mns-go-sdk/README.md
  vendor/github.com/aliyun/aliyun-mns-go-sdk/client.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/credential.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/decoder.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/errors.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/message.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/qps_monitor.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/queue.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/queue_manager.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/topic.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/topic_manager.go
  vendor/github.com/aliyun/aliyun-mns-go-sdk/utils.go
  vendor/modules.txt
Labels: dependencies, size/M

#1878 improve(db_instance): feature support high security access mode not submitted
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/S

#1880 improve(rds): feature support high security access mode not submi…
  alicloud/common.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/XS

#1860 improve(oss_bucket_object):make oss_bucket_object support KMS encryption
  alicloud/resource_alicloud_oss_bucket_object.go
  alicloud/resource_alicloud_oss_bucket_object_test.go
  alicloud/validators.go
  website/docs/r/oss_bucket_object.html.markdown
Labels: documentation, size/M

#1882 improve(cs): modify the value of 'new_nat_gateway' to avoid errors.
  alicloud/resource_alicloud_cs_kubernetes_test.go
Labels: size/XS

#1879 improve(oss): add transitions to life-cycle
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/L

#1886 fix(kvstore): remove the kvstore instance password limitation
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/validators.go
Labels: size/M

#1885 Do not assume `private_zone` is returned from API
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go
  alicloud/resource_alicloud_cs_serverless_kubernetes.go
Labels: size/XS

#1832 - fix(autoscaling): fix autoscaling bugs.
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_alarm.go
  alicloud/resource_alicloud_ess_attachment.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingrule.go
  alicloud/resource_alicloud_ess_scalingrule_test.go
  alicloud/resource_alicloud_ess_scheduled_task.go
  website/docs/d/ess_scaling_configurations.html.markdown
  website/docs/r/ess_alarm.html.markdown
  website/docs/r/ess_notification.html.markdown
  website/docs/r/ess_scaling_configuration.html.markdown
  website/docs/r/ess_scaling_group.html.markdown
  website/docs/r/ess_scaling_lifecycle_hook.html.markdown
  website/docs/r/ess_scaling_rule.html.markdown
Labels: documentation, size/M

#1889 improve(db, kvstore): add auto pay when changing instance charge type
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/XS

#1891 improve(kvstore_instance): correct its docs
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XS

#1893 imporve(docs): add AODC warning
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1872 update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
  website/docs/r/db_instance.html.markdown
  website/docs/r/oss_bucket.html.markdown
  website/docs/r/oss_bucket_object.html.markdown
  website/docs/r/pvtz_zone_attachment.html.markdown
Labels: documentation, size/S

#1896 fix(db_backup_policy): add limitation when modify sqlservr policy
  CHANGELOG.md
  alicloud/resource_alicloud_db_backup_policy.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/S

#1897 improve(db_instance): add new field auto_upgrade_minor_version to set minor version
  CHANGELOG.md
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#1898 fix(db_instance): test case
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#1892 fix(dns_record):fix dns_record testcase bug
  alicloud/service_alicloud_dns.go
Labels: size/XS

#1899 fix(db_instance): fix postgre testcase
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#1901 improve(kvstore_instance_classes): skip unsupported zones
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
Labels: size/S

#1902 fix the bug of TestAccAlicloudEmrCluster_local_storage failed
  alicloud/data_source_alicloud_emr_instance_types.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/docs/d/emr_instance_types.html.markdown
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/M

#1904 improve(mongodb): feature mongodb support postpaid to prepaid
  alicloud/resource_alicloud_mongodb_instance.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/XS

#1905 fix(ess): modify the type of from Set to List.
  alicloud/resource_alicloud_ess_scalinggroup.go
Labels: size/XS

#1907 Revert "improve(mongodb): feature mongodb support postpaid to prepaid"
  alicloud/resource_alicloud_mongodb_instance.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/XS

#1908 improve(mongodb): feature mongodb support postpaid to prepaid
  alicloud/resource_alicloud_mongodb_instance.go
  website/docs/r/mongodb_instance.html.markdown
Labels: dependencies, documentation, size/XS

#1910 fix(kafka): remove the const endpoint
  alicloud/connectivity/client.go
  website/alicloud.erb
  website/docs/r/ram_user.html.markdown
Labels: documentation, size/XS

#1903 fix managedkubernetes demo
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/M

#1911 fix(pvtz_attachment): fix vpc_ids diff error
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  website/docs/r/pvtz_zone_attachment.html.markdown
Labels: documentation, size/L

#1823 add sag_dnat
  alicloud/diff_suppress_funcs.go
  alicloud/provider.go
  alicloud/resource_alicloud_sag_dnat_entry.go
  alicloud/resource_alicloud_sag_dnat_entry_test.go
  examples/sag_dnat_entry/main.tf
  examples/sag_dnat_entry/versions.tf
  website/alicloud.erb
  website/docs/r/sag_dnat_entry.html.markdown
Labels: dependencies, documentation, size/XL

#1916 improve(db_database):update db_database doc
  website/docs/r/db_database.html.markdown
Labels: documentation, size/XS

#1918 improve(sag_dnat_entry): modify docs "add subcategory"
  website/docs/r/sag_dnat_entry.html.markdown
Labels: documentation, size/XS

#1920 improve(validator): Delete TagNum Count
  alicloud/data_source_alicloud_slbs.go
  alicloud/resource_alicloud_slb.go
Labels: size/XS

#1894 feat(alicloud/yundun_bastionhost): Add support for Cloud Bastionhost
  alicloud/connectivity/client.go
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_yundun_bastionhost_instances.go
  alicloud/data_source_alicloud_yundun_bastionhost_instances_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_bastionhost_instance_test.go
  alicloud/service_alicloud_yundun_bastionhost.go
  examples/bastionhost/main.tf
  examples/bastionhost/output.tf
  examples/bastionhost/variables.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/config_instance_network.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/config_instance_security_groups.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/config_instance_white_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_grant.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instance_bastionhost.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instance_login_ticket.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instance_operation_ticket.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_open_service.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_resume.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/describe_sync_info.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/disable_instance_public_access.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/enable_instance_public_access.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/modify_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/modify_plan.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/move_resource_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/refund_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/start_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_data.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instance_in_describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instance_info.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instances_in_describe_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instances_in_describe_instance_bastionhost.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_instances_in_describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_login_ticket.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_private_white_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_public_white_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_referred_security_groups.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_region.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_security_group_ids.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_sts_token.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_zone.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/struct_zones.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/tag_resources_system_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/untag_resources_system_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/yundun_bastionhost/upgrade_instance_version.go
  website/alicloud.erb
  website/docs/d/yundun_bastionhost_instances.html.markdown
  website/docs/r/yundun_bastionhost_instance.html.markdown
Labels: dependencies, size/XXL

#1921 improve(cloud_connect_network_grant): add cloud_connect_network_grant
  alicloud/provider.go
  alicloud/resource_alicloud_cloud_connect_network_grant.go
  alicloud/resource_alicloud_cloud_connect_network_grant_test.go
  examples/cloud_connect_network_grant/main.tf
  examples/cloud_connect_network_grant/versions.tf
  website/alicloud.erb
  website/docs/r/cloud_connect_network_grant.html.markdown
Labels: documentation, size/XL

#1926 improve(kms): improve kms testcases use new method.
  alicloud/data_source_alicloud_kms_ciphertext_test.go
  alicloud/data_source_alicloud_kms_plaintext_test.go
  alicloud/resource_alicloud_kms_ciphertext.go
Labels: size/L

#1925 update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#1927 improve(slb): add a new field skip_delete_protection_validation
  CHANGELOG.md
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_attachment.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_backend_server.go
  alicloud/resource_alicloud_slb_backend_server_test.go
  alicloud/resource_alicloud_slb_domain_extension.go
  alicloud/resource_alicloud_slb_domain_extension_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_master_slave_server_group.go
  alicloud/resource_alicloud_slb_master_slave_server_group_test.go
  alicloud/resource_alicloud_slb_rule.go
  alicloud/resource_alicloud_slb_rule_test.go
  alicloud/resource_alicloud_slb_server_group.go
  alicloud/resource_alicloud_slb_server_group_test.go
  ci/pipeline.yml
  examples/slb-backend-server/main.tf
  examples/slb-domain-extension/main.tf
  examples/slb-master-slave-server-group/main.tf
  examples/slb/main.tf
  examples/slb/variables.tf
  website/docs/r/slb.html.markdown
  website/docs/r/slb_attachment.html.markdown
  website/docs/r/slb_backend_server.html.markdown
  website/docs/r/slb_domain_extension.html.markdown
  website/docs/r/slb_listener.html.markdown
  website/docs/r/slb_master_slave_server_group.html.markdown
  website/docs/r/slb_rule.html.markdown
  website/docs/r/slb_server_group.html.markdown
Labels: documentation, size/XL

#1929 adding replica_set_name to output from alicloud_mongodb_instance
  alicloud/resource_alicloud_mongodb_instance.go
Labels: size/XS

#1930 improve(db_instance): tags supports case sensitive
  CHANGELOG.md
  alicloud/extension_rds.go
  alicloud/resource_alicloud_db_database.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_slb_server_group_test.go
  alicloud/service_alicloud_rds.go
  alicloud/tags.go
  website/docs/r/db_account.html.markdown
  website/docs/r/db_database.html.markdown
  website/docs/r/db_instance.html.markdown
  website/docs/r/fc_function.html.markdown
  website/docs/r/fc_service.html.markdown
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/XL
