Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-09, with the labels that each got.

#1625 improve(example): update the examples to the format of the new version.
  examples/api-gateway-api/main.tf
  examples/api-gateway-fc/main.tf
  examples/build-lnmp/main.tf
  examples/cdn/main.tf
  examples/dns/main.tf
  examples/drds/outputs.tf
  examples/ecs-image/main.tf
  examples/ecs-module/main.tf
  examples/ecs-nat/main.tf
  examples/ecs-nat/variables.tf
  examples/ecs-new-vpc/main.tf
  examples/ecs-ram-role/main.tf
  examples/ecs-slb/main.tf
  examples/ecs/main.tf
  examples/elasticsearch/main.tf
  examples/elasticsearch/variables.tf
  examples/ess-scaling/main.tf
  examples/key-pair/main.tf
  examples/kubernetes/main.tf
  examples/kvstore/main.tf
  examples/nas-access-rule/outputs.tf
  examples/nas-mount-target/outputs.tf
  examples/network-interface/outputs.tf
  examples/ons-topic/variables.tf
  examples/oss-bucket-cors/main.tf
  examples/oss-bucket/main.tf
  examples/ots-table/main.tf
  examples/ram/main.tf
  examples/rds/main.tf
  examples/router-interface/main.tf
  examples/slb-rule/main.tf
  examples/slb-server-group/main.tf
  examples/slb-vpc/main.tf
  examples/vpc-snat/main.tf
  examples/vpn/main.tf
Labels: size/XL

#1626 fix(common_bandwidth_package):make ratio ForceNew
  alicloud/resource_alicloud_common_bandwidth_package.go
  website/docs/r/common_bandwidth_package.html.markdown
Labels: documentation, size/XS

#1622 improve(api gateway): api gateway app supported tags.
  alicloud/common.go
  alicloud/data_source_alicloud_api_gateway_apps.go
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  alicloud/resource_alicloud_api_gateway_app.go
  alicloud/resource_alicloud_api_gateway_app_test.go
  alicloud/service_alicloud_api_gateway.go
  website/docs/d/api_gateway_apps.html.markdown
  website/docs/r/api_gateway_app.html.markdown
Labels: documentation, size/L

#1619 improve(kvstore): kvstore instance supported tags.
  alicloud/data_source_alicloud_kvstore_instances.go
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_kvstore.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/L

#1621 improve(vpc): vpc resources and datasources supported tags.
  alicloud/common.go
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_eips_test.go
  alicloud/data_source_alicloud_route_tables.go
  alicloud/data_source_alicloud_route_tables_test.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/data_source_alicloud_vswitches_test.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_route_table_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vswitch.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/eips.html.markdown
  website/docs/d/route_tables.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vswitches.html.markdown
  website/docs/r/eip.html.markdown
  website/docs/r/route_table.html.markdown
  website/docs/r/vpc.html.markdown
  website/docs/r/vswitch.html.markdown
Labels: documentation, size/XL

#1629 improve(slb): add new field resource_group_id
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/XS

#1631 improve(slb): midified the sweep rules of slb.
  alicloud/resource_alicloud_slb_test.go
Labels: size/XS

#1554 update example to support for snat's creation with multi eips
  website/docs/r/snat.html.markdown
Labels: documentation, size/XS

#1594 fix:resource security_group 'inner_access_policy' replaces 'inner_access',resource slb 'address_type' replaces 'internet'
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  website/docs/r/security_group.html.markdown
  website/docs/r/slb.html.markdown
Labels: documentation, size/L

#1634 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1630 improve(instance):remove bandwidth limit
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#1602 fix(rds): add diffsuppressfunc to rds tags.
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#1615 improve(gpdb): gpdb instance supported tags.
  alicloud/data_source_alicloud_gpdb_instances.go
  alicloud/data_source_alicloud_gpdb_instances_test.go
  alicloud/resource_alicloud_gpdb_instance.go
  alicloud/resource_alicloud_gpdb_instance_test.go
  alicloud/service_alicloud_gpdb.go
  alicloud/tags.go
  website/docs/d/gpdb_instances.html.markdown
  website/docs/r/gpdb_instance.html.markdown
Labels: documentation, size/L

#1648 improve(images): modified the testcase of images datasource.
  alicloud/data_source_alicloud_images_test.go
Labels: size/XS

#1651 improve(provider): add the provider verison in the useragent
  alicloud/connectivity/client.go
Labels: size/XS

#1645 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1652 improve(vpc): Added retry to avoid ListTagResources Throttling error.
  alicloud/service_alicloud_vpc.go
Labels: size/XS

#1653 improve(docs): Added sensitive tag for the doc which has password.
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/cs_swarm.html.markdown
  website/docs/r/db_account.html.markdown
  website/docs/r/elasticsearch.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/kvstore_instance.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
  website/docs/r/ram_login_profile.html.markdown
Labels: documentation, size/XS

#1654 improve(table store): set primary key to forcenew
  CHANGELOG.md
  alicloud/resource_alicloud_ots_table.go
  website/docs/r/ots_table.html.markdown
Labels: documentation, size/XS

#1656 update changelog
  CHANGELOG.md
Labels: size/XS

#1657 improve(provider): add a new field source_name to mark template
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/provider.go
  examples/vpc/main.tf
  website/docs/index.html.markdown
Labels: documentation, size/M

#1660 improve(cen): Added wait time to avoid CreateCen Operation.Blocking error.
  alicloud/resource_alicloud_cen_instance.go
Labels: size/XS

#1661 improve(provider): rename source_name to configuration_source
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/provider.go
  examples/vpc/main.tf
  website/docs/index.html.markdown
Labels: documentation, size/M

#1662 improve(ci): add ci test for alikafka
  ci/configure
  ci/pipeline.yml
  ci/tasks/run.sh
Labels: size/XS

#1664 add missing field ALICLOUD_INSTANCE_ID
  ci/tasks/run.sh
  ci/tasks/run.yml
Labels: size/XS

#1666 fix(testCommon):fix test common bug
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1669 improve(elasticsearch): Added retry to avoid UpdateInstance ConcurrencyUpdateInstanceConflict error.
  alicloud/errors.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/XS

#1668 fix(security_group_rule):fix description bug
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_security_group_rule_test.go
Labels: size/M

#1672 changeLog
  CHANGELOG.md
Labels: size/XS

#1673 ddoscoo instance only support upgrade currently
  alicloud/resource_alicloud_ddoscoo_instance_test.go
  website/docs/r/ddoscoo_instance.html.markdown
Labels: documentation, size/S

#1650 support alicloud_ddosbgp_instances and alicloud_ddosbgp_instance
  alicloud/common.go
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_ddosbgp_instances.go
  alicloud/data_source_alicloud_ddosbgp_instances_test.go
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ddosbgp_instance.go
  alicloud/resource_alicloud_ddosbgp_instance_test.go
  alicloud/service_alicloud_ddosbgp.go
  alicloud/service_alicloud_ddoscoo.go
  alicloud/validators.go
  examples/ddosbgp/main.tf
  examples/ddosbgp/output.tf
  examples/ddosbgp/variables.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/add_ip.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/check_grant.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/delete_blackhole.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/delete_ip.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_ddos_event.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_excpetion_count.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_instance_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_instance_specs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_op_entities.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_pack_ip_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_pack_paid_traffic.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_resource_pack_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_resource_pack_statistics.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_resource_pack_usage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/describe_traffic.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/modify_remark.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/release_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_event.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_events.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_flow.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_flow_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_instance_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_instance_spec.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_instance_specs.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_ip_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_ipitem.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_op_entities.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_op_entity.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_pack_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_pack_paid_traffic.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_pack_paid_traffics.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_pack_usage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_pack_usages.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_region.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_resource_pack.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ddosbgp/struct_resource_packs.go
  website/docs/d/ddosbgp_instances.html.markdown
  website/docs/r/ddosbgp_instance.html.markdown
Labels: dependencies, size/XXL

#1678 improve(elasticsearch): added wait setting for retry.
  alicloud/service_alicloud_elasticsearch.go
Labels: size/S

#1675 improve(provider): support provider test
  alicloud/provider_test.go
  ci/pipeline.yml
  ci/tasks/run.sh
  ci/tasks/run.yml
Labels: size/L

#1685 fix(ram user): supported backward compatible.
  alicloud/service_alicloud_ram.go
Labels: size/XS

#1687 improve(ci): add ddosbgp job
  ci/pipeline.yml
Labels: size/XS

#1684 improve: rds,redis,mongodb remove the enumeration
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XS

#1689 improve(sls): improve sls notfounderror
  alicloud/errors.go
Labels: size/XS

#1683 Update the default period of the ddosbgp instance to 12, add the bandwidth value 201, and update the test case.
  alicloud/data_source_alicloud_ddosbgp_instances_test.go
  alicloud/resource_alicloud_ddosbgp_instance.go
  alicloud/resource_alicloud_ddosbgp_instance_test.go
  examples/ddosbgp/variables.tf
  website/docs/r/ddosbgp_instance.html.markdown
Labels: documentation, size/M

#1688 improve(kafka): added retry to aviod GetTopicList Throttling.User error.
  alicloud/data_source_alicloud_alikafka_topics.go
  alicloud/resource_alicloud_alikafka_topic_test.go
  alicloud/service_alicloud_alikafka.go
Labels: size/M

#1613 add support to vpn-route-entry
  alicloud/provider.go
  alicloud/resource_alicloud_vpn_route_entry.go
  alicloud/resource_alicloud_vpn_route_entry_test.go
  alicloud/service_alicloud_vpn_gateway.go
  examples/vpn-route-entry/main.tf
  examples/vpn-route-entry/outputs.tf
  examples/vpn-route-entry/variables.tf
  website/alicloud.erb
  website/docs/r/vpn_route_entry.html.markdown
Labels: documentation, size/XL

#1692 improve(client): improve useragent setting
  alicloud/connectivity/client.go
Labels: size/M

#1693 improve(elasticsearch): added retry setting to avoid InstanceStatusNotSupportCurrentAction and InstanceActivating error.
  alicloud/errors.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/S

#1690 improve(ecs):add resource_group_id to ecs
  alicloud/data_source_alicloud_disks.go
  alicloud/data_source_alicloud_disks_test.go
  alicloud/data_source_alicloud_instances.go
  alicloud/data_source_alicloud_instances_test.go
  alicloud/data_source_alicloud_key_pairs.go
  alicloud/data_source_alicloud_key_pairs_test.go
  alicloud/data_source_alicloud_network_interfaces.go
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_key_pair.go
  alicloud/resource_alicloud_key_pair_test.go
  alicloud/resource_alicloud_network_interface.go
  alicloud/resource_alicloud_network_interface_test.go
  website/docs/d/disks.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/key_pairs.html.markdown
  website/docs/d/network_interfaces.html.markdown
  website/docs/r/disk.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/key_pair.html.markdown
  website/docs/r/network_interface.html.markdown
Labels: documentation, size/XL

#1696 fix unsupport account site for test
  alicloud/resource_alicloud_vpn_route_entry_test.go
Labels: size/XS

#1695 improve(ci): add new job emr
  README.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  ci/pipeline.yml
  ci/tasks/run.sh
  ci/tasks/run.yml
Labels: size/S

#1697 improve emr test case
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/S

#1691 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1698 improve emr test case
  alicloud/resource_alicloud_emr_cluster_test.go
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/M

#1703 improve(slb_rule): remove `name` forcenew and make it can be updated
  alicloud/resource_alicloud_slb_rule.go
  alicloud/resource_alicloud_slb_rule_test.go
  website/docs/r/slb_rule.html.markdown
Labels: documentation, size/M
