Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-06, with the labels that each got.

#1241 Fix password to comliant with the default password policy.
  alicloud/resource_alicloud_ram_login_profile_test.go
Labels: size/XS

#1238 Update Eip Association Resource
  alicloud/resource_alicloud_eip_association.go
  alicloud/resource_alicloud_eip_association_test.go
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/M

#1244 resource instance supports timeouts configure
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
  alicloud/data_source_alicloud_ess_scalinggroups_test.go
  alicloud/data_source_alicloud_kvstore_instances.go
  alicloud/data_source_alicloud_route_entries_test.go
  alicloud/data_source_alicloud_route_tables_test.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/errors.go
  alicloud/import_alicloud_cen_instance_test.go
  alicloud/import_alicloud_route_entry_test.go
  alicloud/import_alicloud_route_table_attachment_test.go
  alicloud/import_alicloud_route_table_test.go
  alicloud/import_alicloud_vpn_gateway_test.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/resource_alicloud_ess_scalingrule.go
  alicloud/resource_alicloud_fc_service.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_backup_policy.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/resource_alicloud_log_machine_group.go
  alicloud/resource_alicloud_log_machine_group_test.go
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_log_store.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/resource_alicloud_log_store_index_test.go
  alicloud/resource_alicloud_log_store_test.go
  alicloud/resource_alicloud_logtail_attachment.go
  alicloud/resource_alicloud_logtail_attachment_test.go
  alicloud/resource_alicloud_logtail_config.go
  alicloud/resource_alicloud_logtail_config_test.go
  alicloud/resource_alicloud_nas_mount_target.go
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_group_policy_attachment.go
  alicloud/resource_alicloud_ram_login_profile.go
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_ram_role_policy_attachment.go
  alicloud/resource_alicloud_ram_user_policy_attachment.go
  alicloud/resource_alicloud_route_entry_test.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_route_table_attachment_test.go
  alicloud/resource_alicloud_route_table_test.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/service_alicloud_ecs.go
  alicloud/service_alicloud_kvstore.go
  alicloud/service_alicloud_log.go
  website/docs/r/instance.html.markdown
Labels: size/L

#1245 add pending status for resource instance when creating
  CHANGELOG.md
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#1235 improve ssl_vpn_server testcase
  alicloud/data_source_alicloud_ssl_vpn_servers.go
  alicloud/data_source_alicloud_ssl_vpn_servers_test.go
  alicloud/import_alicloud_ssl_vpn_servers_test.go
  alicloud/resource_alicloud_ssl_vpn_server.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/docs/r/ssl_vpn_server.html.markdown
Labels: documentation, size/XXL

#1230 Improve cen_instance_grant use common method.
  alicloud/import_alicloud_cen_instance_grant_test.go
  alicloud/resource_alicloud_cen_instance_grant.go
  alicloud/resource_alicloud_cen_instance_grant_test.go
  alicloud/service_alicloud_vpc.go
Labels: size/M

#1227 Improve cen_bandwidth_limit use common method.
  alicloud/data_source_alicloud_cen_bandwidth_limits.go
  alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
  alicloud/import_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/service_alicloud_cen.go
Labels: size/XL

#1226 Feature/support multi instance types
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/L

#1225 Improve ess_attachment use common method
  alicloud/import_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_ess_attachment.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_attachment.html.markdown
Labels: documentation, size/XL

#1239 fix cr repo details, improve cs and cr docs
  alicloud/data_source_alicloud_cr_repos.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  website/docs/d/cr_repos.html.markdown
  website/docs/r/cs_application.html.markdown
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/cs_swarm.html.markdown
Labels: documentation, size/M

#1232 improve vpn_customer_gateway testcase
  alicloud/data_source_alicloud_vpn_customer_gateways.go
  alicloud/data_source_alicloud_vpn_customer_gateways_test.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/import_alicloud_vpn_customer_gateways_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_vpn_customer_gateway.go
  alicloud/resource_alicloud_vpn_customer_gateway_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/docs/d/vpn_customer_gateways.html.markdown
  website/docs/r/vpn_customer_gateway.html.markdown
Labels: documentation, size/XL

#1243 added webhook support for alarms
  alicloud/resource_alicloud_cms_alarm.go
  alicloud/resource_alicloud_cms_alarm_test.go
  alicloud/service_alicloud_cms.go
  website/docs/r/cms_alarm.html.markdown
Labels: documentation, size/S

#1191 Handle alicloud_cs_*_kubernetes resource NotFound error properly
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/XS

#1248 improve ssl_vpn_client_cert testcase
  alicloud/data_source_alicloud_ssl_vpn_client_certs.go
  alicloud/data_source_alicloud_ssl_vpn_client_certs_test.go
  alicloud/import_alicloud_ssl_vpn_client_certs_test.go
  alicloud/resource_alicloud_route_table_attachment.go
  alicloud/resource_alicloud_ssl_vpn_client_cert.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/docs/r/ssl_vpn_client_cert.html.markdown
Labels: documentation, size/XXL

#1253 fix slb_attachment err ObtainIpFail
  alicloud/resource_alicloud_slb_attachment_test.go
Labels: size/XS

#1216 Improve cen_instance_attachment resource use common method.
  alicloud/import_alicloud_cen_instance_attachment_test.go
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/resource_alicloud_cen_instance_attachment_test.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cen.go
Labels: size/XL

#1247 Improve ram_account_password_policy resource use common method.
  alicloud/resource_alicloud_ram_account_password_policy.go
  alicloud/resource_alicloud_ram_account_password_policy_test.go
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_account_password_policy.html.markdown
Labels: documentation, size/XL

#1242 improve common test method
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/data_source_alicloud_dns_records_test.go
  alicloud/import_alicloud_dns_record_test.go
  alicloud/import_alicloud_dns_test.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XL

#1254 refactor(nas): move import to resource
  alicloud/import_alicloud_nas_access_group_test.go
  alicloud/import_alicloud_nas_access_rule_test.go
  alicloud/import_alicloud_nas_file_system_test.go
  alicloud/import_alicloud_nas_mount_target_test.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_access_rule_test.go
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/resource_alicloud_nas_mount_target_test.go
Labels: size/XL

#1217 Add support for assume_role in provider block
  alicloud/connectivity/config.go
  alicloud/provider.go
  alicloud/resource_alicloud_ram_account_password_policy.go
  alicloud/validators.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#1256 修复scalingConfiguration传入base64的user_data时，和describe返回的信息不一致
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
Labels: size/M

#1258 fix oss bucket update bug.
  alicloud/resource_alicloud_oss_bucket.go
Labels: size/M

#1250 Improve ess_scalingconfiguration use common method
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  alicloud/service_alicloud_ess.go
  website/docs/index.html.markdown
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/XXL

#1259 fix slb_attachment classic testcase
  alicloud/resource_alicloud_slb_attachment_test.go
Labels: size/XS

#1218 Improve ess_alarm use common method
  alicloud/import_alicloud_ess_alarm_test.go
  alicloud/resource_alicloud_ess_alarm.go
  alicloud/resource_alicloud_ess_alarm_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_alarm.html.markdown
Labels: documentation, size/XL

#1261 update CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#1265 update dns_group testcase name
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/data_source_alicloud_dns_groups_test.go
  alicloud/import_alicloud_dns_test.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/service_alicloud_dns.go
  website/docs/r/dns_record.html.markdown
Labels: documentation, size/XL

#1264 fix(nas): describe mount target & access rule
  alicloud/service_alicloud_nas.go
Labels: size/XS

#1266 Improve fc_function use common method
  alicloud/data_source_alicloud_fc_functions.go
  alicloud/data_source_alicloud_fc_functions_test.go
  alicloud/import_alicloud_fc_function_test.go
  alicloud/resource_alicloud_fc_function.go
  alicloud/resource_alicloud_fc_function_test.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/service_alicloud_fc.go
  website/docs/d/fc_functions.html.markdown
  website/docs/r/fc_function.html.markdown
Labels: documentation, size/XL

#1263 update slb sdk
  alicloud/service_alicloud_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_http_listener.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_https_listener.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/create_load_balancer_tcp_listener.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_http_listener_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_https_listener_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_load_balancer_tcp_listener_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_rule_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_http_listener_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_https_listener_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/set_load_balancer_tcp_listener_attribute.go
  vendor/vendor.json
Labels: dependencies, size/S

#1267 fix(nas): fix documents
  website/docs/d/nas_access_groups.html.markdown
  website/docs/d/nas_access_rules.html.markdown
  website/docs/d/nas_file_systems.html.markdown
  website/docs/d/nas_mount_targets.html.markdown
Labels: documentation, size/XS

#1257 improve vpn_connection testcase
  alicloud/data_source_alicloud_vpn_connections.go
  alicloud/data_source_alicloud_vpn_connections_test.go
  alicloud/import_alicloud_vpn_connections_test.go
  alicloud/resource_alicloud_vpn_connection.go
  alicloud/resource_alicloud_vpn_connection_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/docs/d/vpn_connections.html.markdown
  website/docs/r/vpn_connection.html.markdown
Labels: documentation, size/XXL

#1249 Improve cen_route_entries use common method.
  alicloud/data_source_alicloud_cen_region_route_entries.go
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_cen_route_entries.go
  alicloud/data_source_alicloud_cen_route_entries_test.go
  alicloud/import_alicloud_cen_route_entry_test.go
  alicloud/resource_alicloud_cen_route_entry.go
  alicloud/resource_alicloud_cen_route_entry_test.go
  alicloud/service_alicloud_cen.go
Labels: size/XL

#1240 Improve cen_bandwidth_package_attachment resource use common method.
  alicloud/import_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/service_alicloud_cen.go
Labels: size/L

#1272 fix clientToken bug
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_network_interface.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpn_connection.go
  alicloud/resource_alicloud_vpn_customer_gateway.go
  alicloud/resource_alicloud_vpn_gateway.go
Labels: size/XS

#1237 Improve cen_bandwidth_package resource use common method.
  alicloud/data_source_alicloud_cen_bandwidth_packages.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/import_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/service_alicloud_cen.go
Labels: size/XL

#1276 fix slb_listener docs bug
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/XS

#1277 fix log_store ListShards InternalServerError bug
  alicloud/resource_alicloud_log_store.go
Labels: size/XS

#1278 fc_service datasource support outputting ids and names
  alicloud/data_source_alicloud_fc_services.go
  alicloud/data_source_alicloud_fc_services_test.go
  website/docs/d/fc_services.html.markdown
Labels: documentation, size/L

#1269 Improve fc_service use common method
  alicloud/import_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_service.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/service_alicloud_fc.go
  website/docs/r/fc_service.html.markdown
Labels: documentation, size/XL

#1271 fix(nas): fix document and nas_access_rules
  website/docs/d/nas_access_groups.html.markdown
  website/docs/d/nas_access_rules.html.markdown
  website/docs/d/nas_file_systems.html.markdown
Labels: documentation, size/XS

#1283 fix sql server instance storage set bug
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/XS

#1279 terraform support gpdb data source
  alicloud/data_source_alicloud_gpdb_instances.go
  alicloud/data_source_alicloud_gpdb_instances_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/gpdb_instances.html.markdown
Labels: documentation, size/XL

#1284 modeify apigateway-fc example
  examples/api-gateway-fc/hello.py
  examples/api-gateway-fc/hello.zip
  examples/api-gateway-fc/index.js
  examples/api-gateway-fc/main.tf
  examples/api-gateway-fc/variables.tf
Labels: size/M

#1285 add fc_trigger support cdn_events
  alicloud/import_alicloud_fc_trigger_test.go
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/service_alicloud_fc.go
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/XL

#1289 temp fix no value returned by cs openapi
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/XS

#1287 update CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#1291 update changelog
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#1275 Update Eip Resource Isp Field
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_test.go
  website/docs/r/eip.html.markdown
Labels: documentation, size/XS

#1293 feat(nas): fix error report
  alicloud/errors.go
Labels: size/XS

#1288 fix disk device_name bug
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/resource_alicloud_disk_attachment_test.go
Labels: size/S

#1286 fc_trigger datasource support outputting ids and names
  alicloud/data_source_alicloud_fc_triggers.go
  alicloud/data_source_alicloud_fc_triggers_test.go
  website/docs/d/fc_triggers.html.markdown
Labels: documentation, size/XL

#1295 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1298 Add name for cen bandwidth package testcase
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_cen_instance_test.go
Labels: size/XS

#1290 gpdb connection resource
  alicloud/provider.go
  alicloud/resource_alicloud_gpdb_connection.go
  alicloud/resource_alicloud_gpdb_connection_test.go
  alicloud/service_alicloud_gpdb.go
  website/alicloud.erb
  website/docs/r/gpdb_connection.html.markdown
Labels: documentation, size/XL

#1300 Improve db_instance,db_readonly_instance,db_readwrite_splitting_conne…
  alicloud/import_alicloud_db_instance_test.go
  alicloud/import_alicloud_db_read_write_splitting_connection_test.go
  alicloud/import_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_db_readwrite_splitting_connection_test.go
Labels: size/XXL

#1302 fix disk_attachment test bug
  alicloud/resource_alicloud_disk_attachment_test.go
Labels: size/XS

#1294 Improve db testcase
  alicloud/import_alicloud_db_account_privilege_test.go
  alicloud/import_alicloud_db_account_test.go
  alicloud/import_alicloud_db_backup_policy_test.go
  alicloud/import_alicloud_db_connection_test.go
  alicloud/import_alicloud_db_database_test.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_connection.go
  alicloud/resource_alicloud_db_connection_test.go
  alicloud/resource_alicloud_db_database_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_rds.go
Labels: size/XXL

#1303 Update Eip Resource Isp Field
  alicloud/resource_alicloud_eip_test.go
  website/docs/r/eip.html.markdown
Labels: documentation, size/XS

#1307 fix oss lifecycle nil pointer bug
  alicloud/import_alicloud_oss_bucket_test.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
Labels: size/L

#1299 Improve api_gateway_api use common method.
  alicloud/data_source_alicloud_api_gateway_apis.go
  alicloud/data_source_alicloud_api_gateway_apis_test.go
  alicloud/import_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_api_gateway_api.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/service_alicloud_api_gateway.go
  website/docs/d/api_gateway_apis.html.markdown
Labels: documentation, size/XXL

#1309 fix db_instance_classes
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/data_source_alicloud_db_instance_classes_test.go
  website/docs/d/db_instance_classes.html.markdown
Labels: documentation, size/M

#1305 Fix cen_bandwidth_limit Throttling.User bug
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/service_alicloud_cen.go
  website/docs/d/elasticsearch.html.markdown
  website/docs/r/cen_bandwidth_limit.html.markdown
Labels: documentation, size/M

#1310 add multi_zone for db_instance_classes and db_instance_engines
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/data_source_alicloud_db_instance_engines.go
  alicloud/data_source_alicloud_db_instance_engines_test.go
  website/docs/d/db_instance_classes.html.markdown
  website/docs/d/db_instance_engines.html.markdown
Labels: documentation, size/L

#1317 added importer support for security_group_rule
  alicloud/resource_alicloud_forward_entry_test.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_security_group_rule_test.go
Labels: size/XS

#1316 bugfix: remove the 'ForceNew' attribute of 'vswitch_ids' from resourc…
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  website/docs/r/ess_scaling_group.html.markdown
Labels: documentation, size/S

#1318 cen_instance resource supports timeouts setting.
  alicloud/resource_alicloud_cen_instance.go
  alicloud/service_alicloud_cen.go
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/M

#1321 Improve rds testcase zone_id
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_rds.go
Labels: size/XS

#1320 feature: support enable/disable action for resource alicloud_ess_alarm.
  alicloud/resource_alicloud_ess_alarm.go
  alicloud/resource_alicloud_ess_alarm_test.go
  website/docs/r/ess_alarm.html.markdown
Labels: documentation, size/M

#1319 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1324 fix forward_entries testcase bug
  alicloud/data_source_alicloud_forward_entries_test.go
Labels: size/XS

#1325 fix db_instance_engines testcase
  alicloud/data_source_alicloud_db_instance_engines_test.go
Labels: size/XS

#1311 Improve api_gateway_group use common method.
  alicloud/data_source_alicloud_api_gateway_groups.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  alicloud/import_alicloud_api_gateway_group_test.go
  alicloud/resource_alicloud_api_gateway_group.go
  alicloud/resource_alicloud_api_gateway_group_test.go
  alicloud/service_alicloud_api_gateway.go
  website/docs/d/api_gateway_groups.html.markdown
Labels: documentation, size/XL

#1313 improve snapshot_policy testcase
  alicloud/resource_alicloud_snapshot_policy.go
  alicloud/resource_alicloud_snapshot_policy_test.go
  alicloud/service_alicloud_ecs.go
  website/docs/r/snapshot_policy.html.markdown
Labels: documentation, size/XL

#1322 Organize official documents in alphabetical order
  website/alicloud.erb
Labels: documentation, size/XXL

#1306 Improve api_gateway_app use common method.
  alicloud/data_source_alicloud_api_gateway_apps.go
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  alicloud/data_source_alicloud_api_gateway_groups_test.go
  alicloud/import_alicloud_api_gateway_app_test.go
  alicloud/resource_alicloud_api_gateway_app.go
  alicloud/resource_alicloud_api_gateway_app_attachment.go
  alicloud/resource_alicloud_api_gateway_app_attachment_test.go
  alicloud/resource_alicloud_api_gateway_app_test.go
  alicloud/service_alicloud_api_gateway.go
  website/docs/d/api_gateway_apps.html.markdown
Labels: documentation, size/XL

#1323 Improve api_gateway_vpc use common method.
  alicloud/import_alicloud_api_gateway_vpc_test.go
  alicloud/resource_alicloud_api_gateway_vpc.go
  alicloud/resource_alicloud_api_gateway_vpc_test.go
  alicloud/service_alicloud_api_gateway.go
Labels: documentation, size/L

#1331 fix db_instance_classes,db_instance_engines
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/data_source_alicloud_db_instance_engines.go
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#1330 Add function BuildStateConf for common timeouts setting.
  alicloud/common.go
  alicloud/errors.go
  alicloud/resource_alicloud_cen_bandwidth_limit.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_api_gateway.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/L

#1339 Improve mongodb,rds testcase
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
Labels: size/M

#1336 fix(nas): fix error handling
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/service_alicloud_nas.go
Labels: size/M

#1329 drds_instance resource supports timeouts setting.
  alicloud/data_source_alicloud_drds_instances.go
  alicloud/data_source_alicloud_drds_instances_test.go
  alicloud/import_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_drds_instance.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/service_alicloud_drds.go
  website/docs/r/drds_instance.html.markdown
Labels: documentation, size/XL

#1337 fix log_store fields cannot be changed
  alicloud/resource_alicloud_log_store.go
Labels: size/XS

#1341 fix mongodb testcase
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
Labels: size/XS

#1345 update security_group_rule md
  website/docs/r/security_group_rule.html.markdown
Labels: documentation, size/XS

#1344 fix(nas): convert some retrable error to nonretryable
  alicloud/service_alicloud_nas.go
Labels: size/XS

#1346 Support attach & detach operation for loadbalancers and dbinstances.
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  website/docs/r/ess_scaling_group.html.markdown
Labels: documentation, size/L

#1338 Deprecate field statement and use field document to replace.
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/data_source_alicloud_ram_groups_test.go
  alicloud/data_source_alicloud_ram_policies_test.go
  alicloud/data_source_alicloud_ram_roles_test.go
  alicloud/data_source_alicloud_ram_users_test.go
  alicloud/import_alicloud_ram_group_test.go
  alicloud/resource_alicloud_actiontrail_test.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_ram_group_policy_attachment_test.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_ram_role_attachment_test.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
  examples/ecs-ram-role/main.tf
  examples/ecs-ram-role/variables.tf
  examples/ess-scaling/main.tf
  examples/ram/main.tf
  website/docs/r/ram_group_policy_attachment.html.markdown
  website/docs/r/ram_policy.html.markdown
  website/docs/r/ram_role.html.markdown
  website/docs/r/ram_role_attachment.html.markdown
  website/docs/r/ram_role_policy_attachment.html.markdown
  website/docs/r/ram_user_policy_attachment.html.markdown
  website/docs/r/slb.html.markdown
Labels: documentation, size/XXL

#1347 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1349 remove the skipped testcase
  CHANGELOG.md
  alicloud/resource_alicloud_router_interface_connection_test.go
Labels: size/XS

#1352 bugfix: modify ess loadbalancers batch size
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scalinggroup.go
Labels: size/XS

#1351 fix instance OperationConflict bug
  CHANGELOG.md
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#1357 Update changelog
  CHANGELOG.md
Labels: size/XS

#1359 Fix deleting mongodb instance "NotFound" bug
  CHANGELOG.md
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
Labels: size/XS

#1361 Improve sweeper test and remove some needless waiting
  CHANGELOG.md
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_gpdb_instance_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  alicloud/resource_alicloud_ots_instance_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/S
