Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-10, with the labels that each got.

#1686 improve(provider): update go version to 1.12.
  .travis.yml
  ci/tasks/run.yml
Labels: size/XS

#1709 update golang image version
  ci/tasks/run.yml
Labels: size/XS

#1710 fix go clean error in the ci
  ci/tasks/run.sh
Labels: size/XS

#1711 improve(instance): support encrypt password when creating or updating ecs instance
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_kms.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#1655 impove(slb_listener) slb listener support same port.
  alicloud/common.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/XXL

#1719 update tablestore package
  go.mod
Labels: size/XS

#1718 managekubernetes support sls
  alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/github.com/denverdino/aliyungo/cs/token.go
  vendor/github.com/denverdino/aliyungo/ecs/eni.go
  vendor/github.com/denverdino/aliyungo/ecs/route_tables.go
  vendor/github.com/denverdino/aliyungo/ecs/snat_entry.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/net/publicsuffix/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/d/cs_managed_kubernetes_clusters.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: dependencies, documentation, size/XXL

#1727 improve:improve some resource support encrypt password
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/service_alicloud_elasticsearch.go
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/db_account.html.markdown
  website/docs/r/elasticsearch.html.markdown
  website/docs/r/kvstore_instance.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/XL

#1728 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1730 fix(mongodb):fix password encrypt bug
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
Labels: size/XS

#1679 improve(cs): resources supports timeouts setting.
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/service_alicloud_cs.go
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/L

#1733 fix(cs): modify the new_nat_gateway field in testcase to avoid InstanceRouterEntryNotExist error.
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
Labels: size/XS

#1732 use a new ram role instead of hardcode name about emr unit test case …
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  examples/emr-cluster/variables.tf
Labels: size/S

#1726 fix typo in worker_instance_types description
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS

#1739 improve(slb): updated slb acl testcase.
  alicloud/resource_alicloud_slb_acl_test.go
Labels: size/L

#1741 improve(cdn): added adddebug for tags APIs.
  alicloud/tags.go
Labels: size/XS

#1740 improve(slb): updated slb ca_certificate testcase.
  alicloud/resource_alicloud_slb_ca_certificate_test.go
Labels: documentation, size/M

#1738 improve(slb): updated slb slb_attachment testcase.
  alicloud/resource_alicloud_slb_attachment_test.go
Labels: dependencies, documentation, size/XL

#1752 fix slb sweep bug and add region for role test
  alicloud/provider_test.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/resource_alicloud_slb_test.go
Labels: size/XS

#1751 improve(slb): updated slb serverCertificate testcase.
  alicloud/resource_alicloud_slb_server_certificate_test.go
Labels: size/M

#1744 Improve(alicloud_ess_scaling_rule): support TargetTrackingScalingRule and StepScalingRule
  CHANGELOG.md
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_scalingrule.go
  alicloud/resource_alicloud_ess_scalingrule_test.go
  website/docs/r/ess_scaling_rule.html.markdown
Labels: documentation, size/XL

#1745 fix (cs) : log_config support create new project
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
Labels: size/S

#1754 Add missing routing rules for alicloud_dns_record
  alicloud/data_source_alicloud_dns_records.go
  alicloud/resource_alicloud_dns_record.go
  website/docs/d/dns_records.html.markdown
  website/docs/r/dns_record.html.markdown
Labels: documentation, size/XS

#1746 Terraform support serveless
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_cs_serveless_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_serveless_kubernetes_clusters_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cs_serveless_kubernetes.go
  alicloud/resource_alicloud_cs_serveless_kubernetes_test.go
  alicloud/service_alicloud_cs.go
  examples/serverless-kubernetes/README.md
  examples/serverless-kubernetes/main.tf
  examples/serverless-kubernetes/outputs.tf
  examples/serverless-kubernetes/variables.tf
  examples/serverless-kubernetes/versions.tf
  go.mod
  go.sum
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/github.com/denverdino/aliyungo/cs/kubernets_cluster.go
  vendor/github.com/denverdino/aliyungo/cs/serverless.go
  vendor/github.com/denverdino/aliyungo/cs/token.go
  vendor/modules.txt
  website/docs/d/cs_serverless_kubernetes_clusters.html.markdown
  website/docs/r/cs_serverless_kubernetes.html.markdown
Labels: dependencies, documentation, size/XXL

#1761 Add resource_group_id to common_bandwidth_package(resource&data_source)
  alicloud/data_source_alicloud_common_bandwidth_package_test.go
  alicloud/data_source_alicloud_common_bandwidth_packages.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  website/docs/d/common_bandwidth_packages.html.markdown
  website/docs/r/common_bandwidth_package.html.markdown
Labels: documentation, size/S

#1759 improve(cen): added precheck for testcases.
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_cen_route_entries_test.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_instance_attachment_test.go
  alicloud/resource_alicloud_cen_instance_grant_test.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/resource_alicloud_cen_route_entry_test.go
Labels: size/S

#1748 improve(slb): updated slb rule testcase.
  alicloud/resource_alicloud_slb_rule_test.go
Labels: dependencies, documentation, size/XXL

#1762 improve(security_group):make security_group support resource_group_id
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/tags.go
  website/docs/d/security_groups.html.markdown
  website/docs/r/security_group.html.markdown
Labels: documentation, size/L

#1768 fix(instance):fix instance test bug
  alicloud/resource_alicloud_instance_test.go
Labels: size/XS

#1769 add resource_group_id to vpc, slb resources and data sources and revise corresponding docs
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_eips_test.go
  alicloud/data_source_alicloud_slb_server_certificates.go
  alicloud/data_source_alicloud_slb_server_certificates_test.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_ca_certificate_test.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  website/docs/d/eips.html.markdown
  website/docs/d/slb_server_certificates.html.markdown
  website/docs/r/eip.html.markdown
  website/docs/r/slb_ca_certificate.html.markdown
  website/docs/r/slb_server_certificate.html.markdown
Labels: documentation, size/M

#1770 Add tag for in the docs
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_cen_route_entries_test.go
  website/docs/d/common_bandwidth_packages.html.markdown
  website/docs/d/disks.html.markdown
  website/docs/d/eips.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/key_pairs.html.markdown
  website/docs/d/network_interfaces.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/d/slb_server_certificates.html.markdown
  website/docs/r/disk.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/network_interface.html.markdown
  website/docs/r/slb.html.markdown
  website/docs/r/slb_ca_certificate.html.markdown
  website/docs/r/slb_server_certificate.html.markdown
  website/docs/r/vpc.html.markdown
Labels: documentation, size/S

#1771 Make resource_group_id to computed
  CHANGELOG.md
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_server_certificate.go
Labels: size/XS

#1772 fix(common_bandwidth_package): fix common bandwidth package resource_group_id forcenew bug
  CHANGELOG.md
  alicloud/resource_alicloud_common_bandwidth_package.go
Labels: size/XS

#1775 add missing resource ddosbgp_instance docs index
  CHANGELOG.md
  alicloud/connectivity/client.go
  website/alicloud.erb
  website/docs/r/ddosbgp_instance.html.markdown
  website/docs/r/ddoscoo_instance.html.markdown
Labels: documentation, size/XS

#1753 improve(slb): updated slb server_group testcase.
  alicloud/resource_alicloud_slb_server_group_test.go
Labels: size/XL

#1777 Always set PolicyDocument for RAM policy update
  alicloud/resource_alicloud_ram_policy.go
Labels: size/XS

#1782 fix(ddosbgp): the docs error
  website/alicloud.erb
  website/docs/r/ddosbgp_instance.html.markdown
Labels: documentation, size/XS

#1776 rename cs_serveless_kubernetes to cs_serverless_kubernetes
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_cs_serverless_kubernetes.go
  alicloud/resource_alicloud_cs_serverless_kubernetes_test.go
  alicloud/service_alicloud_cs.go
  examples/serverless-kubernetes/README.md
  examples/serverless-kubernetes/main.tf
  examples/serverless-kubernetes/outputs.tf
  examples/serverless-kubernetes/variables.tf
  go.mod
  go.sum
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/github.com/denverdino/aliyungo/cs/serverless.go
  vendor/modules.txt
  website/alicloud.erb
  website/docs/d/cs_serverless_kubernetes_clusters.html.markdown
  website/docs/r/cs_serverless_kubernetes.html.markdown
Labels: dependencies, documentation, size/L

#1780 improve(provider): modified the kms field conflict to diffsuppress.
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  website/docs/r/db_account.html.markdown
  website/docs/r/elasticsearch.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/kvstore_instance.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/S

#1781 add resource_group_id to dns
  alicloud/data_source_alicloud_dns_domains.go
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/resource_alicloud_dns.go
  alicloud/resource_alicloud_dns_test.go
  website/docs/d/dns_domains.html.markdown
  website/docs/r/dns.html.markdown
Labels: documentation, size/S

#1786 Update ssl_vpn_server.html.markdown
  website/docs/d/ssl_vpn_servers.html.markdown
Labels: documentation, size/XS

#1778 fix(instance):fix credit_specification bug
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#1789 improve(zones): using describeAvailableResource instead of DescribeZones for RKvstore
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_zones.go
  ci/pipeline.yml
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/S

#1773 Feature(emr): new datasource emr_instance_types and emr_main_versions
  alicloud/data_source_alicloud_emr_instance_types.go
  alicloud/data_source_alicloud_emr_instance_types_test.go
  alicloud/data_source_alicloud_emr_main_versions.go
  alicloud/data_source_alicloud_emr_main_versions_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/alicloud.erb
  website/docs/d/emr_instance_types.html.markdown
  website/docs/d/emr_main_versions.html.markdown
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/XL

#1792 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1794 improve(slb_listener):add retry for StartLoadBalancerListener
  alicloud/resource_alicloud_slb_listener.go
Labels: size/XS

#1793 improve(fc_trigger):change testcase dependence resource cdn_domain to new
  alicloud/resource_alicloud_fc_trigger_test.go
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/M

#1795 fix(slb): address_type diff bug
  CHANGELOG.md
  alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
  alicloud/data_source_alicloud_alikafka_topics_test.go
  alicloud/data_source_alicloud_file_crc64_checksum.go
  alicloud/data_source_alicloud_file_crc64_checksum_test.go
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_alikafka_consumer_group_test.go
  alicloud/resource_alicloud_alikafka_topic_test.go
  ci/configure
  ci/pipeline.yml
  ci/tasks/run.sh
  ci/tasks/run.yml
  website/docs/r/alikafka_consumer_group.html.markdown
  website/docs/r/alikafka_instance.html.markdown
  website/docs/r/alikafka_topic.html.markdown
Labels: documentation, size/S

#1796 improve(slb): improve slb docs
  CHANGELOG.md
  website/docs/r/slb.html.markdown
Labels: documentation, size/XS

#1797 improve(slb_listener): deprecate ssl_certificate_id and use server_certificate_id instead
  CHANGELOG.md
  alicloud/data_source_alicloud_slb_listeners.go
  alicloud/data_source_alicloud_slb_listeners_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/M

#1798 improve(instance): field 'user_data' supported update.
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/S

#1801 fix(vpc): fix DescribeTag bug for vpc's datasource
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_route_tables.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vswitch.go
  alicloud/service_alicloud_vpc.go
  website/alicloud.erb
Labels: documentation, size/M

#1802 improve(db_instances):update tags type from string to map
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_db_instances_test.go
  website/docs/d/db_instances.html.markdown
Labels: documentation, size/M

#1788 add sag_acl and sag_acl_rule
  alicloud/data_source_alicloud_sag_acls.go
  alicloud/data_source_alicloud_sag_acls_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_sag_acl.go
  alicloud/resource_alicloud_sag_acl_rule.go
  alicloud/resource_alicloud_sag_acl_rule_test.go
  alicloud/resource_alicloud_sag_acl_test.go
  alicloud/service_alicloud_sag.go
  examples/sag_acl/main.tf
  examples/sag_acl/versions.tf
  examples/sag_acl_rule/main.tf
  examples/sag_acl_rule/versions.tf
  website/alicloud.erb
  website/docs/d/sag_acls.html.markdown
  website/docs/r/sag_acl.html.markdown
  website/docs/r/sag_acl_rule.html.markdown
Labels: documentation, size/XXL

#1756 new data_source and resource slb_domain_extensions
  alicloud/data_source_alicloud_slb_domain_extensions.go
  alicloud/data_source_alicloud_slb_domain_extensions_test.go
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_slb_domain_extension.go
  alicloud/resource_alicloud_slb_domain_extension_test.go
  alicloud/service_alicloud_slb.go
  examples/slb-domain-extension/main.tf
  go.sum
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/slb/describe_domain_extension_attribute.go
  website/alicloud.erb
  website/docs/d/slb_domain_extensions.html.markdown
  website/docs/r/slb_domain_extension.html.markdown
Labels: dependencies, documentation, size/XL

#1803 add ids for db_instance_classess and remove limitation for db_database resource
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/resource_alicloud_db_database.go
  examples/rds/main.tf
  examples/rds/variables.tf
  website/docs/d/db_instance_classes.html.markdown
  website/docs/d/db_instances.html.markdown
  website/docs/r/db_account.html.markdown
  website/docs/r/db_database.html.markdown
Labels: documentation, size/S

#1800 add data_source_alicloud_support_lines
  alicloud/data_source_alicloud_dns_resolution_lines.go
  alicloud/data_source_alicloud_dns_resolution_lines_test.go
  alicloud/provider.go
  website/docs/d/dns_resolution_lines.html.markdown
  website/docs/r/dns_record.html.markdown
Labels: documentation, size/XL

#1811 use homedir to expand shared_credentials_file value and add environment variable for it
  alicloud/provider.go
Labels: size/XS

#1812 fix(rds): fix creating db account empty pointer bug
  alicloud/service_alicloud_rds.go
  website/docs/r/eip.html.markdown
Labels: documentation, size/XS

#1814 Add resource_group_id to data_source_alicloud_route_tables
  alicloud/data_source_alicloud_route_tables.go
  alicloud/data_source_alicloud_route_tables_test.go
  website/docs/d/route_tables.html.markdown
Labels: documentation, size/S

#1817 fix(tag): fix api gw, gpdb, kvstore datasource bug
  alicloud/data_source_alicloud_api_gateway_apps.go
  alicloud/data_source_alicloud_gpdb_instances.go
  alicloud/data_source_alicloud_kvstore_instances.go
  alicloud/resource_alicloud_api_gateway_app.go
  alicloud/service_alicloud_api_gateway.go
Labels: size/M
