Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-04, with the labels that each got.

#958 add ddoscoo test region skip code
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_ddoscoo_instance_test.go
Labels: size/XS

#960 improve ram_policy resource update method
  CHANGELOG.md
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_policy_test.go
  website/docs/r/ram_policy.html.markdown
Labels: documentation, size/L

#948 slb create listener with rr scheduler
  alicloud/extension_slb.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/validators.go
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/M

#964 update ram_policy resource testcase
  CHANGELOG.md
  alicloud/resource_alicloud_ram_policy_test.go
Labels: size/XS

#966 update dns_group describe method
  CHANGELOG.md
  alicloud/resource_alicloud_dns_group.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/service_alicloud_dns.go
Labels: size/S

#927 add test common method ,improve dns resource testcase
  alicloud/resource_alicloud_dns_group.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/service_alicloud_common_test.go
Labels: dependencies, size/XL

#963 Improve db_account db_account_privilege db_backup_policy db_connection
  CHANGELOG.md
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_db_account_privilege.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_connection.go
  alicloud/resource_alicloud_db_connection_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_account.html.markdown
Labels: documentation, size/XXL

#967 add ddoscoo data source code and docs
  alicloud/data_source_alicloud_ddoscoo_instances.go
  alicloud/data_source_alicloud_ddoscoo_instances_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_ddoscoo_instance_test.go
  website/alicloud.erb
  website/docs/d/ddoscoo_instances.html.markdown
Labels: documentation, size/XL

#974 support data source alicloud_ess_scaling_configurations
  alicloud/data_source_alicloud_ess_scalingconfigurations.go
  alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/ess_scaling_configurations.html.markdown
Labels: documentation, size/XL

#976 support data source alicloud_ess_scaling_rules
  alicloud/data_source_alicloud_ess_scalingrules.go
  alicloud/data_source_alicloud_ess_scalingrules_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/ess_scaling_rules.html.markdown
  website/docs/r/ess_scaling_rule.html.markdown
Labels: documentation, size/XL

#946 Add data_source_alicloud_ots_instances.
  alicloud/data_source_alicloud_ots_instances.go
  alicloud/data_source_alicloud_ots_instances_test.go
  alicloud/extension_ots.go
  alicloud/provider.go
  alicloud/service_alicloud_ots.go
  alicloud/tags.go
  alicloud/tags_test.go
  website/docs/d/ots_instances.html.markdown
Labels: documentation, size/XL

#977 support changing prepaid instance type
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/L

#979 Improve instance type updating testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_ots_instances.go
  alicloud/data_source_alicloud_ots_instances_test.go
  alicloud/resource_alicloud_db_database.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readwrite_splitting_connection.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#980 Fix print error bug after DescribeDBInstanceById
  CHANGELOG.md
  alicloud/resource_alicloud_db_database.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#983 Update Nat Gateway Token
  alicloud/resource_alicloud_nat_gateway.go
Labels: size/XS

#987 Update Changelog
  CHANGELOG.md
  website/alicloud.erb
  website/docs/r/cen_instance_attachment.html.markdown
Labels: documentation, size/XS

#954 support snapshot
  alicloud/common.go
  alicloud/errors.go
  alicloud/import_alicloud_snapshot_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_snapshot.go
  alicloud/resource_alicloud_snapshot_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/snapshot.html.markdown
Labels: documentation, size/XL

#971 improve dns dataSource testcase use testCommon method
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/data_source_alicloud_dns_groups_test.go
  alicloud/data_source_alicloud_dns_records_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XXL

#978 improve disk and diskAttachment resource testcase use testCommon method
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_disk_attachment_test.go
  alicloud/resource_alicloud_disk_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_key_pair_attachment_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_ecs.go
Labels: size/XL

#990 improve disk dataSource testcase use common method
  CHANGELOG.md
  alicloud/data_source_alicloud_disks_test.go
  website/docs/r/cen_bandwidth_package_attachment.html.markdown
  website/docs/r/cen_route_entry.html.markdown
Labels: documentation, size/XL

#988 support snapshot datasource
  alicloud/data_source_alicloud_snapshots.go
  alicloud/data_source_alicloud_snapshots_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/snapshots.html.markdown
Labels: documentation, size/XL

#991 Add data_source_alicloud_ots_tables.
  alicloud/data_source_alicloud_ots_instance_attachments.go
  alicloud/data_source_alicloud_ots_instance_attachments_test.go
  alicloud/data_source_alicloud_ots_tables.go
  alicloud/data_source_alicloud_ots_tables_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/ots_instance_attachments.html.markdown
  website/docs/d/ots_tables.html.markdown
Labels: documentation, size/XL

#993 fix a bug
  alicloud/resource_alicloud_vpn_gateway.go
Labels: size/XS

#981 Feature/slb listener redirect http to https
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  examples/slb-listener-forward/main.tf
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/L

#994 fix a bug
  alicloud/resource_alicloud_vpn_connection.go
Labels: size/XS

#998 fix disk importSource testcase bug
  alicloud/import_alicloud_disk_test.go
Labels: size/XS

#1000 Fix Eip And VSwitch Token
  alicloud/errors.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_vswitch.go
Labels: size/XS

#999 fixed #969
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  website/docs/r/db_account.html.markdown
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/S

#1002 Improve cs_cluster sweeper test removing retained resources
  CHANGELOG.md
  alicloud/data_source_alicloud_slb_server_groups_test.go
  alicloud/import_alicloud_snapshot_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_nat_gateway_test.go
  alicloud/resource_alicloud_router_interface_test.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/resource_alicloud_snapshot.go
  alicloud/resource_alicloud_snapshot_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XL

#995 improve security_group testcase use common method
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/import_alicloud_security_group_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_security_group_rule_test.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/service_alicloud_ecs.go
Labels: size/XXL

#1012 improve test common method, support 'TestMatchResourceAttr' check
  CHANGELOG.md
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1015 Update sdk to fix timeout bug
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/logger.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/common_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/roa_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/json_parser.go
  vendor/github.com/json-iterator/go/Gopkg.lock
  vendor/github.com/json-iterator/go/Gopkg.toml
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/adapter.go
  vendor/github.com/json-iterator/go/any.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/iter_skip_strict.go
  vendor/github.com/json-iterator/go/pool.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/json-iterator/go/reflect_native.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/vendor.json
Labels: dependencies, size/XL

#1010 `resource group` support for creating new VPC
  alicloud/resource_alicloud_vpc.go
Labels: size/XS

#1018 add computed for resource_group_id
  alicloud/resource_alicloud_vpc.go
  website/docs/r/vpc.html.markdown
Labels: documentation, size/XS

#1016 remove ram validators and update website docs
  CHANGELOG.md
  alicloud/data_source_alicloud_ram_policies.go
  alicloud/data_source_alicloud_ram_users.go
  alicloud/resource_alicloud_ram_access_key.go
  alicloud/resource_alicloud_ram_account_alias.go
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_group_membership.go
  alicloud/resource_alicloud_ram_group_policy_attachment.go
  alicloud/resource_alicloud_ram_login_profile.go
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_ram_role_attachment.go
  alicloud/resource_alicloud_ram_role_policy_attachment.go
  alicloud/resource_alicloud_ram_user.go
  alicloud/resource_alicloud_ram_user_policy_attachment.go
  alicloud/validators.go
  website/docs/r/ram_group.html.markdown
  website/docs/r/ram_group_membership.html.markdown
  website/docs/r/ram_group_policy_attachment.html.markdown
  website/docs/r/ram_policy.html.markdown
  website/docs/r/ram_role.html.markdown
  website/docs/r/ram_role_attachment.html.markdown
  website/docs/r/ram_role_policy_attachment.html.markdown
  website/docs/r/ram_user_policy_attachment.html.markdown
Labels: documentation, size/XL

#1020 Update Nat Gateway Token
  alicloud/resource_alicloud_nat_gateway.go
Labels: size/XS

#1019 update RAM website document
  website/docs/r/ram_role.html.markdown
  website/docs/r/ram_role_attachment.html.markdown
Labels: documentation, size/XS

#1024 fix Error method
  CHANGELOG.md
  alicloud/errors.go
Labels: size/XS

#1029 Update cen data source document
  website/docs/d/cen_bandwidth_limits.html.markdown
Labels: documentation, size/XS

#1032 bugfix: ess go sdk compatibility
  alicloud/data_source_alicloud_ess_scalinggroups.go
  alicloud/data_source_alicloud_ots_instance_attachments.go
  alicloud/data_source_alicloud_ots_instance_attachments_test.go
  alicloud/data_source_alicloud_ots_tables.go
  alicloud/data_source_alicloud_ots_tables_test.go
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/data_source_alicloud_snapshots.go
  alicloud/data_source_alicloud_snapshots_test.go
  alicloud/service_alicloud_ess.go
Labels: size/XS

#1030 improve test common method
  CHANGELOG.md
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1036 make fmt ess_scalinggroups
  alicloud/data_source_alicloud_ess_scalinggroups.go
Labels: size/XS

#1040 Improve db_database db_instance db_readonly_instance db_readwrite_spl…
  CHANGELOG.md
  alicloud/connectivity/regions.go
  alicloud/import_alicloud_db_database_test.go
  alicloud/import_alicloud_db_instance_test.go
  alicloud/import_alicloud_db_read_write_splitting_connection_test.go
  alicloud/import_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_db_database.go
  alicloud/resource_alicloud_db_database_test.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_db_readwrite_splitting_connection.go
  alicloud/resource_alicloud_db_readwrite_splitting_connection_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_account.html.markdown
  website/docs/r/db_account_privilege.html.markdown
  website/docs/r/db_backup_policy.html.markdown
  website/docs/r/db_connection.html.markdown
  website/docs/r/db_database.html.markdown
  website/docs/r/db_instance.html.markdown
  website/docs/r/db_read_write_splitting_connection.html.markdown
  website/docs/r/db_readonly_instance.html.markdown
Labels: documentation, size/XXL

#1041 improve network_interface resource testcase
  alicloud/import_alicloud_network_interface_attachment_test.go
  alicloud/import_alicloud_network_interface_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_network_interface.go
  alicloud/resource_alicloud_network_interface_attachment.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
  alicloud/resource_alicloud_network_interface_test.go
  alicloud/service_alicloud_ecs.go
  website/docs/r/network_interface.html.markdown
  website/docs/r/network_interface_attachment.html.markdown
Labels: documentation, size/XXL

#1042 improve network_interface dataSource testcase
  alicloud/data_source_alicloud_network_interfaces.go
  alicloud/data_source_alicloud_network_interfaces_test.go
  website/docs/d/network_interfaces.html.markdown
Labels: documentation, size/XL

#1039 improve key_pair resource testcase
  alicloud/import_alicloud_key_pair_test.go
  alicloud/resource_alicloud_key_pair.go
  alicloud/resource_alicloud_key_pair_attachment.go
  alicloud/resource_alicloud_key_pair_attachment_test.go
  alicloud/resource_alicloud_key_pair_test.go
  alicloud/service_alicloud_ecs.go
  website/docs/r/key_pair_attachment.html.markdown
Labels: documentation, size/XL

#1038 improve key_pair dataSource testcase
  alicloud/data_source_alicloud_key_pairs.go
  alicloud/data_source_alicloud_key_pairs_test.go
  website/docs/d/key_pairs.html.markdown
Labels: documentation, size/L

#1043 Update Nat Gateway Resource
  alicloud/errors.go
  alicloud/resource_alicloud_nat_gateway.go
Labels: documentation, size/XS

#1017 add mongodb sharding instance support
  alicloud/extension_mongodb.go
  alicloud/import_alicloud_mongodb_sharding_instance_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_mongodb.go
  website/alicloud.erb
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/XXL

#1046 Fix db_instance can't find method DescribeDbInstance
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#1045 update network_interface testcase config
  CHANGELOG.md
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
Labels: size/S

#1050 improve mongodb testcase
  alicloud/import_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
Labels: size/XXL

#1049 update network_interface dataSource basic testcase config
  alicloud/data_source_alicloud_network_interfaces_test.go
Labels: size/S

#953 support launch template
  alicloud/import_alicloud_launch_template_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_launch_template.go
  alicloud/resource_alicloud_launch_template_test.go
  alicloud/service_alicloud_ecs.go
  alicloud/validators.go
  website/alicloud.erb
  website/docs/r/launch_template.html.markdown
Labels: documentation, size/XXL

#1057 fix cms diff bug and improve its testcases
  README.md
  alicloud/data_source_alicloud_network_interfaces_test.go
  alicloud/diff_suppress_funcs.go
  alicloud/import_alicloud_cms_alarm_test.go
  alicloud/import_alicloud_key_pair_test.go
  alicloud/import_alicloud_network_interface_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_cms_alarm.go
  alicloud/resource_alicloud_cms_alarm_test.go
  alicloud/resource_alicloud_key_pair_test.go
  alicloud/resource_alicloud_launch_template.go
  alicloud/resource_alicloud_launch_template_test.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
  alicloud/resource_alicloud_network_interface_test.go
Labels: size/L

#1056 fixed DB log backup policy bug when the log_retention_period does not input.
  alicloud/resource_alicloud_db_backup_policy.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/XS

#1044 Improve kvstore_backup_policy testcase use common method
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_backup_policy.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/service_alicloud_kvstore.go
  website/docs/r/kvstore_backup_policy.html.markdown
Labels: documentation, size/XL

#1067 change database default zone id to avoid some unsupported cases
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#1052 Improve kvstore_instance testcase use common method
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_backup_policy.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_kvstore.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XXL

#1069 remove zone_id setting in the db instance testcase
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#1062 Improve kvstore_instance datasource use common method
  CHANGELOG.md
  alicloud/data_source_alicloud_kvstore_instances.go
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/import_alicloud_kvstore_backup_policy_test.go
  alicloud/import_alicloud_kvstore_instance_test.go
  website/docs/d/kvstore_instances.html.markdown
Labels: documentation, size/L

#1063 Change password to Yourpassword
  alicloud/data_source_alicloud_cs_kubernetes_clusters_test.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  alicloud/resource_alicloud_cs_application_test.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_key_pair_attachment_test.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  examples/kubernetes-wordpress/README.md
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/cs_swarm.html.markdown
  website/docs/r/ram_login_profile.html.markdown
Labels: documentation, size/M

#1071 Fix db_readonly_instance instance_name
  CHANGELOG.md
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#1074 add rand for db_instances testcase
  alicloud/data_source_alicloud_db_instances_test.go
Labels: size/XS

#1058 improve eip testcase
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_eips_test.go
  alicloud/import_alicloud_dns_test.go
  alicloud/import_alicloud_eip_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_association.go
  alicloud/resource_alicloud_eip_association_test.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/eips.html.markdown
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XXL

#1073 Improve fc_trigger support mns_topic
  CHANGELOG.md
  alicloud/data_source_alicloud_fc_triggers.go
  alicloud/data_source_alicloud_fc_triggers_test.go
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_fc_trigger_test.go
  alicloud/service_alicloud_fc.go
  vendor/github.com/aliyun/fc-go-sdk/README.md
  vendor/github.com/aliyun/fc-go-sdk/account.go
  vendor/github.com/aliyun/fc-go-sdk/alias.go
  vendor/github.com/aliyun/fc-go-sdk/cdn_events_trigger.go
  vendor/github.com/aliyun/fc-go-sdk/client.go
  vendor/github.com/aliyun/fc-go-sdk/connect.go
  vendor/github.com/aliyun/fc-go-sdk/const.go
  vendor/github.com/aliyun/fc-go-sdk/custom_domain.go
  vendor/github.com/aliyun/fc-go-sdk/function.go
  vendor/github.com/aliyun/fc-go-sdk/glide.lock
  vendor/github.com/aliyun/fc-go-sdk/go.mod
  vendor/github.com/aliyun/fc-go-sdk/go.sum
  vendor/github.com/aliyun/fc-go-sdk/mns_trigger.go
  vendor/github.com/aliyun/fc-go-sdk/option.go
  vendor/github.com/aliyun/fc-go-sdk/service.go
  vendor/github.com/aliyun/fc-go-sdk/tablestore_trigger.go
  vendor/github.com/aliyun/fc-go-sdk/trigger.go
  vendor/github.com/aliyun/fc-go-sdk/util.go
  vendor/github.com/aliyun/fc-go-sdk/version.go
  vendor/gopkg.in/resty.v1/BUILD.bazel
  vendor/gopkg.in/resty.v1/LICENSE
  vendor/gopkg.in/resty.v1/README.md
  vendor/gopkg.in/resty.v1/WORKSPACE
  vendor/gopkg.in/resty.v1/client.go
  vendor/gopkg.in/resty.v1/default.go
  vendor/gopkg.in/resty.v1/go.mod
  vendor/gopkg.in/resty.v1/middleware.go
  vendor/gopkg.in/resty.v1/redirect.go
  vendor/gopkg.in/resty.v1/request.go
  vendor/gopkg.in/resty.v1/request16.go
  vendor/gopkg.in/resty.v1/request17.go
  vendor/gopkg.in/resty.v1/response.go
  vendor/gopkg.in/resty.v1/resty.go
  vendor/gopkg.in/resty.v1/retry.go
  vendor/gopkg.in/resty.v1/util.go
  vendor/vendor.json
  website/docs/d/fc_triggers.html.markdown
  website/docs/r/fc_trigger.html.markdown
Labels: dependencies, size/XXL

#1075 fix eip_association bug when snat or forward be released
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_eip_association.go
Labels: size/XS

#1077 update some eip method name
  alicloud/data_source_alicloud_eips_test.go
  alicloud/import_alicloud_eip_test.go
Labels: size/XS

#1080 Fix kvstore_instance multi
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_instance_test.go
Labels: size/XS

#1065 improve vpc testcase
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/import_alicloud_vpc_test.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/service_alicloud_vpc.go
Labels: size/XL

#1082 Improve fc_trigger support mns_topic modify config
  alicloud/resource_alicloud_fc_trigger.go
  alicloud/resource_alicloud_fc_trigger_test.go
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/M

#1076 improve vswitch testcase
  CHANGELOG.md
  GNUmakefile
  alicloud/data_source_alicloud_fc_functions_test.go
  alicloud/data_source_alicloud_fc_services_test.go
  alicloud/data_source_alicloud_fc_triggers_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/data_source_alicloud_vswitches_test.go
  alicloud/import_alicloud_vswitch_test.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_drds_instance.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_fc_service.go
  alicloud/resource_alicloud_fc_service_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_nas_mount_target.go
  alicloud/resource_alicloud_ots_instance_attachment.go
  alicloud/resource_alicloud_ots_instance_attachment_test.go
  alicloud/resource_alicloud_vswitch.go
  alicloud/resource_alicloud_vswitch_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_ecs.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/vswitches.html.markdown
Labels: documentation, size/XXL

#1081 fixed rds datasource readOnlyInstanceIDs bug and improve test case
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_db_instances_test.go
Labels: size/L

#1086 Fix fc_triggers datasource when type is mns_topic
  CHANGELOG.md
  alicloud/data_source_alicloud_fc_triggers_test.go
Labels: size/XS

#1085 Modified the error code returned when timeout of upgrading instance.
  alicloud/errors.go
  alicloud/service_alicloud_elasticsearch.go
Labels: size/XS

#1083 improve db backup policy test case
  alicloud/data_source_alicloud_db_instances.go
  alicloud/import_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_backup_policy_test.go
Labels: size/XXL

#1088 Modify table to entry
  alicloud/data_source_alicloud_snat_entries.go
Labels: size/XS

#1090 Improve slb resource use common method
  alicloud/import_alicloud_slb_test.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_attachment.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/XL

#1089 improve nat_gateway testcase
  alicloud/data_source_alicloud_nat_gateways.go
  alicloud/data_source_alicloud_nat_gateways_test.go
  alicloud/import_alicloud_nat_gateway_test.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_nat_gateway_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/nat_gateways.html.markdown
  website/docs/r/nat_gateway.html.markdown
Labels: documentation, size/XXL

#1091 improve snat_entry testcase
  alicloud/data_source_alicloud_snat_entries.go
  alicloud/data_source_alicloud_snat_entries_test.go
  alicloud/import_alicloud_snat_entry_test.go
  alicloud/resource_alicloud_snat_entry.go
  alicloud/resource_alicloud_snat_entry_test.go
  alicloud/resource_alicloud_snat_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/snat_entries.html.markdown
  website/docs/r/snat.html.markdown
Labels: documentation, size/XXL

#1051 feat(nas): add datasource describe_zones
  alicloud/data_source_alicloud_nas_protocols.go
  alicloud/data_source_alicloud_nas_protocols_test.go
  alicloud/provider.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/nas/describe_zones.go
  vendor/vendor.json
  website/alicloud.erb
  website/docs/d/nas_protocols.html.markdown
Labels: dependencies, documentation, size/L
