Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-12, with the labels that each got.

#1934 improve(vpc): add module support for vpc, vswitch and route entry
  CHANGELOG.md
  website/docs/r/route_entry.html.markdown
  website/docs/r/vpc.html.markdown
  website/docs/r/vswitch.html.markdown
Labels: documentation, size/XS

#1923 fix #1867 add serverless kube_config
  alicloud/data_source_alicloud_cs_serverless_kubernetes_clusters_test.go
  alicloud/resource_alicloud_cs_serverless_kubernetes.go
Labels: size/XS

#1913 improve(ecs): add resource image
  alicloud/provider.go
  alicloud/resource_alicloud_image.go
  alicloud/resource_alicloud_image_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/image.html.markdown
Labels: documentation, size/XL

#1933 improve(cloud_connect_network_attachment): add resource
  alicloud/provider.go
  alicloud/resource_alicloud_cloud_connect_network_attachment.go
  alicloud/resource_alicloud_cloud_connect_network_attachment_test.go
  alicloud/service_alicloud_sag.go
  examples/cloud_connect_network_attachment/main.tf
  examples/cloud_connect_network_attachment/versions.tf
  website/alicloud.erb
  website/docs/r/cloud_connect_network_attachment.html.markdown
Labels: documentation, size/XL

#1936 fix(pvtz_zone_record): allow SRV records
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/XS

#1937 fix(cdn_domain_new): constant timeout waiting for server cert
  alicloud/resource_alicloud_cdn_domain_new.go
Labels: size/XS

#1931 update example to support for snat's creation with multi eips
  alicloud/resource_alicloud_cdn_domain_new.go
Labels: documentation, size/XS

#1749 make 'instance_types' 'db_instance_class' 'kvstore_instance_class' support price
  alicloud/data_source_alicloud_db_instance_classes.go
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/data_source_alicloud_instance_types.go
  alicloud/data_source_alicloud_instance_types_test.go
  alicloud/data_source_alicloud_kvstore_instance_classes.go
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
  alicloud/service_alicloud_bssopenapi.go
  website/docs/d/db_instance_classes.html.markdown
  website/docs/d/instance_types.html.markdown
  website/docs/d/kvstore_instance_classes.html.markdown
Labels: documentation, size/XL

#1942 fix 3az test case
  alicloud/resource_alicloud_cs_kubernetes_test.go
Labels: size/XS

#1943 improve(datasources): remove sorted_by testcase results from some internal limitation
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/data_source_alicloud_instance_types_test.go
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
Labels: size/M

#1945 improve(db_account_privilege): supports more privileges
  alicloud/data_source_alicloud_db_instance_classes_test.go
  alicloud/extension_rds.go
  alicloud/resource_alicloud_db_account_privilege.go
  alicloud/resource_alicloud_db_account_test.go
  website/docs/r/db_account_privilege.html.markdown
Labels: documentation, size/S

#1919 - improve(ess): resource alicloud_ess_scalinggroup_vserver_groups sup…
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups.go
  alicloud/resource_alicloud_ess_scalinggroup_vserver_groups_test.go
  website/docs/r/ess_scalinggroup_vserver_groups.markdown
Labels: documentation, size/S

#1947 Fix bug in when doing alikafka instance multi acc test.
  alicloud/resource_alicloud_alikafka_instance_test.go
Labels: size/XS

#1954 update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#1957 improve(docs): improve module guide
  CHANGELOG.md
  website/docs/d/db_instance_classes.html.markdown
  website/docs/d/instance_types.html.markdown
  website/docs/d/kvstore_instance_classes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
  website/docs/r/ess_alarm.html.markdown
  website/docs/r/ess_scaling_configuration.html.markdown
  website/docs/r/ess_scaling_group.html.markdown
  website/docs/r/ess_scaling_lifecycle_hook.html.markdown
  website/docs/r/ess_scaling_rule.html.markdown
  website/docs/r/ess_scheduled_task.html.markdown
  website/docs/r/route_entry.html.markdown
  website/docs/r/vpc.html.markdown
  website/docs/r/vswitch.html.markdown
Labels: documentation, size/S

#1946 fix(validator): update package github.com/denverdino/aliyungo/cdn
  alicloud/resource_alicloud_cdn_domain.go
  go.mod
  go.sum
  vendor/github.com/denverdino/aliyungo/cdn/types.go
  vendor/github.com/denverdino/aliyungo/common/client.go
  vendor/github.com/denverdino/aliyungo/common/types.go
  vendor/github.com/denverdino/aliyungo/ecs/client.go
  vendor/modules.txt
Labels: dependencies, size/M

#1958 fix(kms): correct test case errors
  alicloud/resource_alicloud_kms_ciphertext_test.go
  ci/pipeline.yml
  ci/tasks/run.sh
Labels: size/M

#1959 fix(datahub): fix updating datahub topic comment bug
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/resource_alicloud_datahub_topic.go
Labels: size/M

#1960 fix(alicloud/yundun_bastionhost): Bastionhost RAM policy authorizatio…
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_bastionhost_instance_test.go
  alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
  alicloud/service_alicloud_yundun_bastionhost.go
  alicloud/service_alicloud_yundun_dbaudit.go
Labels: size/S

#1962 fix(market): remove the tags check for avoid the error of testcase.
  alicloud/data_source_alicloud_market_products_test.go
Labels: size/XS

#1807 improve(sag_client_user): add sag_client_user
  alicloud/diff_suppress_funcs.go
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_sag_client_user.go
  alicloud/resource_alicloud_sag_client_user_test.go
  examples/sag_client_user/main.tf
  examples/sag_client_user/versions.tf
  website/alicloud.erb
  website/docs/r/sag_client_user.html.markdown
Labels: documentation, size/XL

#1964 fix(market): remove the suggested_price check for avoid the error of testcase.
  alicloud/data_source_alicloud_market_products_test.go
Labels: size/XS

#1963 fix(provider): Resolve issues from aone.
  website/docs/r/api_gateway_app.html.markdown
  website/docs/r/ram_account_password_policy.html.markdown
  website/docs/r/ram_group.html.markdown
Labels: documentation, size/XS

#1966 add AccessKey and AccessKeySecret instead of RamRole
  alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
Labels: size/L

#1970 improve(slb_server_group): set servers to computed and avoid diff when using ess_scaling_vserver_group
  alicloud/resource_alicloud_slb_server_group.go
Labels: size/XS

#1971 improve(kvstore_instance): set period using createtime and endtime
  alicloud/common.go
  alicloud/connectivity/client.go
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/M

#1967 add resource purchase_reserved_instances_offering
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_reserved_instance.go
  alicloud/resource_alicloud_reserved_instance_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/reserved_instance.html.markdown
Labels: documentation, size/XL

#1975 update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#1976 improve(ess_vserver_groups): improve docs
  CHANGELOG.md
  website/docs/r/ess_scalinggroup_vserver_groups.markdown
Labels: documentation, size/XS

#1977 fix(vpn): added Computed to field `vswitch_id`.
  alicloud/resource_alicloud_vpn_gateway.go
Labels: size/XS

#1980 improve(mongoDB): supported field 'tags'.
  alicloud/data_source_alicloud_mongodb_instances.go
  alicloud/data_source_alicloud_mongodb_instances_test.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/d/mongodb_instances.html.markdown
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/L

#1981 fix(vpn): fix bug from issue #1965
  alicloud/resource_alicloud_vpn_gateway.go
Labels: size/XS

#1984 improve(prepaid): add a method to fix period importer diff
  alicloud/common.go
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_emr_cluster.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_dbaudit_instance.go
  alicloud/service_alicloud_slb.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#1985 improve(prepaid): support computing period by week
  CHANGELOG.md
  alicloud/common.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_emr_cluster.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_dbaudit_instance.go
  website/alicloud.erb
  website/docs/d/caller_identity.markdown
  website/docs/r/cs_kubernetes_autoscaler.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/M

#1987 fix(fc): fixed bug from issue #1961
  alicloud/resource_alicloud_fc_trigger.go
Labels: size/XS

#1988 improve(period): improve computing period method
  alicloud/common.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_slb.go
  alicloud/service_alicloud_rds.go
Labels: size/M

#1989 documenting the replica_set_name attribute in mongodb
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/XS

#1992 improve(market): product datasource supported name regex and ids filter.
  alicloud/data_source_alicloud_market_products.go
  alicloud/data_source_alicloud_market_products_test.go
  website/docs/d/market_products.html.markdown
Labels: documentation, size/M

#1991 improve(polardb): feature polardb support backup policy
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_backup_policy.go
  alicloud/resource_alicloud_polardb_backup_policy_test.go
  website/alicloud.erb
  website/docs/r/polardb_backup_policy.html.markdown
Labels: documentation, size/XL

#1990 improve(instance): improve auto_renew_period setting
  CHANGELOG.md
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/resource_alicloud_polardb_cluster_test.go
Labels: size/S

#1996 improve(polardb): feature polardb support database
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_database.go
  alicloud/resource_alicloud_polardb_database_test.go
  website/alicloud.erb
  website/docs/r/polardb_database.html.markdown
Labels: documentation, size/XL

#1993 create account for kvstore
  alicloud/provider.go
  alicloud/resource_alicloud_kvstore_account.go
  alicloud/resource_alicloud_kvstore_account_test.go
  alicloud/service_alicloud_kvstore.go
  examples/kvstore/main.tf
  website/alicloud.erb
  website/docs/r/kvstore_account.html.markdown
Labels: documentation, size/XL

#1997 add missing tags for acl, keypair and so n
  alicloud/common.go
  alicloud/data_source_alicloud_key_pairs.go
  alicloud/data_source_alicloud_key_pairs_test.go
  alicloud/data_source_alicloud_slb_acls.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/data_source_alicloud_slb_ca_certificates.go
  alicloud/data_source_alicloud_slb_ca_certificates_test.go
  alicloud/data_source_alicloud_slb_server_certificates.go
  alicloud/data_source_alicloud_slb_server_certificates_test.go
  alicloud/resource_alicloud_key_pair.go
  alicloud/resource_alicloud_key_pair_test.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_acl_test.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_ca_certificate_test.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  alicloud/service_alicloud_slb.go
  alicloud/tags.go
  website/docs/d/key_pairs.html.markdown
  website/docs/d/mongodb_instances.html.markdown
  website/docs/d/slb_acls.html.markdown
  website/docs/d/slb_ca_certificates.html.markdown
  website/docs/d/slb_server_certificates.html.markdown
  website/docs/r/key_pair.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/slb_acl.html.markdown
  website/docs/r/slb_ca_certificate.html.markdown
  website/docs/r/slb_server_certificate.html.markdown
Labels: documentation, size/XL

#1978 add copy image
  alicloud/provider.go
  alicloud/resource_alicloud_copy_images.go
  alicloud/resource_alicloud_copy_images_test.go
  alicloud/resource_alicloud_image.go
  alicloud/resource_alicloud_image_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/copy_image.html.markdown
  website/docs/r/image.html.markdown
Labels: documentation, size/XL

#2002 add argument 'account_privilege' for kvstore account
  alicloud/resource_alicloud_kvstore_account.go
  alicloud/resource_alicloud_kvstore_account_test.go
  website/docs/r/kvstore_account.html.markdown
Labels: documentation, size/M

#2003 fix(db_backup_policy): fix postgresql backup policy bug
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_log_store_index.go
  alicloud/service_alicloud_rds.go
  ci/pipeline.yml
Labels: size/S

#1998 improve(polardb): feature polardb support account
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_account.go
  alicloud/resource_alicloud_polardb_account_test.go
  website/alicloud.erb
  website/docs/r/polardb_account.html.markdown
  website/docs/r/polardb_backup_policy.html.markdown
  website/docs/r/polardb_cluster.html.markdown
  website/docs/r/polardb_database.html.markdown
Labels: documentation, size/XL

#2005 improve(polardb): feature polardb support account privilege
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_account_privilege.go
  alicloud/resource_alicloud_polardb_account_privilege_test.go
  website/alicloud.erb
  website/docs/r/polardb_account_privilege.html.markdown
Labels: documentation, size/XL

#2009 remove type 'Super' for kvstore
  alicloud/resource_alicloud_kvstore_account.go
  website/docs/r/kvstore_account.html.markdown
Labels: documentation, size/XS

#2006 feat(alicloud/yundun_bastionhost): Add support for Cloud Bastionhost
  alicloud/data_source_alicloud_yundun_bastionhost_instances.go
  alicloud/data_source_alicloud_yundun_bastionhost_instances_test.go
  alicloud/data_source_alicloud_yundun_dbaudit_instances.go
  alicloud/data_source_alicloud_yundun_dbaudit_instances_test.go
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_bastionhost_instance_test.go
  alicloud/resource_alicloud_yundun_dbaudit_instance.go
  alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
  alicloud/service_alicloud_yundun_bastionhost.go
  alicloud/service_alicloud_yundun_dbaudit.go
  website/docs/d/yundun_bastionhost_instances.html.markdown
  website/docs/d/yundun_dbaudit_instances.html.markdown
  website/docs/r/yundun_bastionhost_instance.html.markdown
  website/docs/r/yundun_dbaudit_instance.html.markdown
Labels: dependencies, documentation, size/XL

#2008 support emr cluster tag
  alicloud/resource_alicloud_emr_cluster.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_emr.go
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/M

#2024 improve(cdn_config): remove the args private_oss_tbl
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/XS

#2017 improve(rds): fix rds resource alicloud_db_backup_policy`s log_backup bug
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/XL

#2025 improve(mongodb): hidden some security ips
  alicloud/resource_alicloud_gpdb_instance.go
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/service_alicloud_gpdb.go
  alicloud/service_alicloud_mongodb.go
  alicloud/service_alicloud_polardb.go
Labels: size/M

#2010 add resource group id
  alicloud/data_source_alicloud_slb_acls.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/resource_alicloud_cdn_domain_new.go
  alicloud/resource_alicloud_cdn_domain_new_test.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_acl_test.go
  website/docs/d/slb_acls.html.markdown
  website/docs/r/cdn_domain_new.html.markdown
  website/docs/r/slb_acl.html.markdown
Labels: documentation, size/M

#2031 improve(ci): add hbase ci
  alicloud/resource_alicloud_hbase_instance.go
  ci/pipeline.yml
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ess/struct_suspended_processes.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ess/struct_suspended_processes.go~add data_source_alicloud_hbase_instances.go
  vendor/modules.txt
  website/alicloud.erb
Labels: dependencies, documentation, size/M

#2030 improve(rds): fix policy sqlserver test bug
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_backup_policy_test.go
Labels: size/XS

#2032 UpdateChangelog
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/S

#2034 rollback hbase resource and datasource because of them need to be improved
  CHANGELOG.md
  website/alicloud.erb
Labels: documentation, size/XS
