Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-05, with the labels that each got.

#1105 fix slb instance sets tags bug
  alicloud/resource_alicloud_slb.go
Labels: size/XS

#1107 update data_source_alicoud_mongo_instances and add test case
  alicloud/data_source_alicloud_mongodb_instances.go
  alicloud/data_source_alicloud_mongodb_instances_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/mongodb_instances.html.markdown
Labels: documentation, size/L

#1112 Improve ram_roles datasource use common method
  alicloud/data_source_alicloud_ram_roles.go
  alicloud/data_source_alicloud_ram_roles_test.go
  website/docs/d/ram_roles.html.markdown
Labels: documentation, size/L

#1113 Improve slb_ca_certificate resource use common method
  alicloud/import_alicloud_slb_ca_certificate_test.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_ca_certificate_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_acl.html.markdown
  website/docs/r/slb_ca_certificate.html.markdown
Labels: documentation, size/L

#1092 Improve slb_acl resource use common method
  alicloud/import_alicloud_slb_acl_test.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_acl_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_acl.html.markdown
Labels: documentation, size/XL

#1095 fix not support outputfile
  alicloud/data_source_alicloud_slb_attachments.go
  alicloud/data_source_alicloud_slb_listeners.go
  alicloud/data_source_alicloud_slb_rules.go
  alicloud/data_source_alicloud_slb_server_groups.go
Labels: size/XS

#1119 Fix scalinggroup id is not found before creating scaling configuration
  alicloud/data_source_alicloud_eips_test.go
  alicloud/data_source_alicloud_nas_protocols_test.go
  alicloud/data_source_alicloud_nat_gateways_test.go
  alicloud/data_source_alicloud_snat_entries_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/import_alicloud_eip_test.go
  alicloud/import_alicloud_nat_gateway_test.go
  alicloud/import_alicloud_snat_entry_test.go
  alicloud/import_alicloud_vswitch_test.go
  alicloud/resource_alicloud_eip_association_test.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_nat_gateway_test.go
  alicloud/resource_alicloud_snat_entry_test.go
  alicloud/service_alicloud_ess.go
Labels: size/M

#1096 update route_entry and forward_entry document
  website/docs/r/forward.html.markdown
  website/docs/r/route_entry.html.markdown
Labels: documentation, size/L

#1106 add mongodb backup policy support, test case, document
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/XL

#1108 Improve ram_account_alias use common method
  alicloud/data_source_alicloud_ram_account_alias.go
  alicloud/data_source_alicloud_ram_account_alias_test.go
Labels: size/S

#989 support snapshot policy
  alicloud/common.go
  alicloud/provider.go
  alicloud/resource_alicloud_snapshot_policy.go
  alicloud/resource_alicloud_snapshot_policy_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/snapshot_policy.html.markdown
Labels: documentation, size/XL

#1123 Add missing bracket
  CHANGELOG.md
  alicloud/service_alicloud_ecs.go
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/snapshot_policy.html.markdown
Labels: documentation, size/XS

#1116 Modified the sweep rules in ram_roles testcases.
  alicloud/data_source_alicloud_ram_roles_test.go
Labels: size/XS

#1111 Improve slb datasource use common method
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
  alicloud/data_source_alicloud_slbs.go
  alicloud/data_source_alicloud_slbs_test.go
  website/docs/d/slbs.html.markdown
Labels: documentation, size/XL

#1122 add support sha256
  alicloud/extension_vpn.go
  alicloud/resource_alicloud_vpn_connection.go
  alicloud/resource_alicloud_vpn_connection_test.go
  examples/vpn/main.tf
  website/docs/r/vpn_connection.html.markdown
Labels: documentation, size/M

#1114 improve instance testcase
  alicloud/data_source_alicloud_instances.go
  alicloud/data_source_alicloud_instances_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_ecs.go
Labels: size/XXL

#1126 Improve ram_users datasource use common method
  alicloud/data_source_alicloud_ram_users.go
  alicloud/data_source_alicloud_ram_users_test.go
  website/docs/d/ram_users.html.markdown
Labels: documentation, size/L

#1125 Improve ram_policies datasource use common method
  alicloud/data_source_alicloud_ram_policies.go
  alicloud/data_source_alicloud_ram_policies_test.go
  website/docs/d/ram_policies.html.markdown
Labels: documentation, size/XL

#1124 rds datasource test case remove connection mode check
  alicloud/data_source_alicloud_db_instances_test.go
Labels: size/S

#1121 Improve ram_groups datasource use common method
  alicloud/data_source_alicloud_ram_groups.go
  alicloud/data_source_alicloud_ram_groups_test.go
  alicloud/service_alicloud_ram.go
  website/docs/d/ram_groups.html.markdown
Labels: documentation, size/XL

#1133 update images testcase check condition
  alicloud/data_source_alicloud_images_test.go
Labels: size/XS

#1134 Update Route Entry Resource
  alicloud/resource_alicloud_route_entry.go
Labels: size/XS

#1127 mongodb sharding instance add backup policy support
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/XL

#1131 bugfix: ess alarm apply重复创建
  alicloud/extension_ess.go
  alicloud/resource_alicloud_ess_alarm.go
  alicloud/service_alicloud_ess.go
Labels: size/S

#1130 improve slb_listener resource use common method
  alicloud/import_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/XXL

#1128 add child_instance_owner_id for resource_alicloud_cen_instance_attach…
  alicloud/import_alicloud_cen_instance_grant_test.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/resource_alicloud_cen_instance_attachment_test.go
  alicloud/resource_alicloud_cen_instance_grant_test.go
  website/docs/r/cen_instance_attachment.html.markdown
  website/docs/r/cen_instance_grant.html.markdown
Labels: documentation, size/S

#1138 improve mongodb and db sweeper test
  alicloud/data_source_alicloud_instances_test.go
  alicloud/data_source_alicloud_ram_groups_test.go
  alicloud/data_source_alicloud_ram_policies_test.go
  alicloud/data_source_alicloud_ram_users_test.go
  alicloud/import_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_snapshot_policy.go
  alicloud/resource_alicloud_snapshot_policy_test.go
  alicloud/service_alicloud_slb.go
Labels: size/S

#1137 Alicloud_ots_table: add max version offset
  alicloud/resource_alicloud_ots_table.go
  alicloud/resource_alicloud_ots_table_test.go
  alicloud/validators.go
  alicloud/validators_test.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/README.md
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/sample.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/api.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/error.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/model.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/ots_header.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/build_proto.sh
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/ots_filter.pb.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/ots_filter.proto
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/search.pb.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/search.proto
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/table_store.pb.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/otsprotocol/table_store.proto
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/plain_buffer.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/collapse.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_bool.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_const_score.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_exists.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_function_score.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_geo_bounding_box.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_geo_distance.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_geo_polygon.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_match.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_match_phrase.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_matchall.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_nested.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_prefix.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_range.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_term.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_terms.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/query_wildcard.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/search_query.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_field.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_geo_distance.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_mode.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_order.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_primary_key.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/sort_score.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search/variant_types.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search_api.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/search_model.go
  vendor/github.com/aliyun/aliyun-tablestore-go-sdk/tablestore/util.go
  vendor/vendor.json
  website/docs/r/ots_table.html.markdown
Labels: dependencies, size/XXL

#1142 Update ots document
  website/docs/d/ots_tables.html.markdown
Labels: documentation, size/XS

#1129 improve common_bandwidth_package testcase
  alicloud/data_source_alicloud_common_bandwidth_package_test.go
  alicloud/data_source_alicloud_common_bandwidth_packages.go
  alicloud/import_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/import_alicloud_common_bandwidth_package_test.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  alicloud/service_alicloud_common_bandwidth_package.go
  alicloud/service_alicloud_vpc.go
  website/docs/r/common_bandwidth_package.html.markdown
Labels: documentation, size/XXL

#1145 slb instance support updating specification
  alicloud/import_alicloud_slb_test.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
Labels: size/M

#1143 add note for SLB that intl account does not support creating PrePaid instance
  website/docs/r/slb.html.markdown
Labels: documentation, size/XS

#1147 Improve ram_account_alias resource use common method
  alicloud/resource_alicloud_ram_account_alias.go
  alicloud/resource_alicloud_ram_account_alias_test.go
  alicloud/service_alicloud_ram.go
Labels: size/M

#1144 improve slb_server_group resource use common method
  alicloud/import_alicloud_slb_server_group_test.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_server_group.go
  alicloud/resource_alicloud_slb_server_group_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_acl.html.markdown
  website/docs/r/slb_server_group.html.markdown
Labels: documentation, size/XL

#1136 improve slb_rule resource use common method
  alicloud/import_alicloud_slb_rule_test.go
  alicloud/resource_alicloud_slb_rule.go
  alicloud/resource_alicloud_slb_rule_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_rule.html.markdown
Labels: documentation, size/XL

#1139 improve slb_server_certificate resource use common method
  alicloud/import_alicloud_slb_server_certificate_test.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_server_certificate.html.markdown
Labels: documentation, size/L

#1148 improve slb_attachment resource use common method
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_attachment.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_slb.go
  website/docs/r/slb_attachment.html.markdown
Labels: documentation, size/XL

#1157 fix(nas): refactor testcases
  alicloud/data_source_alicloud_nas_file_systems_test.go
  alicloud/data_source_alicloud_nas_protocols.go
  alicloud/resource_alicloud_nas_file_system_test.go
Labels: size/M

#1162 update document
  website/docs/d/forward_entries.html.markdown
  website/docs/d/ots_instance_attachments.html.markdown
  website/docs/d/snat_entries.html.markdown
  website/docs/r/ots_table.html.markdown
  website/docs/r/route_entry.html.markdown
Labels: documentation, size/M

#1155 Improve some slb datasource
  alicloud/data_source_alicloud_slb_acls.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/data_source_alicloud_slb_attachments.go
  alicloud/data_source_alicloud_slb_attachments_test.go
  alicloud/data_source_alicloud_slb_ca_certificates.go
  alicloud/data_source_alicloud_slb_ca_certificates_test.go
  alicloud/data_source_alicloud_slb_rules.go
  alicloud/data_source_alicloud_slb_rules_test.go
  alicloud/data_source_alicloud_slb_server_certificates.go
  alicloud/data_source_alicloud_slb_server_certificates_test.go
  alicloud/data_source_alicloud_slb_server_groups.go
  alicloud/data_source_alicloud_slb_server_groups_test.go
  alicloud/import_alicloud_slb_attachment_test.go
  website/docs/d/slb_acls.html.markdown
  website/docs/d/slb_ca_certificates.html.markdown
  website/docs/d/slb_rules.html.markdown
  website/docs/d/slb_server_certificates.html.markdown
  website/docs/d/slb_server_groups.html.markdown
Labels: documentation, size/XXL

#1161 Fix ram account alias notfound bug
  alicloud/resource_alicloud_ram_account_alias.go
  alicloud/service_alicloud_ram.go
Labels: size/XS

#1168 change ecs instance instance_charge_type modifying position
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_ots_table.go
Labels: size/M

#1173 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1169 Fix ram account alias multi testcase bug
  alicloud/resource_alicloud_ram_account_alias_test.go
Labels: size/XS

#1140 Improve ram_access_key resource use common method
  alicloud/resource_alicloud_ram_access_key.go
  alicloud/resource_alicloud_ram_access_key_test.go
  alicloud/service_alicloud_ram.go
Labels: size/XL

#1141 Improve ram_user resource use common method
  alicloud/import_alicloud_ram_user_test.go
  alicloud/resource_alicloud_ram_user.go
  alicloud/resource_alicloud_ram_user_test.go
  alicloud/service_alicloud_ram.go
Labels: size/XL

#1178 Correct the oss bucket docs
  CHANGELOG.md
  alicloud/resource_alicloud_api_gateway_group_test.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/XS

#1179 fix ram user diff bug
  alicloud/resource_alicloud_ram_user_test.go
  alicloud/service_alicloud_ram.go
Labels: size/M

#1176 add slb classic not support regions
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_server_group_test.go
  alicloud/resource_alicloud_slb_test.go
Labels: size/XS

#1180 fix api gw and network acl sweeper test error
  .gitignore
  alicloud/data_source_alicloud_common_bandwidth_package_test.go
  alicloud/data_source_alicloud_forward_entries.go
  alicloud/data_source_alicloud_forward_entries_test.go
  alicloud/data_source_alicloud_nas_protocols.go
  alicloud/data_source_alicloud_slb_acls_test.go
  alicloud/data_source_alicloud_slb_attachments_test.go
  alicloud/data_source_alicloud_slb_ca_certificates_test.go
  alicloud/data_source_alicloud_slb_listeners_test.go
  alicloud/data_source_alicloud_slb_server_certificates_test.go
  alicloud/import_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/import_alicloud_common_bandwidth_package_test.go
  alicloud/resource_alicloud_api_gateway_api_test.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  alicloud/resource_alicloud_forward_entry_test.go
  alicloud/resource_alicloud_network_acl_test.go
  alicloud/resource_alicloud_slb_attachment_test.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/M

#1182 update mongodb instance resource docment.
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/XS

#1186 remove multi test of ram_account_alias
  alicloud/resource_alicloud_ram_account_alias_test.go
Labels: size/S

#1166 Improve ram_policy resource use common method
  alicloud/import_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_policy.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/service_alicloud_ram.go
Labels: size/XL

#1158 Improve ram_login_profile resource use common method
  alicloud/import_alicloud_ram_login_profile_test.go
  alicloud/resource_alicloud_ram_login_profile.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  alicloud/service_alicloud_ram.go
Labels: size/XL

#1189 fix forward_entry multi testcase bug
  alicloud/resource_alicloud_forward_entry_test.go
Labels: size/XS

#1170 improve router_interface testcase
  alicloud/data_source_alicloud_router_interfaces.go
  alicloud/data_source_alicloud_router_interfaces_test.go
  alicloud/import_alicloud_router_interface_connection_test.go
  alicloud/import_alicloud_router_interface_test.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_router_interface_connection.go
  alicloud/resource_alicloud_router_interface_connection_test.go
  alicloud/resource_alicloud_router_interface_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/router_interfaces.html.markdown
  website/docs/r/router_interface_connection.html.markdown
Labels: documentation, size/XXL

#1185 Improve ram_role_attachment resource use common method
  alicloud/resource_alicloud_ram_role_attachment.go
  alicloud/resource_alicloud_ram_role_attachment_test.go
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_role_attachment.html.markdown
Labels: documentation, size/XL

#1195 Skip instance some testcases to avoid qouta limit
  alicloud/resource_alicloud_instance_test.go
Labels: size/XS

#1181 Improve ram_role resource use common method
  alicloud/import_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/service_alicloud_ram.go
Labels: size/L

#1172 Improve ram_user_policy_attachment resource use common method
  alicloud/resource_alicloud_ram_user_policy_attachment.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_user_policy_attachment.html.markdown
Labels: documentation, size/XL

#1197 fix router_interface dataSource testcase bug
  alicloud/data_source_alicloud_router_interfaces_test.go
Labels: size/XS

#1171 Improve ram_role_policy_attachment resource use common method
  alicloud/resource_alicloud_ram_role_policy_attachment.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_role_policy_attachment.html.markdown
Labels: documentation, size/L

#1163 Improve ram_group_policy_attachment resource use common method
  alicloud/resource_alicloud_ram_group_policy_attachment.go
  alicloud/resource_alicloud_ram_group_policy_attachment_test.go
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_group_policy_attachment.html.markdown
Labels: documentation, size/L

#1159 Improve ram_group_membership resource use common method
  alicloud/resource_alicloud_ram_group_membership.go
  alicloud/resource_alicloud_ram_group_membership_test.go
  alicloud/service_alicloud_ram.go
Labels: size/L

#1150 Improve ram_group resource use common method
  alicloud/import_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/service_alicloud_ram.go
Labels: size/L

#1198 Fix ram group import bug
  alicloud/import_alicloud_ram_group_test.go
Labels: size/XS

#1183 Improve ess_scalingrule use common method
  alicloud/data_source_alicloud_ess_scalingrules.go
  alicloud/data_source_alicloud_ess_scalingrules_test.go
  alicloud/import_alicloud_ess_scalingrule_test.go
  alicloud/resource_alicloud_ess_scalingrule.go
  alicloud/resource_alicloud_ess_scalingrule_test.go
  alicloud/service_alicloud_ess.go
  website/docs/d/ess_scaling_rules.html.markdown
  website/docs/r/ess_scaling_rule.html.markdown
Labels: documentation, size/XL

#1200 Fix ram_user sweeper
  alicloud/resource_alicloud_ram_user_test.go
Labels: size/M

#1187 Add Network Acl Attachment Resource
  alicloud/provider.go
  alicloud/resource_alicloud_network_acl.go
  alicloud/resource_alicloud_network_acl_attachment.go
  alicloud/resource_alicloud_network_acl_attachment_test.go
  alicloud/resource_alicloud_network_acl_test.go
  alicloud/service_alicloud_network_acl.go
  website/alicloud.erb
  website/docs/r/network_acl_attachment.html.markdown
Labels: dependencies, documentation, size/XL

#1209 update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#1205 Fix ram testcases name length bug.
  alicloud/import_alicloud_ram_group_test.go
  alicloud/import_alicloud_ram_login_profile_test.go
  alicloud/import_alicloud_ram_policy_test.go
  alicloud/import_alicloud_ram_role_test.go
  alicloud/import_alicloud_ram_user_test.go
  alicloud/resource_alicloud_ram_access_key_test.go
  alicloud/resource_alicloud_ram_group_membership_test.go
  alicloud/resource_alicloud_ram_group_policy_attachment_test.go
  alicloud/resource_alicloud_ram_group_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role_attachment_test.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
Labels: size/S

#1204 support set oss bucket stroage class
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/validators.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/S

#1203 fix actiontrail bug
  alicloud/common.go
  alicloud/data_source_alicloud_actiontrail.go
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/errors.go
  alicloud/import_alicloud_actiontrail_test.go
  alicloud/resource_alicloud_actiontrail.go
  alicloud/resource_alicloud_actiontrail_test.go
  alicloud/service_alicloud_actiontrail.go
  alicloud/validators.go
Labels: size/XL

#1196 Improve ess_lifecyclehook resource use common method
  alicloud/import_alicloud_ess_lifecycle_hook_test.go
  alicloud/resource_alicloud_ess_lifecyclehook.go
  alicloud/resource_alicloud_ess_lifecyclehook_test.go
  alicloud/service_alicloud_ess.go
Labels: size/XL

#1210 support oss bucket encryption configuration.
  alicloud/common.go
  alicloud/data_source_alicloud_oss_bucket_objects.go
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_oss_buckets_test.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/CHANGELOG.md
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/bucket.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/const.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/option.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/upload.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/sample.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/sample/bucket_encryption.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/sample/bucket_lifecycle.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/sample/copy_object.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/sample/object_tagging.go
  vendor/vendor.json
  website/docs/d/oss_bucket_objects.html.markdown
  website/docs/d/oss_buckets.html.markdown
  website/docs/r/oss_bucket.html.markdown
Labels: dependencies, documentation, size/XL

#1211 fix nat_gateway and network_interface testcase bug
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_network_interface_attachment_test.go
Labels: size/XS

#1206 Improve cen_instances use common method.
  alicloud/data_source_alicloud_cen_instances.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/import_alicloud_cen_instance_test.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cen.go
  website/docs/d/cen_instances.html.markdown
Labels: documentation, size/XL

#1213 support oss bucket tags
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_oss_buckets_test.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/CHANGELOG.md
  vendor/github.com/aliyun/aliyun-oss-go-sdk/README-CN.md
  vendor/github.com/aliyun/aliyun-oss-go-sdk/README.md
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/const.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/option.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/type.go
  vendor/vendor.json
  website/docs/d/oss_buckets.html.markdown
  website/docs/r/oss_bucket.html.markdown
Labels: dependencies, documentation, size/XL

#1208 Add Network Acl Entries Resource
  alicloud/common.go
  alicloud/provider.go
  alicloud/resource_alicloud_network_acl.go
  alicloud/resource_alicloud_network_acl_attachment.go
  alicloud/resource_alicloud_network_acl_attachment_test.go
  alicloud/resource_alicloud_network_acl_entries.go
  alicloud/resource_alicloud_network_acl_entries_test.go
  alicloud/resource_alicloud_network_acl_test.go
  alicloud/service_alicloud_network_acl.go
  alicloud/service_alicloud_vpc.go
  website/alicloud.erb
  website/docs/r/network_acl_entries.html.markdown
Labels: documentation, size/XXL

#1214 update oss buket encryption configuration.
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_oss_buckets_test.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
  website/docs/d/oss_buckets.html.markdown
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/S

#1192 Improve ess_scalinggroup use common method
  alicloud/data_source_alicloud_ess_scalinggroups.go
  alicloud/data_source_alicloud_ess_scalinggroups_test.go
  alicloud/import_alicloud_ess_scalinggroup_test.go
  alicloud/resource_alicloud_ess_attachment.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  alicloud/service_alicloud_ess.go
  website/docs/d/ess_scaling_groups.html.markdown
  website/docs/r/ess_scaling_group.html.markdown
Labels: documentation, size/XXL

#1215 update instance dataSource doc
  alicloud/data_source_alicloud_fc_services_test.go
  website/docs/d/instances.html.markdown
Labels: documentation, size/XS

#982 Update Nat Gateway PrePaid
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_nat_gateway_test.go
  website/docs/r/nat_gateway.html.markdown
Labels: documentation, size/M

#1109 improve route_table testcase
  alicloud/data_source_alicloud_route_entries.go
  alicloud/data_source_alicloud_route_entries_test.go
  alicloud/data_source_alicloud_route_tables.go
  alicloud/data_source_alicloud_route_tables_test.go
  alicloud/import_alicloud_route_entry_test.go
  alicloud/import_alicloud_route_table_attachment_test.go
  alicloud/import_alicloud_route_table_test.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_route_entry.go
  alicloud/resource_alicloud_route_entry_test.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_route_table_attachment.go
  alicloud/resource_alicloud_route_table_attachment_test.go
  alicloud/resource_alicloud_route_table_test.go
  alicloud/service_alicloud_cen.go
  alicloud/service_alicloud_route_table.go
  alicloud/service_alicloud_vpc.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/allocate_eip_address.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_customer_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_i_pv6_translator.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_router_interface.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_vpn_connection.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_vpn_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_vpn_pbr_route_entry.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/create_vpn_route_entry.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/describe_customer_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/describe_ssl_vpn_client_cert.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/describe_v_switch_attributes.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/describe_vpn_connection.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/describe_vpn_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/modify_common_bandwidth_package_pay_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/modify_customer_gateway_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/modify_ssl_vpn_server.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/modify_vpn_connection_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/modify_vpn_gateway_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_associated_cen.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_cbn_grant_rule.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_customer_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_ike_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_ipsec_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_ipv6_translator.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_physical_connection_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_route_table.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_router_table_list_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_ssl_vpn_client_cert_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_ssl_vpn_server.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_v_switch.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_virtual_border_router_for_physical_connection_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_vpn_connection.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_vpn_gateway.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_vpn_pbr_route_entry.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/vpc/struct_vpn_route_entry.go
  vendor/vendor.json
  website/docs/d/route_tables.html.markdown
  website/docs/r/route_table.html.markdown
  website/docs/r/route_table_attachment.html.markdown
Labels: dependencies, documentation, size/XXL

#1224 update changeLog
  CHANGELOG.md
  alicloud/resource_alicloud_route_entry_test.go
Labels: size/XS

#1229 improve vpn_gateway testcase
  alicloud/data_source_alicloud_vpn_gateways.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/import_alicloud_vpn_gateway_test.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/service_alicloud_vpn_gateway.go
  website/docs/d/vpn_gateways.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/XL

#1231 fix reset account_password don't work
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  alicloud/service_alicloud_mongodb.go
Labels: size/M

#1184 fix(nas): fix testcase errors
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_nas_access_groups_test.go
  alicloud/data_source_alicloud_nas_access_rules_test.go
  alicloud/data_source_alicloud_nas_file_systems.go
  alicloud/data_source_alicloud_nas_file_systems_test.go
  alicloud/data_source_alicloud_nas_mount_targets_test.go
  alicloud/import_alicloud_nas_file_system_test.go
  alicloud/import_alicloud_nas_mount_target_test.go
  alicloud/resource_alicloud_nas_access_group.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_access_rule.go
  alicloud/resource_alicloud_nas_access_rule_test.go
  alicloud/resource_alicloud_nas_file_system.go
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/resource_alicloud_nas_mount_target.go
  alicloud/resource_alicloud_nas_mount_target_test.go
  alicloud/service_alicloud_nas.go
  examples/vpn/main.tf
  website/docs/d/nas_access_groups.html.markdown
  website/docs/d/nas_access_rules.html.markdown
  website/docs/d/nas_file_systems.html.markdown
  website/docs/d/nas_mount_targets.html.markdown
  website/docs/r/nas_access_group.html.markdown
  website/docs/r/nas_access_rule.html.markdown
  website/docs/r/nas_file_system.html.markdown
  website/docs/r/nas_mount_target.html.markdown
Labels: documentation, size/XXL

#1233 fix slb_ca_certificate err ServiceIsConfiguring
  alicloud/resource_alicloud_slb_ca_certificate.go
Labels: size/XS

#1234 Improve ess_scalingconfigurations datasource use common method
  alicloud/data_source_alicloud_ess_scalingconfigurations.go
  alicloud/data_source_alicloud_ess_scalingconfigurations_test.go
  website/docs/d/ess_scaling_configurations.html.markdown
Labels: documentation, size/L

#1236 fix(nas): fix unittest bugs
  alicloud/import_alicloud_nas_access_group_test.go
  alicloud/import_alicloud_nas_access_rule_test.go
  alicloud/import_alicloud_nas_file_system_test.go
  alicloud/import_alicloud_nas_mount_target_test.go
Labels: size/XS
