Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-03, with the labels that each got.

#808 Update changelog
  CHANGELOG.md
Labels: size/XS

#809 fix import managed kubernetes test
  alicloud/import_alicloud_cs_managed_kubernetes_test.go
Labels: size/XS

#810 update changelog
  CHANGELOG.md
Labels: size/XS

#812 fix rds readonly instance name update issue
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
Labels: size/XS

#813 Update Changelog
  CHANGELOG.md
Labels: size/XS

#815 fix volume_tags diff bug when setting tags by alicloud_disk
  CHANGELOG.md
  alicloud/resource_alicloud_instance.go
  alicloud/tags.go
  examples/cen/main.tf
  examples/kvstore/main.tf
  examples/rds/main.tf
  examples/rds/variables.tf
Labels: size/S

#816 fix volume_tags diff bug when running testcases
  CHANGELOG.md
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#822 bugfix: create vpn gateway got "UnnecessarySslConnection" error when …
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/XS

#817 feat(nas): add resourcee access group
  alicloud/connectivity/config.go
  alicloud/provider.go
  alicloud/resource_alicloud_nas_access_group.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_file_system.go
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/service_alicloud_nas.go
  examples/nas-access-group/README.md
  examples/nas-access-group/main.tf
  examples/nas-access-group/outputs.tf
  examples/nas-access-group/variables.tf
  examples/nas-file-system/README.md
  examples/nas-file-system/main.tf
  examples/nas-file-system/outputs.tf
  examples/nas-file-system/variables.tf
  examples/nas-filesystem/outputs.tf
  website/alicloud.erb
  website/docs/r/nas_access_group.html.markdown
  website/docs/r/nas_file_system.html.markdown
Labels: documentation, size/XL

#824 Improve nas resource docs
  CHANGELOG.md
  alicloud/resource_alicloud_nas_access_group.go
  website/docs/r/nas_access_group.html.markdown
  website/docs/r/nas_file_system.html.markdown
Labels: documentation, size/S

#825 Fix nas docs bug
  CHANGELOG.md
  website/alicloud.erb
Labels: documentation, size/XS

#828 change bool to *bool in parameters of k8s clusters
  alicloud/data_source_alicloud_cs_kubernetes_clusters.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/vendor.json
Labels: dependencies, size/M

#829 new resource cdn_domain_config
  CHANGELOG.md
  alicloud/provider.go
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/resource_alicloud_cdn_domain_config_test.go
  alicloud/resource_alicloud_cdn_domain_new.go
  alicloud/service_alicloud_cdn.go
  website/alicloud.erb
  website/docs/r/cdn_domain_config.html.markdown
Labels: documentation, size/XL

#830 Deprecate the resource alicloud_cdn_domain
  CHANGELOG.md
  alicloud/resource_alicloud_cdn_domain.go
  alicloud/resource_alicloud_cdn_domain_config.go
  alicloud/service_alicloud_cdn.go
  alicloud/service_alicloud_ess.go
  website/docs/r/cdn_domain.html.markdown
  website/docs/r/cdn_domain_config.html.markdown
  website/docs/r/cdn_domain_new.html.markdown
Labels: documentation, size/S

#833 fix cdn service func WaitForCdnDomain
  CHANGELOG.md
  alicloud/service_alicloud_cdn.go
Labels: size/XS

#831 deal with the error message in cen route entry
  alicloud/errors.go
  alicloud/resource_alicloud_cen_route_entry.go
Labels: size/XS

#826 feat(nas): add resource access rules
  alicloud/provider.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_access_rule.go
  alicloud/resource_alicloud_nas_access_rule_test.go
  alicloud/service_alicloud_nas.go
  examples/nas-access-rule/README.md
  examples/nas-access-rule/main.tf
  examples/nas-access-rule/outputs.tf
  website/alicloud.erb
  website/docs/index.html.markdown
  website/docs/r/nas_access_rule.html.markdown
Labels: documentation, size/XL

#834 Bugfix: destroying alicloud_ess_attachment timeout.
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/service_alicloud_ess.go
Labels: size/XS

#836 RDS auto-renewal option
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#838 Add version notes in some docs
  CHANGELOG.md
  alicloud/import_alicloud_cr_namespace_test.go
  alicloud/resource_alicloud_cr_namespace.go
  alicloud/resource_alicloud_cr_namespace_test.go
  website/docs/d/cs_kubernetes_clusters.html.markdown
  website/docs/r/cr_namespace.html.markdown
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/S

#839 fix kubernetes data resource ut and import error
  alicloud/data_source_alicloud_cs_kubernetes_clusters.go
  vendor/github.com/denverdino/aliyungo/cs/clusters.go
  vendor/vendor.json
Labels: dependencies, documentation, size/XS

#840 Improve Eip and mns testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_mns_topic_subscriptions_test.go
  alicloud/data_source_alicloud_mns_topics_test.go
  alicloud/import_alicloud_ram_group_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_eip_test.go
Labels: size/S

#842 Improve vpn_gateway testcases and some sweeper test
  CHANGELOG.md
  alicloud/data_source_alicloud_vpn_connections_test.go
  alicloud/data_source_alicloud_vpn_gateways_test.go
  alicloud/resource_alicloud_cr_namespace_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_nas_access_rule_test.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vpn_connection_test.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/M

#843 Add ssl_vpn_server and ssl_vpn_client_cert sweeper test
  CHANGELOG.md
  alicloud/data_source_alicloud_vswitches.go
  alicloud/resource_alicloud_ssl_vpn_client_cert_test.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vpn_gateway_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/L

#844 fix kms sweeper test deleting bug
  CHANGELOG.md
  alicloud/resource_alicloud_kms_key_test.go
Labels: size/XS

#847 fix log store and config sweeper test deleting bug
  CHANGELOG.md
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_logtail_config_test.go
Labels: size/XS

#848 Fix deleting dns record InternalError bug
  CHANGELOG.md
  alicloud/resource_alicloud_dns_record.go
Labels: size/XS

#851 Add using note for spot instance
  CHANGELOG.md
  alicloud/resource_alicloud_instance_test.go
  alicloud/service_alicloud_nas.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#852 fix(nas): fix resource mount target tests
  alicloud/connectivity/regions.go
  alicloud/import_alicloud_nas_mount_target_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_nas_mount_target_test.go
  website/docs/r/nas_mount_target.html.markdown
Labels: documentation, size/XL

#850 Add Load Balancer PrePaid
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/M

#853 Add drds instance docs
  CHANGELOG.md
  website/alicloud.erb
  website/docs/r/nas_mount_target.html.markdown
Labels: documentation, size/XS

#855 Add client token for vpn services
  CHANGELOG.md
  alicloud/common.go
  alicloud/resource_alicloud_cen_bandwidth_package.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_drds_instance.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_havip.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/resource_alicloud_nas_mount_target_test.go
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_route_entry.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_router_interface.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_ssl_vpn_client_cert.go
  alicloud/resource_alicloud_ssl_vpn_server.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpn_connection.go
  alicloud/resource_alicloud_vpn_customer_gateway.go
  alicloud/resource_alicloud_vswitch.go
Labels: size/L

#856 feat(nas): add datasource access groups
  alicloud/data_source_alicloud_nas_access_groups.go
  alicloud/data_source_alicloud_nas_access_groups_test.go
  alicloud/import_alicloud_nas_access_group_test.go
  alicloud/import_alicloud_nas_access_rule_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_nas_access_group_test.go
  alicloud/resource_alicloud_nas_access_rule_test.go
  website/alicloud.erb
  website/docs/d/nas_access_groups.html.markdown
Labels: documentation, size/XL

#845 add managed k8s data source
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters.go
  alicloud/data_source_alicloud_cs_managed_kubernetes_clusters_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cs_managed_kubernetes_clusters.html.markdown
Labels: documentation, size/XL

#860 feat(nas): add datasource access rules
  alicloud/data_source_alicloud_nas_access_rules.go
  alicloud/data_source_alicloud_nas_access_rules_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/nas_access_rules.html.markdown
Labels: documentation, size/XL

#863 Improve drds instances testcases
  alicloud/data_source_alicloud_drds_instances_test.go
  alicloud/import_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  website/docs/r/drds_instance.html.markdown
Labels: documentation, size/L

#859 add dns test case
  CHANGELOG.md
  alicloud/extension_pvtz.go
  alicloud/import_alicloud_dns_record_test.go
  alicloud/import_alicloud_dns_test.go
  alicloud/resource_alicloud_dns.go
  alicloud/resource_alicloud_dns_group.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/validators.go
  website/docs/r/dns_record.html.markdown
Labels: dependencies, documentation, size/XL

#865 fix elastic search sweeper test bug
  alicloud/resource_alicloud_elasticsearch_instance_test.go
Labels: size/XS

#866 reback the lossing datasource
  alicloud/provider.go
Labels: size/M

#870 fix creating slb bug
  alicloud/data_source_alicloud_cr_namespaces.go
  alicloud/data_source_alicloud_cr_namespaces_test.go
  alicloud/resource_alicloud_cr_repo_test.go
  alicloud/resource_alicloud_slb.go
  alicloud/service_alicloud_cr.go
Labels: size/XS

#868 add cr_repos data source
  alicloud/data_source_alicloud_cr_namespaces_test.go
  alicloud/data_source_alicloud_cr_repos.go
  alicloud/data_source_alicloud_cr_repos_test.go
  alicloud/provider.go
  alicloud/service_alicloud_cr.go
  website/alicloud.erb
  website/docs/d/cr_namespaces.html.markdown
  website/docs/d/cr_repos.html.markdown
  website/docs/r/cr_namespace.html.markdown
  website/docs/r/cr_repo.html.markdown
Labels: documentation, size/XL

#864 feat(nas): add datasource filesystems
  alicloud/data_source_alicloud_cr_repos.go
  alicloud/data_source_alicloud_cr_repos_test.go
  alicloud/data_source_alicloud_nas_file_systems.go
  alicloud/data_source_alicloud_nas_file_systems_test.go
  alicloud/data_source_alicloud_nas_mount_targets.go
  alicloud/data_source_alicloud_nas_mount_targets_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_nas_file_system_test.go
  alicloud/resource_alicloud_nas_mount_target_test.go
  examples/nas-access-group/main.tf
  examples/nas-access-group/variables.tf
  examples/nas-access-rule/main.tf
  examples/nas-access-rule/outputs.tf
  examples/nas-file-system/main.tf
  examples/nas-mount-target/main.tf
  examples/nas-mount-target/outputs.tf
  website/alicloud.erb
  website/docs/d/nas_access_rules.html.markdown
  website/docs/d/nas_file_systems.html.markdown
  website/docs/d/nas_mount_targets.html.markdown
Labels: documentation, size/XXL

#871 Fix dns notfound bug
  CHANGELOG.md
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/service_alicloud_dns.go
Labels: size/XS

#872 Fix nas mount target notfound bug and improve nas datasource's testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_nas_file_systems_test.go
  alicloud/data_source_alicloud_nas_mount_targets_test.go
  alicloud/errors.go
  alicloud/resource_alicloud_nas_mount_target.go
  alicloud/service_alicloud_nas.go
Labels: size/L

#873 Add waiting method to ensure the security group status is ok
  CHANGELOG.md
  alicloud/common.go
  alicloud/errors.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_security_group_test.go
  alicloud/service_alicloud_ecs.go
Labels: size/L

#876 Make dns resource code more standard
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_domains.go
  alicloud/data_source_alicloud_dns_groups.go
  alicloud/data_source_alicloud_dns_records.go
  alicloud/data_source_alicloud_dns_records_test.go
  alicloud/resource_alicloud_dns.go
  alicloud/resource_alicloud_dns_group.go
  alicloud/resource_alicloud_dns_record.go
  alicloud/resource_alicloud_slb_test.go
  alicloud/service_alicloud_dns.go
Labels: size/M

#877 Add account pre-check for common bandwidth package to avoid known error
  CHANGELOG.md
  alicloud/import_alicloud_common_bandwidth_package_attachment_test.go
  alicloud/import_alicloud_common_bandwidth_package_test.go
  alicloud/resource_alicloud_common_bandwidth_package_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
Labels: size/L

#858 Add a new resource action trail
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/errors.go
  alicloud/import_alicloud_actiontrail_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_actiontrail.go
  alicloud/resource_alicloud_actiontrail_test.go
  alicloud/service_alicloud_actiontrail.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/create_trail.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/delete_trail.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/describe_trails.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/get_trail_status.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/lookup_events.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/start_logging.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/stop_logging.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_events.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_region.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_region_item.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_trail_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/struct_trail_list_item.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/actiontrail/update_trail.go
  vendor/vendor.json
  website/alicloud.erb
  website/docs/index.html.markdown
  website/docs/r/actiontrail.html.markdown
Labels: dependencies, documentation, size/XXL

#878 Improve actiontrail docs
  CHANGELOG.md
  alicloud/import_alicloud_actiontrail_test.go
  alicloud/resource_alicloud_actiontrail_test.go
  website/docs/r/actiontrail.html.markdown
Labels: documentation, size/XS

#880 fix rds instance parameter test case issue
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#879 Make db_connection resource code more standard
  CHANGELOG.md
  alicloud/errors.go
  alicloud/import_alicloud_db_connection_test.go
  alicloud/resource_alicloud_db_connection.go
  alicloud/resource_alicloud_db_connection_test.go
  alicloud/service_alicloud_ecs.go
  alicloud/service_alicloud_rds.go
Labels: size/XL

#875 add new resource cas
  alicloud/connectivity/client.go
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_cas_certificates.go
  alicloud/data_source_alicloud_cas_certificates_test.go
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_cas_certificate.go
  alicloud/resource_alicloud_cas_certificate_test.go
  alicloud/service_alicloud_cas.go
  alicloud/validators.go
  examples/cas/main.tf
  examples/cas/outputs.tf
  examples/cas/test.crt
  examples/cas/test.key
  examples/cas/variables.tf
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/create_user_certificate.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/delete_user_certificate.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/describe_user_certificate_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/struct_certificate_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/struct_order.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cas/struct_order_list.go
  vendor/vendor.json
  website/alicloud.erb
  website/docs/d/cas_certificates.html.markdown
  website/docs/index.html.markdown
  website/docs/r/cas_certificate.html.markdown
Labels: dependencies, documentation, size/XXL

#874 improve disk dataSource testcase
  alicloud/data_source_alicloud_disks.go
  alicloud/data_source_alicloud_disks_test.go
Labels: size/XL

#882 for ca certificate test
  alicloud/data_source_alicloud_cas_certificates_test.go
  alicloud/resource_alicloud_cas_certificate_test.go
Labels: size/M

#885 Fix link to BatchSetCdnDomainConfig document
  website/docs/r/cdn_domain_config.html.markdown
Labels: documentation, size/XS

#883 Remove ModifySecurityGroupPolicy waiting and backend has fixed it
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_zones.go
  alicloud/errors.go
  alicloud/resource_alicloud_cms_alarm_test.go
  alicloud/resource_alicloud_security_group.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#887 Slb Add Master Zone Id
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_test.go
  website/docs/r/slb.html.markdown
Labels: documentation, size/S

#889 fix slb_internet_enabled default value
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS

#892 fix(nas): fix mount target deletion bugs
  alicloud/errors.go
  alicloud/resource_alicloud_nas_mount_target.go
  alicloud/service_alicloud_nas.go
Labels: size/XS

#891 add a new datasource actiontrails
  CHANGELOG.md
  alicloud/data_source_alicloud_actiontrail.go
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/actiontrails.html.markdown
Labels: documentation, size/XL

#894 Add for alicloud_zones and support retrieving slb slave zones
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_actiontrail.go
  alicloud/data_source_alicloud_actiontrail_test.go
  alicloud/data_source_alicloud_zones.go
  alicloud/data_source_alicloud_zones_test.go
  alicloud/resource_alicloud_slb_test.go
  website/alicloud.erb
  website/docs/d/actiontrails.html.markdown
  website/docs/d/zones.html.markdown
  website/docs/r/fc_function.html.markdown
  website/docs/r/fc_service.html.markdown
  website/docs/r/fc_trigger.html.markdown
  website/docs/r/slb.html.markdown
Labels: documentation, size/L

#896 add region skip for container registry
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_cr_namespaces_test.go
  alicloud/data_source_alicloud_cr_repos_test.go
  alicloud/import_alicloud_cr_namespace_test.go
  alicloud/import_alicloud_cr_repo_test.go
  alicloud/resource_alicloud_cr_namespace_test.go
  alicloud/resource_alicloud_cr_repo_test.go
Labels: size/XS

#898 Sort slb slave zone ids to avoid needless error
  CHANGELOG.md
  alicloud/data_source_alicloud_actiontrail.go
  alicloud/data_source_alicloud_cr_namespaces_test.go
  alicloud/data_source_alicloud_cr_repos_test.go
  alicloud/data_source_alicloud_zones.go
  alicloud/import_alicloud_cr_namespace_test.go
  alicloud/import_alicloud_cr_repo_test.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/XS

#895 Modify ram group's name's ForceNew to true
  CHANGELOG.md
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_group_test.go
Labels: size/S

#899 fix cas_certificate sweeper test bug
  CHANGELOG.md
  alicloud/resource_alicloud_cas_certificate_test.go
Labels: size/XS

#897 Add Common Bandwidth Packages Datasource
  alicloud/data_source_alicloud_common_bandwidth_package_test.go
  alicloud/data_source_alicloud_common_bandwidth_packages.go
  alicloud/provider.go
  alicloud/service_alicloud_vpc.go
  website/alicloud.erb
  website/docs/d/common_bandwidth_packages.html.markdown
Labels: documentation, size/XL

#903 switch the region id if needed
  alicloud/resource_alicloud_cen_bandwidth_package.go
  website/docs/r/cen_bandwidth_package.html.markdown
Labels: documentation, size/XS

#886 improve disk and attachment resource testcase
  alicloud/import_alicloud_disk_test.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/resource_alicloud_disk_attachment_test.go
  alicloud/resource_alicloud_disk_test.go
  alicloud/service_alicloud_ecs.go
Labels: size/XL

#902 support kv-store auto renewal option
  alicloud/resource_alicloud_kvstore_instance.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/S

#906 add dns and dns_group test sweeper
  alicloud/resource_alicloud_disk_test.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/resource_alicloud_dns_record_test.go
  alicloud/resource_alicloud_dns_test.go
Labels: size/L

#904 fc_function add new schema environment_variables
  CHANGELOG.md
  alicloud/data_source_alicloud_fc_functions.go
  alicloud/data_source_alicloud_fc_functions_test.go
  alicloud/resource_alicloud_fc_function.go
  alicloud/resource_alicloud_fc_function_test.go
  alicloud/service_alicloud_fc.go
Labels: size/M

#905 Add Route Tables Datasource
  alicloud/data_source_alicloud_route_tables.go
  alicloud/data_source_alicloud_route_tables_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/route_tables.html.markdown
Labels: documentation, size/XL

#907 Update changelog
  CHANGELOG.md
Labels: size/XS

#901 return after the instance deleted when destroy the resource cen instance
  alicloud/resource_alicloud_cen_instance.go
  alicloud/service_alicloud_cen.go
Labels: size/S

#908 Fix cen instance deleting bug
  CHANGELOG.md
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_disk_attachment_test.go
  alicloud/resource_alicloud_dns_group_test.go
  alicloud/resource_alicloud_dns_test.go
  alicloud/service_alicloud_cen.go
Labels: size/S

#909 Add wait method for cen instance
  CHANGELOG.md
  alicloud/common.go
  alicloud/errors.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/service_alicloud_cen.go
Labels: size/M

#910 Add wait method for disk and disk attachment
  CHANGELOG.md
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_attachment.go
  alicloud/service_alicloud_cen.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#911 Feature/route table data source
  alicloud/data_source_alicloud_route_tables_test.go
Labels: documentation, size/XS

#913 add new schema environment_variables to fc_function.html.markdown
  CHANGELOG.md
  website/docs/d/fc_functions.html.markdown
  website/docs/r/fc_function.html.markdown
Labels: documentation, size/XS

#915 Add Route Entries Datasource​
  alicloud/data_source_alicloud_route_entries.go
  alicloud/data_source_alicloud_route_entries_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/route_entries.html.markdown
Labels: documentation, size/XXL

#914 add docs about prerequisites for cs and cr
  website/docs/r/cr_repo.html.markdown
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS

#900 set userId as d.Id() rather than userName
  CHANGELOG.md
  alicloud/resource_alicloud_ram_user.go
  alicloud/resource_alicloud_ram_user_test.go
  alicloud/service_alicloud_ram.go
  website/docs/d/ram_users.html.markdown
  website/docs/r/ram_user.html.markdown
Labels: documentation, size/M

#916 Resource snat entry update id and support import
  CHANGELOG.md
  alicloud/data_source_alicloud_route_tables_test.go
  alicloud/import_alicloud_snat_entry_test.go
  alicloud/resource_alicloud_snat.go
  alicloud/resource_alicloud_snat_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/r/snat.html.markdown
Labels: documentation, size/L

#918 Add Nat Gateways Datasource
  alicloud/data_source_alicloud_nat_gateways.go
  alicloud/data_source_alicloud_nat_gateways_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/nat_gateways.html.markdown
Labels: documentation, size/XL

#917 Skipping bandwidth package related test for international site account
  alicloud/data_source_alicloud_cen_bandwidth_limits_test.go
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/import_alicloud_cen_bandwidth_limit_test.go
  alicloud/import_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/import_alicloud_cen_bandwidth_package_test.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_attachment_test.go
  alicloud/resource_alicloud_cen_bandwidth_package_test.go
Labels: size/XS

#919 fix default pod_cidr in k8s docs
  website/docs/r/cs_kubernetes.html.markdown
Labels: documentation, size/XS

#920 Add Snat Entries Datasource
  alicloud/data_source_alicloud_snat_entries.go
  alicloud/data_source_alicloud_snat_entries_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/snat_entries.html.markdown
Labels: documentation, size/XL

#921 Fix the parameter bug when actiontrail is created
  CHANGELOG.md
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_actiontrail.go
  website/docs/r/actiontrail.html.markdown
Labels: documentation, size/M

#922 Add Forward Entries Datasource
  CHANGELOG.md
  alicloud/data_source_alicloud_forward_entries.go
  alicloud/data_source_alicloud_forward_entries_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/common_bandwidth_packages.html.markdown
  website/docs/d/forward_entries.html.markdown
  website/docs/d/nat_gateways.html.markdown
  website/docs/d/route_entries.html.markdown
  website/docs/d/route_tables.html.markdown
  website/docs/d/snat_entries.html.markdown
Labels: documentation, size/XL

#926 cr_repos fix docs link error
  website/alicloud.erb
Labels: documentation, size/XS

#925 add RDS security group support
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#928 Improve pvtz resource datasource testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_pvtz_zone_records.go
  alicloud/data_source_alicloud_pvtz_zone_records_test.go
  alicloud/data_source_alicloud_pvtz_zones.go
  alicloud/data_source_alicloud_pvtz_zones_test.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
  alicloud/resource_alicloud_pvtz_zone_test.go
  alicloud/service_alicloud_pvtz.go
Labels: size/XL

#929 modify ram user sweep
  CHANGELOG.md
  alicloud/resource_alicloud_ram_user_test.go
Labels: size/XS

#924 added DB instance monitor provider
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#932 testSweepCRNamespace skip not supported region
  alicloud/resource_alicloud_cr_namespace_test.go
Labels: size/XS

#933 Improve pvtz_zone_record create record
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/S

#934 Improve pvtz_zone_record WrapError
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/XS

#931 refine retry logic of tablestore
  alicloud/errors.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/service_alicloud_ots.go
Labels: size/S

#937 Deprecate bucket logging_isenabled and fix referer_config diff bug
  CHANGELOG.md
  alicloud/resource_alicloud_oss_bucket.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/M

#939 security_groups vpcs vswitches add ids names
  CHANGELOG.md
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/data_source_alicloud_vswitches_test.go
Labels: size/XL

#942 dns_records add urls
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_records.go
  alicloud/data_source_alicloud_dns_records_test.go
Labels: size/S

#941 modify stop instance timeout to 5min
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#857 resource cen instance grant
  alicloud/common.go
  alicloud/errors.go
  alicloud/import_alicloud_cen_instance_grant_test.go
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/resource_alicloud_cen_instance_grant.go
  alicloud/resource_alicloud_cen_instance_grant_test.go
  alicloud/service_alicloud_cen.go
  alicloud/service_alicloud_vpc.go
  website/alicloud.erb
  website/docs/r/cen_instance_grant.html.markdown
Labels: documentation, size/XL

#943 Add missing outputs for datasource dns_records, security groups, vpcs and vswitches
  CHANGELOG.md
  website/docs/d/dns_records.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vswitches.html.markdown
  website/docs/d/zones.html.markdown
Labels: documentation, size/S

#947 update mongodb instance test case multiAZ
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_mongodb_instance_test.go
Labels: size/XS

#949 prepaid instance support modify attribute
  alicloud/resource_alicloud_instance.go
Labels: documentation, size/XS

#955 Fix drds instance sweeper test bug
  CHANGELOG.md
  alicloud/resource_alicloud_dns_test.go
  alicloud/resource_alicloud_drds_instance_test.go
  website/docs/r/actiontrail.html.markdown
  website/docs/r/db_read_write_splitting_connection.html.markdown
  website/docs/r/db_readonly_instance.html.markdown
  website/docs/r/mns_topic_subscription.html.markdown
  website/docs/r/security_group_rule.html.markdown
  website/docs/r/slb_listener.html.markdown
  website/docs/r/vpn_connection.html.markdown
Labels: documentation, size/M
