Repository aliyun/terraform-provider-alicloud, pull requests merged in 2019-01, with the labels that each got.

#602 Bugfix/kvstore charge type
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/XS

#616 Fix ots instance description force new bug
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_instance.go
  alicloud/resource_alicloud_ots_instance.go
  website/docs/r/ots_instance.html.markdown
Labels: documentation, size/XS

#617 Support oss client https
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#618 Support mns client https
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_mns_queues_test.go
  alicloud/data_source_alicloud_mns_topic_subscriptions_test.go
  alicloud/data_source_alicloud_mns_topics_test.go
  alicloud/import_alicloud_mns_queue_test.go
  alicloud/import_alicloud_mns_topic_subscription_test.go
  alicloud/import_alicloud_mns_topic_test.go
  alicloud/resource_alicloud_mns_queue_test.go
  alicloud/resource_alicloud_mns_topic_subscription_test.go
  alicloud/resource_alicloud_mns_topic_test.go
Labels: size/L

#619 Support https for services client using official sdk
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/service_alicloud_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/acs_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/common_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/roa_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/rpc_request.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests/types.go
  vendor/vendor.json
Labels: dependencies, size/XL

#623 Support https for log client
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#624 Fix api gateway groups filter bug
  CHANGELOG.md
  alicloud/data_source_alicloud_api_gateway_groups.go
Labels: size/XS

#625 support name_prefix to multiAZ Kubernetes Cluster
  alicloud/resource_alicloud_cs_kubernetes.go
Labels: size/XS

#627 Update changelog
  CHANGELOG.md
Labels: size/XS

#630 Remove ots https schema because of in some region only supports http
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#631 Update changelog
  CHANGELOG.md
Labels: size/XS

#632 Improve slb instance docs
  CHANGELOG.md
  website/docs/r/slb.html.markdown
Labels: documentation, size/XS

#633 Fix api gateway deleteing app bug
  CHANGELOG.md
  alicloud/resource_alicloud_api_gateway_app_test.go
Labels: size/XS

#635 Improve db_account testcase and its docs
  CHANGELOG.md
  alicloud/import_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_account_test.go
  website/docs/r/db_account.html.markdown
Labels: documentation, size/S

#636 Fix typo in docs
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XS

#639 Improve pvtz_zone testcase by using rand
  CHANGELOG.md
  alicloud/data_source_alicloud_pvtz_zone_records_test.go
  alicloud/data_source_alicloud_pvtz_zones_test.go
  alicloud/import_alicloud_pvtz_zone_attachment_test.go
  alicloud/import_alicloud_pvtz_zone_record_test.go
  alicloud/import_alicloud_pvtz_zone_test.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  alicloud/resource_alicloud_pvtz_zone_record_test.go
  alicloud/resource_alicloud_pvtz_zone_test.go
Labels: size/XL

#642 Fix pvtz throttling user bug and add WrafError
  CHANGELOG.md
  alicloud/common.go
  alicloud/errors.go
  alicloud/extension_pvtz.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/service_alicloud_pvtz.go
Labels: size/M

#643 Support cs client setting customer endpoint
  CHANGELOG.md
  alicloud/connectivity/client.go
  vendor/github.com/denverdino/aliyungo/cs/client.go
  vendor/vendor.json
Labels: dependencies, size/XS

#638 support for zero node clusters in swarm container service
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_cs_swarm_test.go
Labels: size/L

#644 Fix ess group describing error
  CHANGELOG.md
  alicloud/service_alicloud_ess.go
Labels: size/XS

#649 Reback image filter to meet many non-ecs testcase
  CHANGELOG.md
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#641 do not poll nodes when k8s cluster is stable
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/XS

#652 Support customer endpoints in the provider
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#653 Offline drds resource from website results from drds does not support idempotent
  CHANGELOG.md
  alicloud/provider.go
  website/alicloud.erb
Labels: documentation, size/XS

#654 Improve route entry retry strategy to avoid concurrence issue
  CHANGELOG.md
  alicloud/resource_alicloud_route_entry.go
Labels: size/XS

#658 Fix cs cluster not found error and improve its testcase
  CHANGELOG.md
  alicloud/import_alicloud_cs_application_test.go
  alicloud/import_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_cs_application.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_cs_swarm_test.go
Labels: size/XL

#659 Fix ecs and ess tags read bug with ignore system tag
  CHANGELOG.md
  alicloud/tags.go
  website/docs/r/ess_scaling_configuration.html.markdown
  website/docs/r/instance.html.markdown
Labels: documentation, size/S

#655 BugFix: rename cen instance to avoid mistake query.
  alicloud/data_source_alicloud_cen_bandwidth_packages_test.go
  alicloud/data_source_alicloud_cen_instances_test.go
Labels: size/M

#660 Fix pvtz zone attaching vpc system busy error
  CHANGELOG.md
  alicloud/errors.go
  alicloud/extension_pvtz.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/XS

#663 Improve pvtz attachment test updating case
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
Labels: size/XS

#665 Fix cs_kubernetes setting int value error
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/M

#666 Fix deleting log project requestTimeout error
  CHANGELOG.md
  alicloud/data_source_alicloud_pvtz_zone_records.go
  alicloud/data_source_alicloud_pvtz_zones.go
  alicloud/errors.go
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_record.go
Labels: size/S

#667 Fix slb OperationFailed.TokenIsProcessing error
  CHANGELOG.md
  alicloud/common.go
  alicloud/errors.go
  alicloud/resource_alicloud_slb.go
Labels: size/S

#668 check vswitch id when creating instance
  alicloud/resource_alicloud_instance.go
  examples/ecs/main.tf
  examples/ecs/variables.tf
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#669 Ots service support https
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_ots_table.go
Labels: size/XS

#672 fix k8s cluster worker_period_unit typo
  alicloud/resource_alicloud_cs_kubernetes.go
Labels: size/XS

#674 Fix deleting ram role error
  CHANGELOG.md
  alicloud/data_source_alicloud_pvtz_zone_records.go
  alicloud/data_source_alicloud_pvtz_zones.go
  alicloud/errors.go
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_ots_table.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_slb.go
Labels: size/M

#675 Improve ecs instance testcases
  CHANGELOG.md
  alicloud/resource_alicloud_instance_test.go
Labels: size/M

#676 Improve redis and memcache instance testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/M

#677 Add multi_zone_ids for datasource alicloud_zones
  CHANGELOG.md
  alicloud/data_source_alicloud_zones.go
  alicloud/data_source_alicloud_zones_test.go
  website/docs/d/zones.html.markdown
Labels: documentation, size/XS

#678 prefected disk testcases
  alicloud/data_source_alicloud_disks_test.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_test.go
Labels: size/XL

#679 Improve db instance's testcases
  CHANGELOG.md
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_db_instances_test.go
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/import_alicloud_db_account_privilege_test.go
  alicloud/import_alicloud_db_account_test.go
  alicloud/import_alicloud_db_backup_policy_test.go
  alicloud/import_alicloud_db_connection_test.go
  alicloud/import_alicloud_db_database_test.go
  alicloud/import_alicloud_db_instance_test.go
  alicloud/import_alicloud_kvstore_backup_policy_test.go
  alicloud/import_alicloud_kvstore_instance_test.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_account_test.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/resource_alicloud_db_connection_test.go
  alicloud/resource_alicloud_db_database_test.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_common_test.go
  alicloud/service_alicloud_ecs.go
Labels: size/XL

#680 Improve sweeper testcases
  CHANGELOG.md
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/S

#681 Modify the slb sever group testcase name
  CHANGELOG.md
  alicloud/data_source_alicloud_slb_server_groups_test.go
  alicloud/errors.go
Labels: size/XS

#683 Fix multi-k8s testcase failed error
  CHANGELOG.md
  alicloud/resource_alicloud_cs_kubernetes_test.go
Labels: size/XS

#684 Improve vpc resource and data source testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_vpcs_test.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpc_test.go
Labels: size/L

#686 fix data_source and resource ut of security_group
  alicloud/data_source_alicloud_security_groups_test.go
  alicloud/resource_alicloud_security_group_test.go
Labels: size/XL

#687 Improve vswitch resource and data source testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_vswitches_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/L

#688 Add wraperror and apply it to vpc and eip
  CHANGELOG.md
  alicloud/data_source_alicloud_eips.go
  alicloud/data_source_alicloud_vpcs.go
  alicloud/errors.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_association.go
  alicloud/resource_alicloud_eip_association_test.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/service_alicloud_vpc.go
Labels: size/XL

#689 Apply wraperror to ess group
  CHANGELOG.md
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_ess_attachment.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  alicloud/service_alicloud_ess.go
  alicloud/service_alicloud_vpc.go
Labels: size/M

#691 Fix pvtz 'Zone.VpcExists' error
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/service_alicloud_pvtz.go
Labels: size/M

#692 Fix oss bucket docs error
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/XS

#693 Update Changelog
  CHANGELOG.md
Labels: size/XS

#695 Fix ServiceUnavailable error on VPC and VSW
  CHANGELOG.md
  alicloud/data_source_alicloud_vpcs.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_logtail_config.go
  alicloud/resource_alicloud_logtail_config_test.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/M

#698 Modify pagesize on API DescribeVSWitches tp avoid ServiceUnavailable
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/XS

#697 Improve eip resource and data source testcases
  CHANGELOG.md
  alicloud/data_source_alicloud_eips_test.go
  alicloud/resource_alicloud_eip_test.go
Labels: size/M

#700 Improve pvtz attachment testcase
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone_attachment_test.go
Labels: size/XS

#701 Improve kvstore backup policy
  CHANGELOG.md
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/errors.go
  alicloud/resource_alicloud_kvstore_backup_policy.go
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/M

#704 Add notes for datahub and improve its testcase
  CHANGELOG.md
  alicloud/resource_alicloud_datahub_topic.go
  alicloud/resource_alicloud_datahub_topic_test.go
  website/docs/r/datahub_topic.html.markdown
Labels: documentation, size/XS

#708 Improve cdn testcase
  CHANGELOG.md
  alicloud/resource_alicloud_cdn_domain_test.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/S

#709 Fix modify kvstore policy not working bug
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_kvstore_backup_policy.go
Labels: size/S

#710 Fix pvtz record Zone.NotExists error when deleting record
  CHANGELOG.md
  alicloud/resource_alicloud_kvstore_backup_policy.go
  alicloud/resource_alicloud_pvtz_zone_attachment.go
  alicloud/resource_alicloud_pvtz_zone_record.go
  alicloud/service_alicloud_pvtz.go
Labels: size/XS

#711 Modify db account returning update to read after creating
  CHANGELOG.md
  alicloud/resource_alicloud_db_account.go
Labels: size/XS

#712 Fix forward entry UnknownError error
  CHANGELOG.md
  alicloud/resource_alicloud_forward.go
  alicloud/service_alicloud_vpc.go
Labels: size/M

#714 Fix snat entry IncorretSnatEntryStatus error when deleting
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_forward.go
  alicloud/resource_alicloud_logtail_attachment.go
  alicloud/resource_alicloud_logtail_attachment_test.go
  alicloud/resource_alicloud_snat.go
  alicloud/service_alicloud_vpc.go
Labels: size/M

#707 Apply wraperror to security_group, security_group_rule, vswitch, disk
  CHANGELOG.md
  alicloud/data_source_alicloud_disks.go
  alicloud/data_source_alicloud_security_group_rules.go
  alicloud/data_source_alicloud_security_groups.go
  alicloud/data_source_alicloud_vswitches.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_vswitch.go
Labels: size/M

#716 Improve security group rule testcase for classic
  CHANGELOG.md
  alicloud/data_source_alicloud_security_group_rules_test.go
Labels: size/XS

#718 add ids parameter extraction in data_resource_read
  CHANGELOG.md
  alicloud/data_source_alicloud_dns_domains.go
  alicloud/data_source_alicloud_dns_domains_test.go
  alicloud/data_source_alicloud_images.go
  alicloud/data_source_alicloud_images_test.go
  alicloud/data_source_alicloud_instance_types.go
  alicloud/data_source_alicloud_instance_types_test.go
  alicloud/data_source_alicloud_regions.go
  alicloud/data_source_alicloud_regions_test.go
  alicloud/data_source_alicloud_zones.go
  alicloud/data_source_alicloud_zones_test.go
  website/docs/d/dns_domains.html.markdown
  website/docs/d/images.html.markdown
  website/docs/d/instance_types.html.markdown
  website/docs/d/regions.html.markdown
  website/docs/d/zones.html.markdown
Labels: documentation, size/M

#720 fix resource log project descrition forcenew
  alicloud/resource_alicloud_log_project.go
  alicloud/resource_alicloud_log_project_test.go
  alicloud/resource_alicloud_logtail_attachment_test.go
  website/docs/r/log_project.html.markdown
Labels: documentation, size/S

#723 Datasource instance_types supports filter results and used to create kuberneters
  CHANGELOG.md
  alicloud/common.go
  alicloud/data_source_alicloud_instance_types.go
  alicloud/data_source_alicloud_instance_types_test.go
Labels: size/L

#724 Add note for kubernetes resource and improve its testcase
  CHANGELOG.md
  alicloud/data_source_alicloud_instance_types.go
  alicloud/data_source_alicloud_instance_types_test.go
  alicloud/resource_alicloud_cs_kubernetes_test.go
  alicloud/resource_alicloud_cs_managed_kubernetes_test.go
  website/docs/d/instance_types.html.markdown
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/M

#725 Wrap resource elasticserarch_instance's error
  CHANGELOG.md
  alicloud/import_alicloud_elasticsearch_test.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/service_alicloud_elasticsearch.go
  website/docs/r/logtail_attachment.html.markdown
Labels: documentation, size/M

#728 check vpc attributes changed
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#730 Router Entry Token Bugfix
  alicloud/resource_alicloud_route_entry.go
Labels: size/XS

#732 Fix db_account setting description bug
  CHANGELOG.md
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_route_entry.go
Labels: size/S

#733 Fix ots_table StorageServerBusy bug
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_ots_table.go
Labels: size/XS

#729 Update testcases for cen region domain route entries.
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
Labels: size/S

#731 provider supports getting credential via ecs role name
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/data_source_alicloud_kms_keys_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/service_alicloud_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/roa_signature_composer.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signer.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/algorithms.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/credential_updater.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_access_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_ecs_ram_role.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_key_pair.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_ram_role_arn.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_sts_token.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signers/signer_v2.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/errors/client_error.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/errors/server_error.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/errors/signature_does_not_match_wrapper.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/json_parser.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/response.go
  vendor/vendor.json
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XL

#734 Fix cen region route entries testcase bug
  CHANGELOG.md
  alicloud/data_source_alicloud_cen_region_route_entries_test.go
Labels: size/XS

#738 Improve api_gateway_vpc_access testcases
  CHANGELOG.md
  alicloud/import_alicloud_api_gateway_vpc_test.go
  alicloud/resource_alicloud_api_gateway_vpc_test.go
Labels: size/M

#741 test(elasticsearch) IPV6 is supported in some regions, and the defaul…
  alicloud/resource_alicloud_elasticsearch_instance_test.go
Labels: size/XS

#743 Improve nat_gateway testcases
  alicloud/resource_alicloud_nat_gateway.go
  alicloud/resource_alicloud_nat_gateway_test.go
Labels: size/L

#746 make k8s cluster deleting timeout longer
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/XS

#742 Improve eip_association testcases
  alicloud/resource_alicloud_eip_association_test.go
Labels: size/M

#748 delete data source roles limit of policy_type and policy_name
  alicloud/data_source_alicloud_ram_roles.go
  alicloud/data_source_alicloud_ram_roles_test.go
Labels: size/XS

#749 Improve snat and forward testcases
  alicloud/resource_alicloud_forward_test.go
  alicloud/resource_alicloud_snat.go
  alicloud/resource_alicloud_snat_test.go
Labels: size/M

#740 Add debug for db instance and ess group
  CHANGELOG.md
  alicloud/common.go
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_zones.go
  alicloud/errors.go
  alicloud/resource_alicloud_db_account.go
  alicloud/resource_alicloud_ess_attachment_test.go
  alicloud/service_alicloud_ess.go
  alicloud/service_alicloud_rds.go
Labels: size/M
