Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-05, with the labels that each got.

#2412 Fix regression in writeToFile
  alicloud/common.go
Labels: size/XS

#2397 optimized create emr cluster test case
  alicloud/data_source_alicloud_emr_instance_types.go
  alicloud/resource_alicloud_emr_cluster_test.go
Labels: size/M

#2415 fix log audit document
  website/docs/r/log_audit.html.markdown
Labels: documentation, size/M

#2371 add a new resource cen_route_map
  alicloud/provider.go
  alicloud/resource_alicloud_cen_route_map.go
  alicloud/resource_alicloud_cen_route_map_test.go
  alicloud/service_alicloud_cbn.go
  website/alicloud.erb
  website/docs/r/cen_route_map.html.markdown
Labels: documentation, size/XXL

#2425 A new resource for Resource Manager Folder
  alicloud/provider.go
  alicloud/resource_alicloud_resource_manager_folder.go
  alicloud/resource_alicloud_resource_manager_folder_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_folder.html.markdown
Labels: documentation, size/L

#2429 fix_markdown_slb_vpc
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#2432 A new resource for ResourceManager Handshake.
  alicloud/provider.go
  alicloud/resource_alicloud_resource_manager_handshake.go
  alicloud/resource_alicloud_resource_manager_handshake_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_handshake.html.markdown
Labels: documentation, size/L

#2430 fix_markdown_instance
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#2433 Update changelog
  CHANGELOG.md
  alicloud/resource_alicloud_resource_manager_handshake_test.go
Labels: size/S

#2421 add a new resource alicloud_cen_private_zone
  alicloud/provider.go
  alicloud/resource_alicloud_cen_private_zone.go
  alicloud/resource_alicloud_cen_private_zone_test.go
  alicloud/service_alicloud_cbn.go
  website/alicloud.erb
  website/docs/r/cen_private_zone.html.markdown
Labels: documentation, size/XL

#2436 fix_markdown_instance
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#2439 A new resource for Resource Manager policy
  alicloud/provider.go
  alicloud/resource_alicloud_resource_manager_policy.go
  alicloud/resource_alicloud_resource_manager_policy_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_policy.html.markdown
Labels: documentation, size/XL

#2441 A new resource for ResourceManager Account.
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_resource_manager_account.go
  alicloud/resource_alicloud_resource_manager_account_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_account.html.markdown
Labels: documentation, size/XL

#2455 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2377 fix autoscaler configmap update
  alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
Labels: size/XS

#2458 fix the bug of TestAccAlicloudEmrCluster_local_storage nodeCount less…
  alicloud/resource_alicloud_emr_cluster_test.go
Labels: size/XS

#2459 A new resource for Resource Manager Resource Directory
  alicloud/provider.go
  alicloud/resource_alicloud_resource_manager_resource_directory.go
  alicloud/resource_alicloud_resource_manager_resource_directory_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_resource_directory.html.markdown
Labels: documentation, size/L

#2460 fix_markdown_key_pair_attachment
  website/docs/r/key_pair_attachment.html.markdown
Labels: documentation, size/XS

#2445 fix_tag_validation
  alicloud/resource_alicloud_cs_kubernetes_autoscaler.go
  alicloud/resource_alicloud_instance.go
  alicloud/tags.go
Labels: size/XS

#2463 fix_finger_print
  alicloud/data_source_alicloud_key_pairs.go
Labels: size/XS

#2453 fix polardb connection string output bug
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/S

#2468 A new DataSource for Alidns Instance.
  alicloud/data_source_alicloud_dns_instances.go
  alicloud/data_source_alicloud_dns_instances_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/dns_instances.html.markdown
Labels: documentation, size/L

#2469 fix_markdown_alicloud_network_interface_attachment
  website/docs/r/network_interface_attachment.html.markdown
Labels: documentation, size/XS

#2440 fix eip association failed cause by snat entry's snat_ip update bug
  alicloud/resource_alicloud_snat_entry.go
Labels: size/XS

#2465 fix_markdown_instance_type_families
  website/docs/d/instance_type_families.html.markdown
Labels: documentation, size/XS

#2467 A new datasource for Resource Manager Folders
  alicloud/data_source_alicloud_resource_manager_folders.go
  alicloud/data_source_alicloud_resource_manager_folders_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/resource_manager_folders.html.markdown
Labels: documentation, size/XL

#2454 A new resource for Alidns DomainGroup.
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  alicloud/resource_alicloud_alidns_domain_group.go
  alicloud/resource_alicloud_alidns_domain_group_test.go
  alicloud/service_alicloud_alidns.go
  website/alicloud.erb
  website/docs/r/alidns_domain_group.html.markdown
  website/docs/r/dns_group.html.markdown
Labels: documentation, size/XL

#2462 A new datasource for Resource Manager Resource Groups
  alicloud/data_source_alicloud_resource_manager_resource_groups.go
  alicloud/data_source_alicloud_resource_manager_resource_groups_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/resource_manager_resource_groups.html.markdown
Labels: documentation, size/XL

#2457 A new resource for Resource Manager Policy Version
  alicloud/provider.go
  alicloud/resource_alicloud_resource_manager_policy_version.go
  alicloud/resource_alicloud_resource_manager_policy_version_test.go
  alicloud/service_alicloud_resourcemanager.go
  website/alicloud.erb
  website/docs/r/resource_manager_policy_version.html.markdown
Labels: documentation, size/XL

#2477 UPDATE CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2475 fix_markdown_network_interfaces
  website/docs/d/network_interfaces.html.markdown
Labels: documentation, size/XS

#2473 Alicloud edas docs modify
  alicloud/resource_alicloud_edas_application.go
  alicloud/resource_alicloud_edas_application_package_attachment.go
  alicloud/resource_alicloud_edas_deploy_group.go
  alicloud/resource_alicloud_edas_instance_cluster_attachment.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/edas/unbind_slb.go
  website/docs/r/edas_application.html.markdown
  website/docs/r/edas_application_deployment.html.markdown
  website/docs/r/edas_application_scale.html.markdown
  website/docs/r/edas_slb_attachment.html.markdown
Labels: dependencies, documentation, size/XS

#2472 fix_apg
  alicloud/resource_alicloud_auto_provisioning_group.go
Labels: size/XS

#2444 kms key resource
  alicloud/resource_alicloud_kms_key.go
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/service_alicloud_kms.go
  website/docs/r/kms_key.html.markdown
Labels: documentation, size/XL

#2471 kms keyversion
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_kms_key_version.go
  alicloud/resource_alicloud_kms_key_version_test.go
  alicloud/service_alicloud_kms.go
  website/alicloud.erb
  website/docs/r/kms_key_version.html.markdown
Labels: documentation, size/L

#2478 fix_markdown_reserved_instance
  alicloud/resource_alicloud_kms_key.go
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/service_alicloud_kms.go
  website/docs/r/reserved_instance.html.markdown
Labels: documentation, size/XS

#2490 增加cdn_config删除错误码。
  alicloud/service_alicloud_cdn.go
Labels: size/XS

#2482 A new datasoruce for Alidns Domain Group.
  alicloud/data_source_alicloud_alidns_domain_groups.go
  alicloud/data_source_alicloud_alidns_domain_groups_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/alidns_domain_groups.html.markdown
Labels: documentation, size/L

#2495 A new resource for Alidns record.
  alicloud/provider.go
  alicloud/resource_alicloud_alidns_record.go
  alicloud/resource_alicloud_alidns_record_test.go
  alicloud/resource_alicloud_kms_key_version.go
  alicloud/resource_alicloud_kms_key_version_test.go
  alicloud/service_alicloud_alidns.go
  website/alicloud.erb
  website/docs/r/alidns_record.html.markdown
  website/docs/r/dns_record.html.markdown
Labels: documentation, size/XL

#2497 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2496 A new datasource for Resource Manager Policy Versions
  alicloud/data_source_alicloud_resource_manager_policy_versions.go
  alicloud/data_source_alicloud_resource_manager_policy_versions_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/resource_manager_policy_versions.html.markdown
Labels: documentation, size/L

#2494 New datasource kms keyversions
  alicloud/data_source_alicloud_kms_key_versions.go
  alicloud/data_source_alicloud_kms_key_versions_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kms_key_versions.html.markdown
Labels: documentation, size/L

#2464 Control the instance start and stop through the status attribute.
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M
