Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-09, with the labels that each got.

#2580 Rewrote resource page to correct name
  website/docs/r/cms_site_monitor.html.markdown
Labels: documentation, size/XS

#2552 fix_auto_provisioning_group
  alicloud/resource_alicloud_auto_provisioning_group.go
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#2545 datasource snapshots supports outputting tags
  alicloud/data_source_alicloud_snapshots.go
  website/docs/d/snapshots.html.markdown
  website/docs/r/snapshot.html.markdown
Labels: documentation, size/S
