Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-08, with the labels that each got.

#2682 Support to get NotFound error in read method.
  alicloud/resource_alicloud_auto_provisioning_group.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_ecs_dedicated_host.go
  alicloud/resource_alicloud_image.go
  alicloud/resource_alicloud_image_share_permission.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_key_pair.go
  alicloud/resource_alicloud_launch_template.go
  alicloud/resource_alicloud_network_interface.go
  alicloud/resource_alicloud_network_interface_attachment.go
  alicloud/resource_alicloud_security_group.go
  alicloud/resource_alicloud_security_group_rule.go
  alicloud/resource_alicloud_snapshot.go
  alicloud/resource_alicloud_snapshot_policy.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#2679 Add oos execution resource and datasource
  alicloud/common.go
  alicloud/data_source_alicloud_oos_executions.go
  alicloud/data_source_alicloud_oos_executions_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_oos_execution.go
  alicloud/resource_alicloud_oos_execution_test.go
  alicloud/service_alicloud_oos.go
  website/alicloud.erb
  website/docs/d/oos_executions.html.markdown
  website/docs/r/oos_execution.html.markdown
Labels: documentation, size/XXL

#2685 fix cassandra doc and add describe not found error
  alicloud/data_source_alicloud_cassandra_clusters_test.go
  alicloud/data_source_alicloud_cassandra_data_centers_test.go
  alicloud/resource_alicloud_cassandra_cluster.go
  alicloud/resource_alicloud_cassandra_cluster_test.go
  alicloud/resource_alicloud_cassandra_data_center.go
  alicloud/resource_alicloud_cassandra_data_center_test.go
  alicloud/service_alicloud_cassandra.go
Labels: size/XL

#2686 fix(edas): improve sweeper test
  alicloud/resource_alicloud_edas_cluster_test.go
  alicloud/resource_alicloud_edas_k8s_cluster_test.go
  alicloud/resource_alicloud_image_share_permission.go
  alicloud/resource_alicloud_vpc_test.go
Labels: size/XS

#2688 Add default vpc for kvstore
  alicloud/data_source_alicloud_kvstore_instances_test.go
  alicloud/resource_alicloud_kvstore_backup_policy_test.go
  alicloud/resource_alicloud_kvstore_instance_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/M

#2689 Add default vpc for mongodb
  alicloud/data_source_alicloud_mongodb_instances_test.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
Labels: size/XL

#2651 improve(slb) update slb_backend_server add parameter server_ip
  alicloud/extension_slb.go
  alicloud/resource_alicloud_slb_backend_server.go
  alicloud/resource_alicloud_slb_backend_server_test.go
  examples/slb-backend-server/main.tf
  website/docs/r/slb_backend_server.html.markdown
Labels: documentation, size/S

#2690 fix: create rds sql_collector_status bug.
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#2572 fix doc: attach AliyunMNSNotificationRolePolicy to role
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/S

#2559 docs: fix typos and grammar in Alicloud Provider
  website/docs/guides/getting-account.html.md
Labels: documentation, size/S

#2540 fix_markdown_snapshot_policy
  website/docs/r/snapshot_policy.html.markdown
Labels: documentation, size/XS

#2543 fix_markdown_auto_provisioning_group
  website/docs/r/auto_provisioning_group.html.markdown
Labels: documentation, size/XS

#2693 Add purge cluster api for cassandra sweeper
  alicloud/resource_alicloud_cassandra_cluster_test.go
Labels: size/XS

#2694 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2691 improve(slb) update doc alicloud_slb_backend_servers
  website/docs/d/slb_backend_servers.html.markdown
Labels: documentation, size/XS

#2562 fix_markdown_security_group_rules
  website/docs/d/security_group_rules.html.markdown
Labels: documentation, size/S
