Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-03, with the labels that each got.

#2212 improve sweeper test
  alicloud/common.go
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  alicloud/resource_alicloud_alikafka_instance_test.go
  alicloud/resource_alicloud_alikafka_sasl_acl_test.go
  alicloud/resource_alicloud_alikafka_topic_test.go
  alicloud/resource_alicloud_cas_certificate_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_network_interface_test.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/L

#2213 improve alikafka sweeper test
  alicloud/resource_alicloud_alikafka_instance_test.go
  alicloud/resource_alicloud_alikafka_sasl_acl_test.go
  alicloud/resource_alicloud_alikafka_sasl_user_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
Labels: size/S

#2216 fix(elasticsearch_instance): resolve the ci bug
  alicloud/resource_alicloud_elasticsearch_instance_test.go
Labels: size/XS

#2214 Support the parameter of 'protocol'.
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/provider.go
Labels: size/XS

#2191 added new resoure provider for cms sitemonitor
  alicloud/extension_cms.go
  alicloud/provider.go
  alicloud/resource_alicloud_cms_site_monitor.go
  alicloud/resource_alicloud_cms_site_monitor_test.go
  alicloud/service_alicloud_cms.go
  go.sum
  website/docs/r/cms_sitemonitor.markdown 
Labels: documentation, size/XL

#2219 fix the bug of RAM user cannot be destroyed.
  alicloud/resource_alicloud_ram_user.go
Labels: size/XS

#2223 fix sweep test bug
  alicloud/alicloud_sweeper_test.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#2162 Feature/datasource ess lifecyclehooks
  alicloud/data_source_alicloud_ess_lifecyclehooks.go
  alicloud/data_source_alicloud_ess_lifecyclehooks_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/ess_lifecycle_hooks.html.markdown
Labels: documentation, size/XL

#2225 improve(mns_topic_subscription): remove the validate
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/resource_alicloud_mns_topic_subscription.go
Labels: size/XS

#2226 Update Changelog.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2224 add security group id in mongodb
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/M

#2229 add a new resource cen_flowlog
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_flowlog.go
  alicloud/resource_alicloud_cen_flowlog_test.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cbn.go
  website/docs/r/cen_flowlog.html.markdown
Labels: documentation, size/XL

#2231 terraform format examples
  examples/alikafka-consumer-group/main.tf
  examples/alikafka-instance/main.tf
  examples/alikafka-sasl-user/main.tf
  examples/alikafka-topic/main.tf
  examples/bastionhost/main.tf
  examples/build-lnmp/main.tf
  examples/cloud_connect_network/main.tf
  examples/cluster-autoscaler/main.tf
  examples/cluster-autoscaler/variables.tf
  examples/dbaudit/main.tf
  examples/ddosbgp/main.tf
  examples/dns/main.tf
  examples/ecs-new-vpc/main.tf
  examples/ecs-ram-role/main.tf
  examples/emr-cluster/main.tf
  examples/hbase/main.tf
  examples/kubernetes/main.tf
  examples/kvstore/main.tf
  examples/polardb/main.tf
  examples/sag_acl/main.tf
  examples/sag_acl_rule/main.tf
  examples/serverless-kubernetes/main.tf
  examples/serverless-kubernetes/variables.tf
  examples/vpn-route-entry/main.tf
Labels: size/XL

#2232 add new version aliyungo
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/denverdino/aliyungo/common/client.go
  vendor/github.com/denverdino/aliyungo/common/regions.go
  vendor/github.com/denverdino/aliyungo/common/types.go
  vendor/github.com/denverdino/aliyungo/cs/client.go
  vendor/github.com/denverdino/aliyungo/cs/projects_client.go
  vendor/github.com/denverdino/aliyungo/ecs/disks.go
  vendor/github.com/denverdino/aliyungo/ecs/route_entry.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/net/publicsuffix/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#2230 fix(es): fix ci bug.
  alicloud/resource_alicloud_elasticsearch_instance_test.go
Labels: size/XS

#2228 Hbase tags
  alicloud/data_source_alicloud_hbase_instances.go
  alicloud/data_source_alicloud_hbase_instances_test.go
  alicloud/resource_alicloud_hbase_instance.go
  alicloud/resource_alicloud_hbase_instance_test.go
  alicloud/service_alicloud_hbase.go
  examples/hbase/main.tf
  examples/hbase/outputs.tf
  examples/hbase/variables.tf
  go.mod
  go.sum
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/add_user_hdfs_info.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/convert_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/create_cluster.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/create_hbase_ha_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/create_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/delete_hbase_ha_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/delete_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/delete_user_hdfs_info.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_db_instance_usage.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_endpoints.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_instance_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_ip_whitelist.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/describe_security_groups.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/list_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/list_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_cluster_deletion_protection.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_instance_maintain_time.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_instance_name.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_ip_whitelist.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_security_groups.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/modify_ui_account_password.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/query_h_base_ha_db.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/query_xpack_relate_db.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/renew_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/resize_disk_size.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/resize_node_count.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/restart_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/struct_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/switch_hbase_ha_slb.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/un_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/hbase/xpack_relate_db.go
  website/docs/d/hbase_instances.html.markdown
  website/docs/r/hbase_instance.html.markdown
Labels: dependencies, documentation, size/XXL

#2233 fix SQLServer testcase
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#2207 mongodb support TDE
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/M

#2237 add flowlog docs in the alicloud.erb
  alicloud/service_alicloud_kms.go
  website/alicloud.erb
Labels: documentation, size/XS

#2235 New datasource for RDS zones.
  alicloud/data_source_alicloud_db_zones.go
  alicloud/data_source_alicloud_db_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/db_zones.html.markdown
Labels: documentation, size/L

#2242 fix(cms_alarm): resolve the effective_interval format bug
  alicloud/resource_alicloud_cms_alarm.go
Labels: size/XS

#2240 A new datasource for HBase zones.
  alicloud/data_source_alicloud_hbase_zones.go
  alicloud/data_source_alicloud_hbase_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/hbase_zones.html.markdown
Labels: documentation, size/L

#2241 A new datasource for Gpdb zones.
  alicloud/data_source_alicloud_gpdb_zones.go
  alicloud/data_source_alicloud_gpdb_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/gpdb_zones.html.markdown
Labels: documentation, size/L

#2236 A new datasource for KVStore zones.
  alicloud/data_source_alicloud_kvstore_zones.go
  alicloud/data_source_alicloud_kvstore_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kvstore_zones.html.markdown
Labels: documentation, size/L

#2238 A new datasource for mongodb zones.
  alicloud/data_source_alicloud_mongodb_zones.go
  alicloud/data_source_alicloud_mongodb_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/mongodb_zones.html.markdown
Labels: documentation, size/L

#2245 improve(ecs): supported auto snapshop policy.
  alicloud/resource_alicloud_instance.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#2252 Adjust the return error mode.
  alicloud/data_source_alicloud_db_zones.go
  alicloud/data_source_alicloud_gpdb_zones.go
  alicloud/data_source_alicloud_hbase_zones.go
  alicloud/data_source_alicloud_kvstore_zones.go
  alicloud/data_source_alicloud_mongodb_zones.go
  alicloud/data_source_alicloud_zones.go
Labels: size/XS

#2249 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2251 improve(elasticsearch): resource support tags
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/service_alicloud_elasticsearch.go
  go.mod
  go.sum
  website/docs/r/elasticsearch.html.markdown
Labels: documentation, size/L

#2250 A new datasource for polarDB zones.
  alicloud/data_source_alicloud_polardb_zones.go
  alicloud/data_source_alicloud_polardb_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/polardb_zones.html.markdown
Labels: documentation, size/L

#2253 fix(cms_alarm): resolve the effective_interval default value
  alicloud/resource_alicloud_cms_alarm.go
  website/alicloud.erb
  website/docs/r/cms_alarm.html.markdown
  website/docs/r/cms_sitemonitor.html.markdown
Labels: documentation, size/S

#2254 corrct cen_flowlog docs
  website/alicloud.erb
Labels: documentation, size/XS

#2255 rename polardb test name
  alicloud/data_source_alicloud_polardb_clusters_test.go
Labels: size/XS

#2256 A new datasource for FC zones.
  alicloud/data_source_alicloud_fc_zones.go
  alicloud/data_source_alicloud_fc_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/fc_zones.html.markdown
Labels: documentation, size/L

#2259 improve(hbase): modify the vsw specified.
  alicloud/data_source_alicloud_hbase_instances_test.go
  alicloud/resource_alicloud_hbase_instance_test.go
Labels: size/M

#2257 improve(elasticsearch): data_source support tags
  alicloud/data_source_alicloud_elasticsearch_instances.go
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  alicloud/service_alicloud_elasticsearch.go
  alicloud/tags.go
  website/docs/d/elasticsearch.html.markdown
Labels: documentation, size/M

#2239 improve(elasticsearch): modify the vsw specified.
  alicloud/data_source_alicloud_elasticsearch_instances_test.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/S

#2264 improve(alikafka_instance): suspend kafka prepaid test
  alicloud/resource_alicloud_alikafka_instance_test.go
Labels: size/XS

#2260 improve(gpdb): modify the vsw specified.
  alicloud/data_source_alicloud_gpdb_instances_test.go
  alicloud/resource_alicloud_gpdb_connection_test.go
  alicloud/resource_alicloud_gpdb_instance_test.go
Labels: size/S

#2266 tagResource bug fix
  alicloud/service_alicloud_kvstore.go
Labels: size/XS

#2265 fix(kvstore_instance): resolve auto_renew incorrect value
  alicloud/resource_alicloud_kvstore_instance.go
Labels: size/XS

#2268 Update CHANGLOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2269 fix(cen):modify resource_alicloud_cen_instance_attachment
  alicloud/resource_alicloud_cen_instance_attachment.go
Labels: size/XS

#2272 fix adb ci bug
  alicloud/data_source_alicloud_adb_clusters.go
  alicloud/data_source_alicloud_adb_clusters_test.go
  alicloud/resource_alicloud_adb_account_test.go
  alicloud/resource_alicloud_adb_backup_policy_test.go
  alicloud/resource_alicloud_adb_cluster.go
  alicloud/resource_alicloud_adb_cluster_test.go
  alicloud/service_alicloud_adb.go
  alicloud/service_alicloud_common_test.go
  examples/adb/main.tf
  website/docs/r/adb_account.html.markdown
  website/docs/r/adb_backup_policy.html.markdown
  website/docs/r/adb_cluster.html.markdown
Labels: documentation, size/L

#2248 A new datasource for ADB zones.
  alicloud/data_source_alicloud_adb_zones.go
  alicloud/data_source_alicloud_adb_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/adb_zones.html.markdown
Labels: documentation, size/L

#2274 fix polardb data source zones
  alicloud/data_source_alicloud_polardb_zones.go
  alicloud/data_source_alicloud_zones.go
Labels: size/S

#2283 fix ADB data source zones
  alicloud/data_source_alicloud_adb_zones.go
  alicloud/data_source_alicloud_zones.go
Labels: size/XS

#2244 A new datasource for Slb zones.
  alicloud/data_source_alicloud_slb_zones.go
  alicloud/data_source_alicloud_slb_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/slb_zones.html.markdown
Labels: documentation, size/L

#2243 A new datasource for elasticsearch zones.
  alicloud/data_source_alicloud_elasticsearch_zones.go
  alicloud/data_source_alicloud_elasticsearch_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/elasticsearch_zones.html.markdown
Labels: documentation, size/L

#2285 imporve the zones markdown.
  website/docs/d/adb_zones.html.markdown
  website/docs/d/db_zones.html.markdown
  website/docs/d/elasticsearch_zones.html.markdown
  website/docs/d/fc_zones.html.markdown
  website/docs/d/gpdb_zones.html.markdown
  website/docs/d/hbase_zones.html.markdown
  website/docs/d/kvstore_zones.html.markdown
  website/docs/d/mongodb_zones.html.markdown
  website/docs/d/polardb_zones.html.markdown
  website/docs/d/slb_zones.html.markdown
Labels: documentation, size/XS

#2286 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2287 imporve(db_instance): support force_restart
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/S

#2297 improve cen_instance and cen_flowlog
  alicloud/data_source_alicloud_kvstore_instance_classes.go
  alicloud/data_source_alicloud_kvstore_zones.go
  alicloud/resource_alicloud_cen_bandwidth_limit_test.go
  alicloud/resource_alicloud_cen_flowlog.go
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cbn.go
  alicloud/service_alicloud_cen.go
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/L

#2298 add security group id and TDE for mongodb sharding
  alicloud/resource_alicloud_mongodb_sharding_instance.go
  alicloud/resource_alicloud_mongodb_sharding_instance_test.go
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/L

#2296 added support for isp_cities in site_monitor
  alicloud/resource_alicloud_cms_site_monitor.go
  alicloud/resource_alicloud_cms_site_monitor_test.go
  alicloud/service_alicloud_cms.go
  go.sum
  website/docs/r/cms_sitemonitor.html.markdown
Labels: documentation, size/M

#2277 support parameter DesiredCapacity
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_ess_scalinggroup_test.go
  website/docs/r/ess_scaling_group.html.markdown
Labels: documentation, size/M

#2293 fix(cen):modify resource_alicloud_cen_instance_grant
  alicloud/resource_alicloud_cen_instance_grant.go
Labels: size/XS

#2310 add a new resource alicloud_kms_secret
  alicloud/common.go
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/extension_tags.go
  alicloud/provider.go
  alicloud/resource_alicloud_cen_flowlog.go
  alicloud/resource_alicloud_kms_key_test.go
  alicloud/resource_alicloud_kms_secret.go
  alicloud/resource_alicloud_kms_secret_test.go
  alicloud/service_alicloud_cbn.go
  alicloud/service_alicloud_kms.go
  alicloud/tags.go
  website/alicloud.erb
  website/docs/r/kms_secret.html.markdown
Labels: documentation, size/XL

#2309 change default autoscaler tag and refactor docs of managed kubernetes
  alicloud/service_alicloud_cs.go
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS

#2308 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2311 fix(db_instance): resolve postgres testcase
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#2312 fix adb ci bug
  alicloud/resource_alicloud_adb_cluster_test.go
Labels: size/XS

#2313 improve(kms_secret): improve tags
  alicloud/resource_alicloud_kms_secret.go
  alicloud/service_alicloud_kms.go
  alicloud/tags.go
Labels: size/M
