Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-06, with the labels that each got.

#2503 A new datasource for Alidns Domain Records.
  alicloud/data_source_alicloud_alidns_records.go
  alicloud/data_source_alicloud_alidns_records_test.go
  alicloud/data_source_alicloud_kms_key_versions.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/alidns_record.html.markdown
Labels: documentation, size/XL

#2501 fix_markdown_disk_attachment
  website/docs/r/disk_attachment.html.markdown
Labels: documentation, size/XS

#2481 fix Resource Manager Role
  alicloud/resource_alicloud_resource_manager_role.go
Labels: size/XS

#2488 A new datasource for Resource Manager Accounts
  alicloud/data_source_alicloud_resource_manager_accounts.go
  alicloud/data_source_alicloud_resource_manager_accounts_test.go
  alicloud/provider.go
  alicloud/provider_test.go
  website/alicloud.erb
  website/docs/d/alidns_records.html.markdown
  website/docs/d/resource_manager_accounts.html.markdown
Labels: documentation, size/L

#2499 A new datasource for Resource Manager Resource Directories
  alicloud/data_source_alicloud_resource_manager_resource_directories.go
  alicloud/data_source_alicloud_resource_manager_resource_directories_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/resource_manager_resource_directories.html.markdown
Labels: documentation, size/XL

#2489 A new datasource for Resource Manager Handshakes
  alicloud/data_source_alicloud_resource_manager_handshakes.go
  alicloud/data_source_alicloud_resource_manager_handshakes_test.go
  alicloud/provider.go
  alicloud/provider_test.go
  website/alicloud.erb
  website/docs/d/resource_manager_handshakes.html.markdown
Labels: documentation, size/L

#2516 fix_markdown_image_import
  website/docs/r/image_import.html.markdown
Labels: documentation, size/XS

#2498 add new datasource alicloud_waf_domains
  CHANGELOG.md
  alicloud/data_source_alicloud_waf_domains.go
  alicloud/data_source_alicloud_waf_domains_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_waf_domain.go
  website/alicloud.erb
  website/docs/d/waf_domains.html.markdown
Labels: documentation, size/L

#2509 support "resource_group_id" for kvstore instance.
  alicloud/resource_alicloud_kvstore_instance.go
  website/docs/r/kvstore_instance.html.markdown
Labels: documentation, size/XS

#2515 Add datasource kms secrets
  alicloud/data_source_alicloud_kms_secrets.go
  alicloud/data_source_alicloud_kms_secrets_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kms_secrets.html.markdown
Labels: documentation, size/XL

#2512 fix ecs 'status' attribute bug.
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#2521 Added new feature of encrypting data node disk
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  examples/elasticsearch/main.tf
  examples/elasticsearch/variables.tf
  website/docs/r/elasticsearch.html.markdown
Labels: documentation, size/M

#2508 fix_markdown_ess_scalinggroup_vserver_groups
  website/docs/r/ess_scalinggroup_vserver_groups.markdown
Labels: documentation, size/XS

#2502 Add Log Dashboard
  alicloud/provider.go
  alicloud/resource_alicloud_log_dashboard.go
  alicloud/resource_alicloud_log_dashboard_test.go
  alicloud/service_alicloud_log.go
  website/alicloud.erb
  website/docs/r/log_dashboard.html.markdown
Labels: documentation, size/XL

#2525 A new resource for Container Registry Enterprise Repo.
  alicloud/provider.go
  alicloud/resource_alicloud_cr_ee_repo.go
  alicloud/resource_alicloud_cr_ee_repo_test.go
  website/alicloud.erb
  website/docs/r/cr_ee_repo.html.markdown
Labels: documentation, size/XL

#2476 A new resource for DdosCoo SchedulerRule
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  alicloud/resource_alicloud_ddoscoo_scheduler_rule.go
  alicloud/resource_alicloud_ddoscoo_scheduler_rule_test.go
  alicloud/service_alicloud_ddoscoo.go
  website/alicloud.erb
  website/docs/r/ddoscoo_scheduler_rule.html.markdown
Labels: dependencies, documentation, size/XL

#2518 support "resource_group_id" for Private Zone
  alicloud/resource_alicloud_pvtz_zone.go
  website/docs/r/pvtz_zone.html.markdown
Labels: documentation, size/XS

#2528 support "resource_group_id" for Elasticsearch instance
  alicloud/resource_alicloud_elasticsearch_instance.go
  website/docs/r/elasticsearch.html.markdown
Labels: documentation, size/XS

#2537 adapter schedulerrule
  alicloud/resource_alicloud_ddoscoo_scheduler_rule.go
Labels: size/S

#2535 UPDATE CHANHELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2529 fix_markdown_ess_scalinggroup
  website/docs/r/ess_scaling_group.html.markdown
Labels: documentation, size/XS

#2520 fix_markdown_image_import
  website/docs/r/image_import.html.markdown
Labels: documentation, size/XS

#2504 fix_markdown_disk
  website/docs/r/disk.html.markdown
Labels: documentation, size/XS

#2491 improve_user_experience
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/XS

#2526 A new datasource for Container Registry Enterprise Instances.
  alicloud/data_source_alicloud_cr_ee_instances.go
  alicloud/data_source_alicloud_cr_ee_instances_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cr_ee_instances.html.markdown
Labels: documentation, size/XL

#2530 A new datasource for Container Registry Enterprise Namespaces.
  alicloud/data_source_alicloud_cr_ee_namespaces.go
  alicloud/data_source_alicloud_cr_ee_namespaces_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cr_ee_namespaces.html.markdown
Labels: documentation, size/XL

#2538 A new datasource for Container Registry Enterprise Repos.
  alicloud/data_source_alicloud_cr_ee_repos.go
  alicloud/data_source_alicloud_cr_ee_repos_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cr_ee_repos.html.markdown
Labels: documentation, size/XL

#2542 Fix image export
  alicloud/resource_alicloud_image_export.go
  website/docs/r/image_export.html.markdown
Labels: documentation, size/XS

#2533 fix: perf create rds pg
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/XS

#2544 support "resource_group_id" for Bastionhost Instance
  alicloud/resource_alicloud_yundun_bastionhost_instance.go
  alicloud/resource_alicloud_yundun_bastionhost_instance_test.go
  alicloud/service_alicloud_yundun_bastionhost.go
  website/docs/r/yundun_bastionhost_instance.html.markdown
Labels: documentation, size/S

#2539 support "resource_group_id" for DBaudit Instance
  alicloud/resource_alicloud_yundun_dbaudit_instance.go
  alicloud/resource_alicloud_yundun_dbaudit_instance_test.go
  alicloud/service_alicloud_yundun_dbaudit.go
  website/docs/d/resource_manager_resource_directories.html.markdown
  website/docs/r/yundun_dbaudit_instance.html.markdown
Labels: documentation, size/S

#2554 new datasource for CEN Route Maps
  alicloud/data_source_alicloud_cen_route_maps.go
  alicloud/data_source_alicloud_cen_route_maps_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cen_route_maps.html.markdown
Labels: documentation, size/XL

#2548 improve(elasticsearch): resource support to open or close network, and modify the kibana whitelist in private network
  alicloud/common.go
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/resource_alicloud_elasticsearch_instance_test.go
  alicloud/service_alicloud_elasticsearch.go
  website/docs/r/elasticsearch.html.markdown
Labels: documentation, size/XL

#2546 fix_markdown_image_s
  website/docs/r/image.html.markdown
  website/docs/r/image_copy.html.markdown
  website/docs/r/image_export.html.markdown
  website/docs/r/image_import.html.markdown
  website/docs/r/image_share_permission.html.markdown
Labels: documentation, size/XS

#2556 add testcase
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  alicloud/resource_alicloud_pvtz_zone_test.go
Labels: size/XS

#2549 Automatically generate dns_domain datasource.
  alicloud/data_source_alicloud_dns_domains.go
  alicloud/data_source_alicloud_dns_domains_test.go
  website/docs/d/dns_domains.html.markdown
Labels: documentation, size/XL

#2555 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2558 fix name spelling mistake.
  website/docs/r/kms_secret.html.markdown
Labels: documentation, size/XS

#2561 gpdb doc change "tf-gpdb-test"" to "tf-gpdb-test"
  website/docs/r/gpdb_instance.html.markdown
Labels: documentation, size/XS

#2569 Fix the fc-function testcase and markdown.
  alicloud/resource_alicloud_fc_function_test.go
  website/docs/r/fc_function.html.markdown
Labels: documentation, size/S

#2566 modify cen_instance_attachment
  alicloud/resource_alicloud_cen_instance_attachment.go
  alicloud/service_alicloud_cen.go
Labels: size/S

#2564 new datasource for CEN Private Zones
  alicloud/data_source_alicloud_cen_private_zones.go
  alicloud/data_source_alicloud_cen_private_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cen_private_zones.html.markdown
Labels: documentation, size/XL

#2557 Add dms datasource
  alicloud/data_source_alicloud_dms_enterprise_instances.go
  alicloud/data_source_alicloud_dms_enterprise_instances_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/dms_enterprise_instances.html.markdown
Labels: documentation, size/XL

#2575 add a new resource alicloud_cen_vbr_health_check
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_cen_vbr_health_check.go
  alicloud/resource_alicloud_cen_vbr_health_check_test.go
  alicloud/service_alicloud_cbn.go
  website/alicloud.erb
  website/docs/r/cen_vbr_health_check.html.markdown
Labels: documentation, size/XL

#2574 cassandra data source
  alicloud/data_source_alicloud_cassandra_clusters.go
  alicloud/data_source_alicloud_cassandra_clusters_test.go
  alicloud/data_source_alicloud_cassandra_data_centers.go
  alicloud/data_source_alicloud_cassandra_data_centers_test.go
  alicloud/data_source_alicloud_cassandra_zones.go
  alicloud/data_source_alicloud_cassandra_zones_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cassandra_clusters.html.markdown
  website/docs/d/cassandra_data_centers.html.markdown
  website/docs/d/cassandra_zones.html.markdown
Labels: documentation, size/XXL

#2576 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2583 add datasource kms secret version
  alicloud/data_source_alicloud_kms_secret_versions.go
  alicloud/data_source_alicloud_kms_secret_versions_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kms_secret_versions.html.markdown
Labels: documentation, size/L

#2584 Changelog
  CHANGELOG.md
Labels: size/XS

#2585 skip instance prepaid testcase
  alicloud/provider_test.go
  alicloud/resource_alicloud_edas_cluster_test.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/S

#2587 run 'go mod vendor' to sync
  CHANGELOG.md
  vendor/modules.txt
Labels: dependencies, size/XS

#2588 fix the dns_record test case bug.
  alicloud/resource_alicloud_dns_record_test.go
Labels: size/XS

#2591 improve(alikafka): using default vswitch to run alikafka testcases
  alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
  alicloud/data_source_alicloud_alikafka_instances_test.go
  alicloud/data_source_alicloud_alikafka_sasl_acls_test.go
  alicloud/data_source_alicloud_alikafka_sasl_users_test.go
  alicloud/data_source_alicloud_alikafka_topics_test.go
  alicloud/resource_alicloud_alikafka_consumer_group_test.go
  alicloud/resource_alicloud_alikafka_sasl_acl_test.go
  alicloud/resource_alicloud_alikafka_sasl_user_test.go
  alicloud/resource_alicloud_alikafka_topic_test.go
Labels: size/L

#2592 fix testcase for pvtz_zone
  alicloud/resource_alicloud_pvtz_zone_test.go
Labels: size/XS

#2593 Support modify system_disk_size online.
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/S

#2596 fix kms secret, secret version doc
  website/docs/d/kms_secret_versions.html.markdown
  website/docs/d/kms_secrets.html.markdown
Labels: documentation, size/XS

#2597 Add version_stage filter
  alicloud/data_source_alicloud_kms_secret_versions.go
  alicloud/data_source_alicloud_kms_secret_versions_test.go
  website/docs/d/kms_secret_versions.html.markdown
Labels: documentation, size/S

#2541 fix_markdown_launch_template
  alicloud/resource_alicloud_launch_template.go
  website/docs/r/launch_template.html.markdown
Labels: documentation, size/S

#2599 support region cn-wulanchabu
  alicloud/connectivity/regions.go
Labels: size/XS

#2603 modify cen_bandwidth_package
  alicloud/resource_alicloud_cen_bandwidth_package.go
  website/docs/r/cen_bandwidth_package.html.markdown
Labels: documentation, size/XS

#2606 modify cen_route_map
  alicloud/resource_alicloud_cen_route_map_test.go
Labels: size/XS
