Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-04, with the labels that each got.

#2319 fix(ram_user): resolve importing ram user notfound bug
  alicloud/service_alicloud_ram.go
  website/docs/r/ram_user.html.markdown
Labels: documentation, size/S

#2307 Add new resource for alicloud_kms_alias.
  alicloud/provider.go
  alicloud/resource_alicloud_kms_alias.go
  alicloud/resource_alicloud_kms_alias_test.go
  alicloud/service_alicloud_kms.go
  website/alicloud.erb
  website/docs/r/kms_alias.html.markdown
Labels: documentation, size/L

#2323 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2328 Add statistics attribute support ErrorCodeMaximum for cms
  alicloud/resource_alicloud_cms_alarm.go
Labels: size/XS

#2330 fix(nas_rule): resolve pagesize bug
  alicloud/resource_alicloud_nas_access_rule_test.go
  alicloud/service_alicloud_nas.go
Labels: size/M

#2331 improve(snat): add retry error codes
  alicloud/resource_alicloud_snat_entry.go
Labels: size/XS

#2322 alicloud_kms_secret: mark secret_data as sensitive
  alicloud/resource_alicloud_kms_secret.go
Labels: size/XS

#2334 fix create rds instance bug
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#2335 improve(mongodb): supported ssl setting.
  alicloud/resource_alicloud_mongodb_instance.go
  alicloud/resource_alicloud_mongodb_instance_test.go
  alicloud/service_alicloud_mongodb.go
  website/docs/r/mongodb_instance.html.markdown
Labels: documentation, size/L

#2336 new datasource cen_flowlogs
  alicloud/data_source_alicloud_cen_flowlogs.go
  alicloud/data_source_alicloud_cen_flowlogs_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cen_flowlogs.html.markdown
Labels: documentation, size/XL

#2325 Add resource log alert
  alicloud/provider.go
  alicloud/resource_alicloud_log_alert.go
  alicloud/resource_alicloud_log_alert_test.go
  alicloud/service_alicloud_log.go
  go.mod
  website/alicloud.erb
  website/docs/r/log_alert.html.markdown
Labels: documentation, size/XL

#2338 improve(cen_flowlogs): add more parameters
  alicloud/data_source_alicloud_cen_flowlogs.go
  alicloud/data_source_alicloud_cen_flowlogs_test.go
  alicloud/provider.go
  website/docs/d/cen_flowlogs.html.markdown
Labels: documentation, size/M

#2339 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2317 fix(db_instance): resolve deleting db instance bug
  alicloud/resource_alicloud_db_instance.go
  alicloud/service_alicloud_rds.go
Labels: size/S

#2247 eip associate add clientToken support
  alicloud/resource_alicloud_eip_association.go
Labels: size/XS

#2342 Update fc_function.html.markdown
  website/docs/r/fc_function.html.markdown
Labels: documentation, size/XS

#2261 improve(polardb): modify the vsw specified.
  alicloud/data_source_alicloud_polardb_accounts_test.go
  alicloud/data_source_alicloud_polardb_clusters_test.go
  alicloud/data_source_alicloud_polardb_databases_test.go
  alicloud/data_source_alicloud_polardb_endpoints_test.go
  alicloud/resource_alicloud_polardb_account_privilege_test.go
  alicloud/resource_alicloud_polardb_account_test.go
  alicloud/resource_alicloud_polardb_backup_policy_test.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  alicloud/resource_alicloud_polardb_database_test.go
  alicloud/resource_alicloud_polardb_endpoint_address_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/M

#2303 Feature/ecs resource fleet
  alicloud/provider.go
  alicloud/resource_alicloud_auto_provisioning_group.go
  alicloud/resource_alicloud_auto_provisioning_group_test.go
  alicloud/resource_alicloud_log_alert.go
  alicloud/resource_alicloud_log_alert_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/auto_provisioning_group.html.markdown
Labels: documentation, size/XL

#2343 Fix create rds bug
  alicloud/resource_alicloud_db_instance.go
  go.mod
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#2344 private_zone has the wrong description
  website/docs/r/cs_serverless_kubernetes.html.markdown
Labels: documentation, size/XS

#2341 Update fc_trigger.html.markdown
  website/docs/r/fc_trigger.html.markdown
Labels: documentation, size/XS

#2346 Add error retry in delete method.
  alicloud/resource_alicloud_cms_alarm.go
Labels: size/XS

#2348 Update data_source_alicloud_fc_triggers.go
  alicloud/data_source_alicloud_fc_triggers.go
Labels: size/XS

#2349 fix(managed_kubernetes): resolve field version diff issue
  alicloud/resource_alicloud_cs_managed_kubernetes.go
Labels: size/XS

#2350 optimize retryable request for alikafka
  alicloud/resource_alicloud_alikafka_consumer_group.go
  alicloud/resource_alicloud_alikafka_instance.go
  alicloud/resource_alicloud_alikafka_sasl_acl.go
  alicloud/resource_alicloud_alikafka_sasl_user.go
  alicloud/service_alicloud_alikafka.go
Labels: size/M

#2351 fix(rds): fix the bug of parameters modification.
  alicloud/service_alicloud_rds.go
Labels: size/XS

#2345 improve(vpc): vpc and vswitch supported timeouts settings.
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vswitch.go
  alicloud/service_alicloud_vpc.go
  website/docs/r/vpc.html.markdown
  website/docs/r/vswitch.html.markdown
Labels: documentation, size/M

#2352 fix(ram): fix datasource ram users convince bug.
  alicloud/data_source_alicloud_ram_users.go
  website/docs/d/ram_users.html.markdown
Labels: documentation, size/XS

#2354 fix(polardb): fix the bug of parameters modification
  alicloud/service_alicloud_polardb.go
Labels: size/XS

#2290 user want api server's public ip when they set endpoint_public_access…
  alicloud/resource_alicloud_cs_serverless_kubernetes.go
Labels: size/XS

#2356 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2358 remove checking instance type before creating ecs instance ang ess configuration
  alicloud/data_source_alicloud_instance_types.go
  alicloud/data_source_alicloud_zones.go
  alicloud/resource_alicloud_cs_swarm.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#2353 New datesource kms_aliases
  alicloud/data_source_alicloud_kms_aliases.go
  alicloud/data_source_alicloud_kms_aliases_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/kms_aliases.html.markdown
Labels: documentation, size/L

#2362 improve(cen_flowlogs): append output_file
  alicloud/data_source_alicloud_cen_flowlogs.go
Labels: size/XS

#2357 A new datasource for dns domain txt guid.
  alicloud/data_source_alicloud_dns_domain_txt_guid.go
  alicloud/data_source_alicloud_dns_domain_txt_guid_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/dns_domain_txt_guid.html.markdown
Labels: documentation, size/L

#2321 add resource polardb endpoint
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_endpoint.go
  alicloud/resource_alicloud_polardb_endpoint_test.go
  alicloud/service_alicloud_polardb.go
  website/alicloud.erb
  website/docs/r/polardb_endpoint.html.markdown
Labels: documentation, size/XL

#2368 Fix assign variable bug
  alicloud/service_alicloud_alikafka.go
Labels: size/XS

#2364 fix(oss): fix creation_date info displays incorrectly bug.
  alicloud/resource_alicloud_oss_bucket.go
Labels: size/XS

#2361 A new resource for DNS Instance.
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  alicloud/resource_alicloud_dns_instance.go
  alicloud/resource_alicloud_dns_instance_test.go
  alicloud/service_alicloud_dns.go
  website/alicloud.erb
  website/docs/r/dns_instance.html.markdown
Labels: documentation, size/L

#2367 ADB support scale in/out
  alicloud/resource_alicloud_adb_cluster.go
  alicloud/resource_alicloud_adb_cluster_test.go
  website/docs/r/adb_cluster.html.markdown
Labels: documentation, size/S

#2365 A new resource for Dns domain attachment.
  alicloud/provider.go
  alicloud/resource_alicloud_dns_domain_attachment.go
  alicloud/resource_alicloud_dns_domain_attachment_test.go
  alicloud/service_alicloud_dns.go
  website/alicloud.erb
  website/docs/r/dns_domain_attachment.html.markdown
Labels: documentation, size/XL

#2370 Fix alikafka topic tag crate bug
  alicloud/resource_alicloud_alikafka_topic.go
Labels: size/XS

#2372 improve(rds_instance): remove checking zone id
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#2374 improve(cen_instance): support tags
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cen_instance_test.go
  alicloud/service_alicloud_cbn.go
  ci/pipeline.yml
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/L

#2375 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2376 improve(cen_instances): support tags
  alicloud/data_source_alicloud_cen_instances.go
  alicloud/data_source_alicloud_cen_instances_test.go
  alicloud/resource_alicloud_kms_secret.go
  alicloud/service_alicloud_kms.go
  website/docs/d/cen_instances.html.markdown
Labels: documentation, size/XL

#2366 fix(oss): fix the bug of setting a object acl with the wrong option.
  alicloud/data_source_alicloud_oss_bucket_objects_test.go
  alicloud/resource_alicloud_oss_bucket_object.go
Labels: size/XS

#2359 Update oss_bucket.html.markdown
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/XS

#2383 update emr tag resourceType from instance to cluster
  alicloud/common.go
  alicloud/service_alicloud_emr.go
Labels: size/XS

#2382 fix adb account & documents bug
  alicloud/resource_alicloud_adb_account.go
  alicloud/resource_alicloud_adb_account_test.go
  website/docs/d/adb_clusters.html.markdown
  website/docs/r/adb_account.html.markdown
  website/docs/r/adb_backup_policy.html.markdown
  website/docs/r/adb_cluster.html.markdown
Labels: documentation, size/XS

#2387 fix del rds ins task
  alicloud/service_alicloud_rds.go
Labels: size/XS

#2386 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2385 return connection_string after polardb cluster created
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  alicloud/service_alicloud_common_test.go
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/S

#2369 add new data source polardb instance classes
  alicloud/data_source_alicloud_polardb_node_classes.go
  alicloud/data_source_alicloud_polardb_node_classes_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/polardb_node_classes.html.markdown
Labels: documentation, size/XL

#2379 improve: upgraded the sdk and add new resource for DNS domain.
  alicloud/provider.go
  alicloud/resource_alicloud_dns_domain.go
  alicloud/resource_alicloud_dns_domain_test.go
  alicloud/service_alicloud_dns.go
  go.mod
  go.sum
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/copy_gtm_config.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/describe_domains.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/describe_gtm_instance_status.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/describe_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/list_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_domain.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_tag.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_tag_resource.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_tags_in_describe_domains.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_tags_in_describe_tags.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/struct_values.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/tag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/untag_resources.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/import_image.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/struct_instance_type.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/elasticsearch/struct_kibana_private_ip_whitelist.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/elasticsearch/struct_result.go
  vendor/modules.txt
  website/alicloud.erb
  website/docs/r/dns.html.markdown
  website/docs/r/dns_domain.html.markdown
Labels: dependencies, documentation, size/XXL

#2388 fix adb documents bug
  alicloud/resource_alicloud_adb_backup_policy.go
  alicloud/resource_alicloud_adb_cluster.go
  website/docs/r/adb_backup_policy.html.markdown
Labels: documentation, size/XS

#2392 add adb connection resource
  alicloud/provider.go
  alicloud/resource_alicloud_adb_connection.go
  alicloud/resource_alicloud_adb_connection_test.go
  website/alicloud.erb
  website/docs/d/adb_clusters.html.markdown
  website/docs/d/adb_zones.html.markdown
  website/docs/r/adb_account.html.markdown
  website/docs/r/adb_backup_policy.html.markdown
  website/docs/r/adb_cluster.html.markdown
  website/docs/r/adb_connection.html.markdown
Labels: documentation, size/XL

#2396 fix adb test
  alicloud/data_source_alicloud_adb_clusters_test.go
  alicloud/resource_alicloud_adb_account_test.go
  alicloud/resource_alicloud_adb_backup_policy_test.go
  alicloud/resource_alicloud_adb_cluster_test.go
  alicloud/resource_alicloud_adb_connection_test.go
Labels: size/XS

#2389 Add sls log audit
  alicloud/connectivity/client.go
  alicloud/provider.go
  alicloud/resource_alicloud_log_audit.go
  alicloud/resource_alicloud_log_audit_test.go
  alicloud/service_alicloud_log.go
  go.mod
  go.sum
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/restart_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_config_parameters.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_items_in_describe_running_log_records.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_items_in_describe_slow_log_records.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_log_records.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_node_info.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_parameter.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_redis_proxy_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_redis_shard_list.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_tag.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_tags_in_describe_instance_attribute.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/r-kvstore/struct_tags_in_describe_instances.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/analyze_app_log.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/analyze_product_log.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/create_app.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/delete_app.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/describe_app.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/query_saf_service.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/struct_app_model.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sls/update_app.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/klauspost/cpuid/private-gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/net/publicsuffix/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/alicloud.erb
  website/docs/r/log_audit.html.markdown
Labels: dependencies, documentation, size/XXL

#2401 improve dms docs
  ci/pipeline.yml
  website/docs/r/dms_enterprise_instance.html.markdown
Labels: documentation, size/XS

#2402 add test Parameter dependence
  alicloud/resource_alicloud_dms_enterprise_instance_test.go
  alicloud/resource_alicloud_log_audit.go
  alicloud/resource_alicloud_log_audit_test.go
  alicloud/service_alicloud_log.go
  go.mod
Labels: size/S

#2408 Let WriteFile return write/delete errors
  alicloud/common.go
Labels: size/XS

#2407 update changelog.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: dependencies, size/XS

#2411 fix(log_audit): resolve cannot get region
  alicloud/resource_alicloud_log_audit.go
Labels: size/XS
