Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-02, with the labels that each got.

#2154 improve(kvstore_account): correct test case
  alicloud/resource_alicloud_kvstore_account_test.go
Labels: size/XS

#2157 Update CHANGELOH.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2158 improve(db_instances): add more parameters
  CHANGELOG.md
  alicloud/data_source_alicloud_db_instances.go
  alicloud/data_source_alicloud_db_instances_test.go
  website/docs/d/db_instances.html.markdown
Labels: documentation, size/M

#2159 fix(db_account_privilege): resolve privilege timeout bug on PosrgreSql
  CHANGELOG.md
  alicloud/resource_alicloud_db_account_privilege.go
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/service_alicloud_rds.go
Labels: size/L

#2163 improve(cms): add computed for effective_interval
  alicloud/resource_alicloud_cms_alarm.go
  website/docs/r/cms_alarm.html.markdown
Labels: documentation, size/XS

#2167 fixed regional sts endpoint
  alicloud/provider.go
Labels: size/XS

#2164 fix(ram_login_profile): resolve not found when deleting and deprecate alicloud_slb_attachment
  alicloud/resource_alicloud_ram_group.go
  alicloud/resource_alicloud_ram_login_profile.go
  alicloud/resource_alicloud_ram_role.go
  alicloud/resource_alicloud_ram_user.go
  website/docs/r/slb_attachment.html.markdown
  website/docs/r/slb_backend_server.html.markdown
Labels: documentation, size/S

#2171 add market product image id
  alicloud/data_source_alicloud_market_product.go
Labels: size/XS

#2172 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2173 improve(fc_function): remove useless code
  alicloud/resource_alicloud_adb_backup_policy.go
  alicloud/resource_alicloud_fc_function.go
  ci/pipeline.yml
  website/docs/d/market_product.html.markdown
Labels: documentation, size/XS

#2174 improve(ecs_instance): improve security groups
  alicloud/resource_alicloud_instance.go
Labels: size/M

#2170 add support for create snat entry with source_dir
  alicloud/resource_alicloud_snat_entry.go
  alicloud/resource_alicloud_snat_entry_test.go
  examples/vpc-snat/main.tf
  website/docs/r/snat.html.markdown
Labels: documentation, size/S

#2175 improve(ecs_instance): add tags into runInstances request
  alicloud/connectivity/client.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_instance.go
Labels: size/M

#2176 add heyuan region and datasource market supports available_region
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_market_product.go
  alicloud/service_alicloud_market.go
  website/docs/d/market_product.html.markdown
Labels: documentation, size/M

#2177 (improve market_products): supports more filter parameter
  alicloud/data_source_alicloud_market_products.go
  website/docs/d/market_products.html.markdown
Labels: documentation, size/S

#2180 fix(image): fix the bug of created image by disk.
  alicloud/resource_alicloud_image.go
Labels: size/S

#2181 improve(instance): remove sdk mutex and improve instance creating speed
  alicloud/common.go
  alicloud/connectivity/client.go
  alicloud/errors.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#2182 fix(instance): resolve volume_tags diff bug when new resource
  alicloud/resource_alicloud_instance.go
  alicloud/tags.go
Labels: size/M

#2184 improve(vpcs): support outputting tags
  alicloud/data_source_alicloud_vpcs.go
  alicloud/resource_alicloud_vpc.go
  alicloud/resource_alicloud_vpc_test.go
  alicloud/service_alicloud_vpc.go
  website/docs/d/vpcs.html.markdown
Labels: documentation, size/M

#2185 fix(instance): resolve modifying network spec LastOrderProcessing error
  alicloud/data_source_alicloud_instances.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/XS

#2186 fix(instance): resolve LastTokenProcessing error when modifying newor…
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#2187 update SnatEntry test case
  alicloud/resource_alicloud_snat_entry_test.go
Labels: size/XS

#2188 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2189 modify the next release version
  website/docs/d/market_product.html.markdown
  website/docs/d/market_products.html.markdown
  website/docs/r/snat.html.markdown
Labels: documentation, size/XS

#2192 improve(client): remove useless goSdkMutex
  alicloud/connectivity/client.go
Labels: size/M

#2193 add retry for throttling when setting tags
  alicloud/common.go
  alicloud/service_alicloud_rds.go
  alicloud/service_alicloud_slb.go
  alicloud/service_alicloud_vpc.go
Labels: size/M

#2194 improve(nat_gateways): add output vpc_id
  alicloud/data_source_alicloud_nat_gateways.go
  alicloud/data_source_alicloud_nat_gateways_test.go
  alicloud/resource_alicloud_common_bandwidth_package.go
  website/docs/d/nat_gateways.html.markdown
Labels: documentation, size/S

#2195 add sweeper for polardb and hbase
  alicloud/common.go
  alicloud/resource_alicloud_hbase_instance_test.go
  alicloud/resource_alicloud_image_share_permission_test.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  alicloud/resource_alicloud_snat_entry.go
  alicloud/resource_alicloud_vswitch_test.go
Labels: size/L

#2196 improve(snat): add snat_entry_name for this resource
  alicloud/resource_alicloud_snat_entry.go
  alicloud/resource_alicloud_snat_entry_test.go
  website/docs/r/snat.html.markdown
Labels: documentation, size/M

#2199 fix(common_bandwidth): resolve BandwidthPackageOperation.conflict
  alicloud/resource_alicloud_common_bandwidth_package.go
Labels: size/XS

#2200 improve(mns_topic_subscription): supports json
  alicloud/resource_alicloud_mns_topic_subscription.go
  website/docs/r/mns_topic_subscription.html.markdown
Labels: documentation, size/XS

#2204 fix(ess): fix the bug of creating ess scaling group.
  alicloud/errors.go
  alicloud/resource_alicloud_ess_scalinggroup.go
Labels: size/XS

#2205 added filter parameter instance type about data source emr_instance_t…
  alicloud/data_source_alicloud_emr_instance_types.go
  website/docs/d/emr_instance_types.html.markdown
Labels: documentation, size/XS

#2203 improve(polardb): fix update polardb cluster db_node_class will delete instance
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/S

#2206 improve alikafka sweeper test
  CHANGELOG.md
  alicloud/errors.go
  alicloud/resource_alicloud_alikafka_instance_test.go
  alicloud/resource_alicloud_cs_swarm_test.go
  alicloud/resource_alicloud_ess_scalinggroup.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_network_acl_attachment_test.go
  alicloud/resource_alicloud_ssl_vpn_server_test.go
  alicloud/resource_alicloud_vpc_test.go
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/M

#2208 fix(ess): fix create ess scaling group error.
  alicloud/resource_alicloud_ess_scalinggroup.go
Labels: size/XS

#2211 fix(cms_alarm): resolve the creating rule dunplicated
  CHANGELOG.md
  alicloud/resource_alicloud_cen_instance.go
  alicloud/resource_alicloud_cms_alarm.go
Labels: size/XS

#2209 fix(slb): fix slb listener fields and rules creation bug.
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_rule.go
Labels: size/XS

#2210 supported bootstrap action when create a new emr cluster instance
  alicloud/resource_alicloud_emr_cluster.go
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/S
