Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-01, with the labels that each got.

#2020 improve(polardb): feature polardb support connection
  alicloud/data_source_alicloud_polardb_endpoints.go
  alicloud/data_source_alicloud_polardb_endpoints_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_endpoint_address.go
  alicloud/resource_alicloud_polardb_endpoint_address_test.go
  alicloud/service_alicloud_polardb.go
  website/alicloud.erb
  website/docs/d/polardb_endpoints.html.markdown
  website/docs/r/polardb_endpoint_address.html.markdown
Labels: documentation, size/XL

#2040 Modify naming issues in alicloud_image_copy.
  alicloud/provider.go
  alicloud/resource_alicloud_image_copy.go
  alicloud/resource_alicloud_image_copy_test.go
  alicloud/resource_alicloud_polardb_endpoint_address_test.go
  website/alicloud.erb
  website/docs/r/image_copy.html.markdown
Labels: documentation, size/S

#2027 Implement update method for sasl user
  alicloud/resource_alicloud_alikafka_sasl_acl.go
  alicloud/resource_alicloud_alikafka_sasl_user.go
  website/docs/r/alikafka_sasl_acl.html.markdown
  website/docs/r/alikafka_sasl_user.html.markdown
Labels: documentation, size/M

#2043 UpdateChangelog
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2046 ess-rules/groups/configrution three markdown files different with codes
  website/docs/d/ess_scaling_configurations.html.markdown
  website/docs/d/ess_scaling_groups.html.markdown
  website/docs/d/ess_scaling_rules.html.markdown
Labels: documentation, size/XS

#2026 feat(ecs) new resource alicloud_share_image.
  alicloud/errors.go
  alicloud/provider.go
  alicloud/resource_alicloud_iamge_share_permission_test.go
  alicloud/resource_alicloud_image_share_permission.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/image_share_permission.html.markdown
Labels: documentation, size/L

#2036 feat(ecs): new resource alicloud_export_image.
  alicloud/provider.go
  alicloud/resource_alicloud_image_export.go
  alicloud/resource_alicloud_image_export_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/image_export.html.markdown
Labels: documentation, size/XL

#2044 improve(slb): update slb_server_certificate
  alicloud/resource_alicloud_slb_server_certificate.go
Labels: size/XS

#2045 improve(polardb): feature polardb support tags
  alicloud/data_source_alicloud_polardb_clusters.go
  alicloud/data_source_alicloud_polardb_clusters_test.go
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/resource_alicloud_polardb_cluster_test.go
  alicloud/service_alicloud_polardb.go
  website/docs/d/polardb_clusters.html.markdown
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/L

#2048 improve(db_instance): support setting db_instance_storage_type
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  website/docs/d/polardb_clusters.html.markdown
  website/docs/r/db_instance.html.markdown
  website/docs/r/image_export.html.markdown
  website/docs/r/image_share_permission.html.markdown
  website/docs/r/polardb_cluster.html.markdown
Labels: documentation, size/L

#2049 fix(security_group): fix enterprise sg does not support inner access policy from issue #1961 @yongzhang
  CHANGELOG.md
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_security_group.go
Labels: size/XS

#2050 improve(db_readonly_instance): supports tags
  CHANGELOG.md
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_readonly_instance.go
  alicloud/resource_alicloud_db_readonly_instance_test.go
  website/docs/r/db_readonly_instance.html.markdown
Labels: documentation, size/S

#2051 feat(ecs): new resource alicloud_image_import.
  alicloud/provider.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_iamge_share_permission_test.go
  alicloud/resource_alicloud_image.go
  alicloud/resource_alicloud_image_copy.go
  alicloud/resource_alicloud_image_copy_test.go
  alicloud/resource_alicloud_image_export_test.go
  alicloud/resource_alicloud_image_import.go
  alicloud/resource_alicloud_image_import_test.go
  alicloud/resource_alicloud_image_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/r/image.html.markdown
  website/docs/r/image_copy.html.markdown
  website/docs/r/image_import.html.markdown
Labels: documentation, size/XL

#2042 improve(rds): feature rds backup policy improve the functions
  alicloud/diff_suppress_funcs.go
  alicloud/resource_alicloud_db_backup_policy.go
  alicloud/resource_alicloud_db_backup_policy_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_backup_policy.html.markdown
Labels: documentation, size/XL

#2052 Alibaba master
  alicloud/resource_alicloud_image.go
Labels: size/XS

#2055 improve(api): added app_code in attribute apps.
  alicloud/data_source_alicloud_api_gateway_apps.go
  alicloud/data_source_alicloud_api_gateway_apps_test.go
  examples/api-gateway-fc/main.tf
  website/docs/d/api_gateway_apps.html.markdown
Labels: documentation, size/S

#2056 improve(db_instance): support security_group_ids
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_security_group.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#2060 improve(instances): supports ram_role_name
  alicloud/common.go
  alicloud/data_source_alicloud_instances.go
  alicloud/data_source_alicloud_instances_test.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_fc_service.go
  website/docs/d/instances.html.markdown
Labels: documentation, size/M

#2062 improve(instances): improve its efficiency when fetching its disk mappings
  alicloud/data_source_alicloud_instances.go
  alicloud/data_source_alicloud_instances_test.go
Labels: size/M

#2063 fix the bug of ecs instance not supported
  alicloud/data_source_alicloud_emr_instance_types.go
  alicloud/service_alicloud_common_test.go
  website/docs/d/emr_instance_types.html.markdown
Labels: documentation, size/XS

#2061 improve(image): correct docs
  website/docs/r/image.html.markdown
Labels: documentation, size/XS

#2067 improve(listener): supports description
  alicloud/data_source_alicloud_slb_listeners.go
  alicloud/data_source_alicloud_slb_listeners_test.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_ca_certificate_test.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  website/docs/d/slb_listeners.html.markdown
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/L

#2068 modify(market): modify the attributes of market products datasource.
  alicloud/data_source_alicloud_market_products.go
  alicloud/data_source_alicloud_market_products_test.go
  website/docs/d/market_products.html.markdown
Labels: documentation, size/M

#2069 improve(instance_types): support gpu amount and gpu spec
  alicloud/data_source_alicloud_instance_types.go
  website/docs/d/instance_types.html.markdown
Labels: documentation, size/XS

#2070 feat(market): added market product datasource.
  alicloud/data_source_alicloud_market_product.go
  alicloud/data_source_alicloud_market_product_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/market_product.html.markdown
Labels: documentation, size/L

#2078 improve sweeper test for emr
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/resource_alicloud_instance_test.go
Labels: size/S

#2083 improve(polardb): fix polardb add parameters bug
  alicloud/resource_alicloud_polardb_cluster.go
  alicloud/service_alicloud_polardb.go
Labels: size/XS

#2084 feat(market): added new resource alicloud_market_order.
  alicloud/provider.go
  alicloud/resource_alicloud_market_order.go
  alicloud/resource_alicloud_market_order_test.go
  alicloud/service_alicloud_market.go
  website/alicloud.erb
  website/docs/r/market_order.html.markdown
Labels: documentation, size/XL

#2081 improve(test): support force sleep while running testcase
  alicloud/resource_alicloud_actiontrail_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/XS

#2077 improve(slb): update slb_server_certificate
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  website/docs/r/slb_server_certificate.html.markdown
Labels: documentation, size/L

#2086 improve(pvtz): supports proxy_pattern, user_client_ip and lang
  CHANGELOG.md
  alicloud/resource_alicloud_pvtz_zone.go
  alicloud/resource_alicloud_pvtz_zone_test.go
  website/docs/r/pvtz_zone.html.markdown
Labels: documentation, size/M

#2059 fix snat doc's demo error
  website/docs/r/snat.html.markdown
Labels: documentation, size/XS

#2087 improve(hbase): expose the hbase docs
  CHANGELOG.md
  website/alicloud.erb
Labels: documentation, size/XS

#2088 improve(api_gateway_group): add outputs sub_domain and vpc_domain
  CHANGELOG.md
  alicloud/resource_alicloud_api_gateway_group.go
  alicloud/resource_alicloud_slb_server_certificate_test.go
  website/docs/r/api_gateway_group.html.markdown
Labels: documentation, size/XS

#2089 fix(ram_roles): getRole not found error
  CHANGELOG.md
  alicloud/data_source_alicloud_ram_roles.go
Labels: size/XS

#2090 improve(market): supported new field 'search_term'.
  alicloud/data_source_alicloud_market_products.go
  alicloud/data_source_alicloud_market_products_test.go
  website/docs/d/market_products.html.markdown
Labels: documentation, size/M

#2093 fix(instance_types): resolve a bug results from the filed spelling error
  CHANGELOG.md
  alicloud/data_source_alicloud_instance_types.go
  website/docs/d/instance_types.html.markdown
Labels: documentation, size/XS

#2082 improve(rds): feature rds support sql audit records
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: dependencies, documentation, size/M

#2097 improve(pvtz_zone): correct the docs error
  alicloud/data_source_alicloud_alikafka_consumer_groups_test.go
  alicloud/data_source_alicloud_alikafka_sasl_acls_test.go
  alicloud/data_source_alicloud_alikafka_sasl_users_test.go
  alicloud/data_source_alicloud_alikafka_topics_test.go
  alicloud/resource_alicloud_alikafka_consumer_group_test.go
  alicloud/resource_alicloud_alikafka_sasl_acl_test.go
  alicloud/resource_alicloud_alikafka_sasl_user_test.go
  website/docs/r/pvtz_zone.html.markdown
Labels: documentation, size/XS

#2099 improve(elasticsearch): resource support to renew a PrePaid instance
  alicloud/resource_alicloud_elasticsearch_instance.go
  alicloud/service_alicloud_elasticsearch.go
  website/docs/r/elasticsearch.html.markdown
Labels: documentation, size/M

#2105 improve(instance): supports setting auto_release_time #2095
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#2108 improve(rds): fix rds modify db instance spec bug
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
Labels: size/XS

#2110 improve(rds): fix rds modify sql collector policy bug
  alicloud/resource_alicloud_db_instance.go
Labels: size/XS

#2115 improve(instance): close partial
  alicloud/resource_alicloud_instance.go
Labels: size/XS

#2091 improve(rds): feature polardb add data source
  alicloud/data_source_alicloud_polardb_accounts.go
  alicloud/data_source_alicloud_polardb_accounts_test.go
  alicloud/data_source_alicloud_polardb_databases.go
  alicloud/data_source_alicloud_polardb_databases_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_polardb_account.go
  website/alicloud.erb
  website/docs/d/polardb_accounts.html.markdown
  website/docs/d/polardb_databases.html.markdown
  website/docs/r/polardb_account.html.markdown
Labels: documentation, size/XL

#2116 fix:cen_instance.html.markdown(modify docs of name & description)
  website/docs/r/cen_instance.html.markdown
Labels: documentation, size/XS

#2117 improve(kvstore_instance_classes): add validateFunc for engine
  alicloud/data_source_alicloud_kvstore_instance_classes.go
  alicloud/data_source_alicloud_kvstore_instance_classes_test.go
  alicloud/data_source_alicloud_kvstore_instance_engines.go
  alicloud/data_source_alicloud_kvstore_instance_engines_test.go
  website/docs/d/kvstore_instance_classes.html.markdown
  website/docs/d/kvstore_instance_engines.html.markdown
Labels: documentation, size/XS

#2118 fix(drds_instance): resolve parsing response error
  alicloud/data_source_alicloud_polardb_accounts.go
  alicloud/data_source_alicloud_polardb_databases.go
  alicloud/resource_alicloud_drds_instance.go
  go.mod
  go.sum
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/drds/create_drds_instance.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/drds/struct_data_in_create_drds_instance.go
  vendor/modules.txt
  website/docs/r/eip.html.markdown
  website/docs/r/eip_association.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/log_project.html.markdown
  website/docs/r/log_store.html.markdown
  website/docs/r/log_store_index.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
  website/docs/r/security_group.html.markdown
  website/docs/r/security_group_rule.html.markdown
Labels: dependencies, documentation, size/M

#2120 modify:cen_instance_grant.html.markdown("alicloud_cen_instance_grant.foo")
  website/docs/r/cen_instance_grant.html.markdown
Labels: documentation, size/XS

#2119 improve drds and rds sweeper test
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/resource_alicloud_drds_instance_test.go
Labels: size/XS

#2102 improve(slb) update slb_listener add health_check_method
  alicloud/connectivity/regions.go
  alicloud/resource_alicloud_slb_listener.go
  alicloud/resource_alicloud_slb_listener_test.go
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/L

#2094 Update CHANGELOG.md
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: documentation, size/XS

#2121 improve(slb_listener): add document for health_check_method
  CHANGELOG.md
  website/docs/r/log_machine_group.html.markdown
  website/docs/r/logtail_attachment.html.markdown
  website/docs/r/logtail_config.html.markdown
  website/docs/r/slb_listener.html.markdown
Labels: documentation, size/XS

#2127 improve(hbase): add precheck for the test cases
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_hbase_instances_test.go
  alicloud/provider_test.go
  alicloud/resource_alicloud_hbase_instance_test.go
Labels: size/M

#2128 improve(mongodb_sharding): removing the limitation of node_storage
  alicloud/resource_alicloud_mongodb_sharding_instance.go
Labels: size/XS

#2130 added data source emr main versions parameter filter: cluster_type
  alicloud/data_source_alicloud_emr_main_versions.go
  alicloud/resource_alicloud_emr_cluster_test.go
  examples/emr-cluster/main.tf
  website/docs/d/emr_main_versions.html.markdown
  website/docs/r/emr_cluster.html.markdown
Labels: documentation, size/M

#2124 fix the bug of create emr gateway failed and optimized status delay time
  alicloud/resource_alicloud_emr_cluster.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
Labels: size/S

#2135 update changelog and format the code
  CHANGELOG.md
  alicloud/connectivity/client.go
  alicloud/data_source_alicloud_emr_main_versions.go
  alicloud/resource_alicloud_emr_cluster_test.go
  alicloud/service_alicloud_common_test.go
  examples/emr-cluster/main.tf
  website/docs/d/emr_main_versions.html.markdown
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: documentation, size/XS

#2137 fix(instance): resolve the untag bug
  alicloud/resource_alicloud_instance.go
  alicloud/tags.go
Labels: size/XS

#2138 improve(instance): remove the useless method
  alicloud/common.go
  alicloud/resource_alicloud_actiontrail.go
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  alicloud/resource_alicloud_security_group.go
  alicloud/service_alicloud_ecs.go
Labels: size/M

#2141 improve(client): add a method when load endpoint from local file
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
Labels: size/M

#2142 fix(slb): resolve listTags throttling
  alicloud/resource_alicloud_slb_server_certificate_test.go
  alicloud/service_alicloud_slb.go
Labels: size/XS

#2143 fix(ram): resolve ram resources not found error
  alicloud/errors.go
  alicloud/resource_alicloud_polardb_endpoint_address.go
  alicloud/resource_alicloud_ram_access_key_test.go
  alicloud/resource_alicloud_ram_group_membership_test.go
  alicloud/resource_alicloud_ram_login_profile_test.go
  alicloud/resource_alicloud_ram_policy_test.go
  alicloud/resource_alicloud_ram_role_policy_attachment_test.go
  alicloud/resource_alicloud_ram_role_test.go
  alicloud/resource_alicloud_ram_user_policy_attachment_test.go
  alicloud/resource_alicloud_ram_user_test.go
  alicloud/service_alicloud_ram.go
Labels: size/M

#2065 fix vpn bug
  alicloud/data_source_alicloud_ssl_vpn_client_certs.go
  alicloud/data_source_alicloud_ssl_vpn_servers.go
  alicloud/data_source_alicloud_vpn_connections.go
  alicloud/data_source_alicloud_vpn_customer_gateways.go
  alicloud/data_source_alicloud_vpn_gateways.go
  alicloud/resource_alicloud_vpn_gateway.go
  alicloud/service_alicloud_vpn_gateway.go
  examples/vpn/main.tf
  website/alicloud.erb
  website/docs/d/ssl_vpn_servers.html.markdown
  website/docs/d/vpn_customer_gateways.html.markdown
  website/docs/d/vpn_gateways.html.markdown
  website/docs/r/vpn_gateway.html.markdown
  website/docs/r/vpn_route_entry.html.markdown
Labels: documentation, size/S

#2144 improve client endpoint
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_polardb_accounts_test.go
  alicloud/data_source_alicloud_polardb_databases_test.go
  alicloud/data_source_alicloud_polardb_endpoints_test.go
  alicloud/resource_alicloud_dns.go
  alicloud/resource_alicloud_kms_key_test.go
  website/docs/r/ssl_vpn_server.html.markdown
Labels: documentation, size/M

#2146 improve(ram_login_profile): resolve EntityNotExist.User
  alicloud/data_source_alicloud_ons_topics_test.go
  alicloud/service_alicloud_ram.go
Labels: size/XS

#2147 improve(slb): improve set slb tags
  alicloud/data_source_alicloud_slbs.go
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_eip.go
  alicloud/resource_alicloud_eip_test.go
  alicloud/resource_alicloud_route_table.go
  alicloud/resource_alicloud_slb.go
  alicloud/resource_alicloud_slb_acl.go
  alicloud/resource_alicloud_slb_ca_certificate.go
  alicloud/resource_alicloud_slb_server_certificate.go
  alicloud/resource_alicloud_vswitch.go
  alicloud/service_alicloud_slb.go
  alicloud/tags.go
Labels: size/XL

#2148 update changelog
  CHANGELOG.md
Labels: size/XS
