Repository aliyun/terraform-provider-alicloud, pull requests merged in 2020-07, with the labels that each got.

#2598 fix_markdown_ess_notification
  website/docs/r/ess_notification.html.markdown
Labels: documentation, size/XS

#2613 fix_kms_ecs_disk
  alicloud/resource_alicloud_disk.go
  alicloud/resource_alicloud_disk_test.go
  website/docs/r/disk.html.markdown
Labels: documentation, size/S

#2614 fix cms site monitor document
  website/alicloud.erb
  website/docs/r/cms_site_monitor.html.markdown
Labels: documentation, size/XS

#2615 A new resource for eci_image_cache.
  alicloud/connectivity/client.go
  alicloud/connectivity/config.go
  alicloud/connectivity/endpoint.go
  alicloud/provider.go
  alicloud/resource_alicloud_eci_openapi_image_cache.go
  alicloud/resource_alicloud_eci_openapi_image_cache_test.go
  alicloud/service_alicloud_eci.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/create_container_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/create_container_group_from_template.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/create_image_cache.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/delete_container_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/delete_image_cache.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_container_group_metric.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_container_group_price.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_container_groups.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_container_log.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_image_caches.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_multi_container_group_metric.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/describe_regions.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/exec_container_command.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/export_container_group_template.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/restart_container_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/update_container_group.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/eci/update_container_group_by_template.go
  vendor/modules.txt
  website/alicloud.erb
  website/docs/r/eci_openapi_image_cache.html.markdown
Labels: dependencies, documentation, size/XXL

#2594 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2617 A new datasource for WAF instance
  alicloud/data_source_alicloud_waf_instances.go
  alicloud/data_source_alicloud_waf_instances_test.go
  alicloud/provider.go
  alicloud/provider_test.go
  website/alicloud.erb
  website/docs/d/waf_instances.html.markdown
Labels: documentation, size/XL

#2625 fix testcase of WAF instance datasource
  alicloud/data_source_alicloud_waf_instances_test.go
  alicloud/provider_test.go
Labels: size/XS

#2621 fix oss lifecycle rule match the whole bucket by default
  alicloud/resource_alicloud_oss_bucket.go
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/XS

#2622 support the CNAME of CDN domain new
  alicloud/resource_alicloud_cdn_domain_new.go
  website/docs/r/cdn_domain_new.html.markdown
Labels: documentation, size/XS

#2627 A new datasource for eci_image_cache, and modify the eci_openapi to eci.
  alicloud/data_source_alicloud_eci_image_caches.go
  alicloud/data_source_alicloud_eci_image_caches_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_eci_image_cache.go
  alicloud/resource_alicloud_eci_image_cache_test.go
  alicloud/service_alicloud_eci.go
  website/alicloud.erb
  website/docs/d/eci_image_caches.html.markdown
  website/docs/r/eci_image_cache.html.markdown
Labels: documentation, size/XL

#2590 Feature/disable addon
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  alicloud/service_alicloud_cs.go
Labels: size/S

#2604 dms user
  alicloud/common.go
  alicloud/data_source_alicloud_dms_enterprise_users.go
  alicloud/data_source_alicloud_dms_enterprise_users_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_dms_enterprise_user.go
  alicloud/resource_alicloud_dms_enterprise_user_test.go
  alicloud/service_alicloud_dms_enterprise.go
  website/alicloud.erb
  website/docs/d/dms_enterprise_users.html.markdown
  website/docs/r/dms_enterprise_user.html.markdown
Labels: documentation, size/XL

#2480 set system default and make fmt
  alicloud/resource_alicloud_kms_key.go
Labels: size/XS

#2607 A new resource for Container Registry Enterprise Sync Rule.
  alicloud/provider.go
  alicloud/resource_alicloud_cr_ee_sync_rule.go
  alicloud/resource_alicloud_cr_ee_sync_rule_test.go
  alicloud/service_alicloud_cr_ee.go
  website/alicloud.erb
  website/docs/r/cr_ee_sync_rule.html.markdown
Labels: documentation, size/XL

#2628 fix_ess_scheduled_task
  alicloud/resource_alicloud_ess_scheduled_task.go
  alicloud/resource_alicloud_ess_scheduled_task_test.go
  website/docs/r/ess_scheduled_task.html.markdown
Labels: documentation, size/XL

#2589 Deprecated "default_version" for policy and "is_default_version" for policy version.
  alicloud/resource_alicloud_resource_manager_policy.go
  alicloud/resource_alicloud_resource_manager_policy_version.go
  website/docs/r/resource_manager_policy.html.markdown
  website/docs/r/resource_manager_policy_version.html.markdown
  website/docs/r/resource_manager_role.html.markdown
Labels: documentation, size/XS

#2624 feat: rds create ssl and tde func
  alicloud/resource_alicloud_db_instance.go
  alicloud/resource_alicloud_db_instance_test.go
  alicloud/service_alicloud_rds.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/M

#2630 A new datasource for Container Registry Enterprise Sync Rules.
  alicloud/data_source_alicloud_cr_ee_sync_rules.go
  alicloud/data_source_alicloud_cr_ee_sync_rules_test.go
  alicloud/provider.go
  website/alicloud.erb
  website/docs/d/cr_ee_sync_rules.html.markdown
Labels: documentation, size/XL

#2635 Support DescribeInstanceSystemDisk method return the error message.
  alicloud/errors.go
  alicloud/resource_alicloud_instance.go
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#2634 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2636 Add 'testAcc' prefix for test case name.
  alicloud/data_source_alicloud_alidns_domain_groups_test.go
  alicloud/resource_alicloud_resource_manager_account_test.go
Labels: size/XS

#2638 fix testcase name
  alicloud/data_source_alicloud_cen_private_zones_test.go
  alicloud/data_source_alicloud_cen_route_maps_test.go
  alicloud/data_source_alicloud_resource_manager_folders_test.go
  alicloud/data_source_alicloud_resource_manager_policies_test.go
  alicloud/data_source_alicloud_resource_manager_policy_versions_test.go
  alicloud/data_source_alicloud_resource_manager_roles_test.go
  alicloud/resource_alicloud_resource_manager_folder_test.go
  alicloud/resource_alicloud_resource_manager_policy_test.go
  alicloud/resource_alicloud_resource_manager_policy_version_test.go
Labels: size/XS

#2640 fix WAF instance testcase
  alicloud/data_source_alicloud_waf_instances_test.go
  alicloud/resource_alicloud_waf_instance_test.go
Labels: size/S

#2632 fix_instance
  alicloud/resource_alicloud_instance.go
  alicloud/resource_alicloud_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#2641 Remove the resource_group_id parameter when querying the system disk.
  alicloud/service_alicloud_ecs.go
Labels: size/XS

#2647 fix_markdown_ess_scheduled_task
  website/docs/r/ess_scheduled_task.html.markdown
Labels: size/XS

#2648 cassandra doc fix
  website/alicloud.erb
Labels: documentation, size/M

#2642 add isp support to cbwp
  alicloud/resource_alicloud_common_bandwidth_package.go
  website/docs/r/common_bandwidth_package.html.markdown
Labels: documentation, size/XS

#2645 perf: rds ssl and tde limitation
  alicloud/resource_alicloud_db_instance.go
  website/docs/r/db_instance.html.markdown
Labels: documentation, size/XS

#2649 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
  website/docs/r/common_bandwidth_package.html.markdown
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#2644 modify cen_instance
  alicloud/resource_alicloud_cen_instance_attachment.go
Labels: size/XS

#2655 fix_markdown_ess_scheduled_task
  website/docs/r/ess_scheduled_task.html.markdown
Labels: documentation, size/XS

#2653 fix slb_listener creates NewCommonRequest error handling.
  alicloud/service_alicloud_slb.go
Labels: size/XS

#2656 fix dms instance
  alicloud/data_source_alicloud_dms_enterprise_instances_test.go
  alicloud/resource_alicloud_dms_enterprise_instance.go
  alicloud/resource_alicloud_dms_enterprise_instance_test.go
Labels: size/XL

#2661 add example moudle for OSS bucket
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/XS

#2652 Add new resource and datasource of ecs ddh
  alicloud/connectivity/client.go
  alicloud/connectivity/endpoint.go
  alicloud/data_source_alicloud_ecs_dedicated_hosts.go
  alicloud/data_source_alicloud_ecs_dedicated_hosts_test.go
  alicloud/provider.go
  alicloud/resource_alicloud_ecs_dedicated_host.go
  alicloud/resource_alicloud_ecs_dedicated_host_test.go
  alicloud/service_alicloud_ecs.go
  website/alicloud.erb
  website/docs/d/ecs_dedicated_hosts.html.markdown
  website/docs/r/ecs_dedicated_host.html.markdown
Labels: documentation, size/XXL

#2663 correct log alert testcase name
  alicloud/resource_alicloud_log_alert_test.go
  ci/pipeline.yml
Labels: size/XS

#2665 fix ddh testcase
  alicloud/data_source_alicloud_ecs_dedicated_hosts_test.go
  alicloud/resource_alicloud_ecs_dedicated_host_test.go
Labels: size/XS

#2654 drds support internation
  alicloud/connectivity/regions.go
  alicloud/data_source_alicloud_drds_instances.go
  alicloud/data_source_alicloud_drds_instances_test.go
  alicloud/resource_alicloud_drds_instance.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/service_alicloud_drds.go
  website/docs/d/drds_instances.html.markdown
  website/docs/r/drds_instance.html.markdown
Labels: documentation, size/L

#2669 update: add nat binded eip ipaddress
  alicloud/data_source_alicloud_nat_gateways.go
  alicloud/data_source_alicloud_nat_gateways_test.go
  website/docs/d/nat_gateways.html.markdown
Labels: documentation, size/XS

#2671 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS

#2672 improve test case name
  CHANGELOG.md
  alicloud/resource_alicloud_db_account_privilege_test.go
  alicloud/resource_alicloud_dms_enterprise_instance.go
  alicloud/resource_alicloud_drds_instance_test.go
  alicloud/resource_alicloud_polardb_account_privilege_test.go
  alicloud/resource_alicloud_polardb_cluster_test.go
Labels: size/M

#2573 Support service_account_issuer and api_audiences in alicloud_cs_kubernetes and alicloud_cs_managed_kubernetes
  alicloud/resource_alicloud_cs_kubernetes.go
  alicloud/resource_alicloud_cs_managed_kubernetes.go
  website/docs/r/cs_kubernetes.html.markdown
  website/docs/r/cs_managed_kubernetes.html.markdown
Labels: dependencies, documentation, size/S

#2662 Supports setting the kms id for oss bucket.
  alicloud/data_source_alicloud_oss_buckets.go
  alicloud/data_source_alicloud_oss_buckets_test.go
  alicloud/resource_alicloud_oss_bucket.go
  alicloud/resource_alicloud_oss_bucket_test.go
  website/docs/d/oss_buckets.html.markdown
  website/docs/r/oss_bucket.html.markdown
Labels: documentation, size/M

#2668 Fix ess kms disk
  alicloud/data_source_alicloud_nat_gateways.go
  alicloud/resource_alicloud_ess_scalingconfiguration.go
  alicloud/resource_alicloud_ess_scalingconfiguration_test.go
  alicloud/service_alicloud_ess.go
  website/docs/r/ess_scaling_configuration.html.markdown
Labels: documentation, size/L

#2675 modify alicloud_cen_bandwidth_package_attachment
  alicloud/resource_alicloud_cen_bandwidth_package_attachment.go
Labels: size/XS

#2683 Support 'resoruce_group_id' attribute for ImportKeyPair.
  alicloud/resource_alicloud_key_pair.go
  website/docs/r/key_pair.html.markdown
Labels: documentation, size/XS

#2681 UPDATE CHANGELOG
  CHANGELOG.md
  alicloud/connectivity/client.go
Labels: size/XS
